-- Esquema PostgreSQL para Panel REPuve Mantenimientos
-- Ejecutar dentro de la base de datos remota ya creada.

CREATE TABLE IF NOT EXISTS users (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    username VARCHAR(100) NOT NULL UNIQUE,
    password VARCHAR(255) NOT NULL,
    role VARCHAR(30) NOT NULL DEFAULT 'user',
    created_at TIMESTAMP WITHOUT TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS ubicaciones (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre VARCHAR(120) NOT NULL UNIQUE,
    lat VARCHAR(50),
    lng VARCHAR(50)
);

CREATE TABLE IF NOT EXISTS materiales (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre VARCHAR(150) NOT NULL,
    medida VARCHAR(30) NOT NULL DEFAULT 'pz',
    foto VARCHAR(255),
    serie VARCHAR(120)
);

CREATE TABLE IF NOT EXISTS arcos (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre VARCHAR(150) NOT NULL UNIQUE,
    ubicacion_id INTEGER NOT NULL REFERENCES ubicaciones(id) ON DELETE RESTRICT,
    fecha_instalacion TIMESTAMP WITHOUT TIME ZONE,
    lat VARCHAR(50),
    lng VARCHAR(50)
);

CREATE TABLE IF NOT EXISTS arco_material (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    arco_id INTEGER NOT NULL REFERENCES arcos(id) ON DELETE CASCADE,
    material_id INTEGER NOT NULL REFERENCES materiales(id) ON DELETE RESTRICT,
    cantidad NUMERIC(12, 2) NOT NULL DEFAULT 1,
    foto VARCHAR(255),
    serie VARCHAR(120),
    creado_at TIMESTAMP WITHOUT TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS revisiones (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    arco_id INTEGER NOT NULL REFERENCES arcos(id) ON DELETE CASCADE,
    fecha_mantenimiento TIMESTAMP WITHOUT TIME ZONE NOT NULL,
    tipo_mantenimiento VARCHAR(20) NOT NULL DEFAULT 'Correctivo',
    observaciones TEXT,
    tecnico_responsable VARCHAR(150)
);

CREATE TABLE IF NOT EXISTS revision_material (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    revision_id INTEGER NOT NULL REFERENCES revisiones(id) ON DELETE CASCADE,
    arco_material_id INTEGER REFERENCES arco_material(id) ON DELETE SET NULL,
    material_id INTEGER NOT NULL REFERENCES materiales(id) ON DELETE RESTRICT,
    cantidad NUMERIC(12, 2) NOT NULL DEFAULT 1,
    foto VARCHAR(255),
    serie VARCHAR(120),
    accion VARCHAR(20) NOT NULL DEFAULT 'cambio'
);

CREATE TABLE IF NOT EXISTS revision_evidencias (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    revision_id INTEGER NOT NULL REFERENCES revisiones(id) ON DELETE CASCADE,
    filename VARCHAR(255) NOT NULL,
    mimetype VARCHAR(100),
    created_at TIMESTAMP WITHOUT TIME ZONE,
    uploaded_at TIMESTAMP WITHOUT TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS infraestructura_nodos (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tipo VARCHAR(40) NOT NULL DEFAULT 'Puente/Poste',
    nombre VARCHAR(150) NOT NULL,
    ubicacion_id INTEGER REFERENCES ubicaciones(id) ON DELETE SET NULL,
    lat VARCHAR(50),
    lng VARCHAR(50),
    descripcion TEXT,
    created_at TIMESTAMP WITHOUT TIME ZONE,
    creado_at TIMESTAMP WITHOUT TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    UNIQUE (tipo, nombre)
);

CREATE TABLE IF NOT EXISTS arco_infraestructura (
    id INTEGER,
    arco_id INTEGER NOT NULL REFERENCES arcos(id) ON DELETE CASCADE,
    infraestructura_id INTEGER NOT NULL REFERENCES infraestructura_nodos(id) ON DELETE CASCADE,
    PRIMARY KEY (arco_id, infraestructura_id)
);

CREATE TABLE IF NOT EXISTS infraestructura_material (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    infraestructura_id INTEGER NOT NULL REFERENCES infraestructura_nodos(id) ON DELETE CASCADE,
    material_id INTEGER NOT NULL REFERENCES materiales(id) ON DELETE RESTRICT,
    cantidad NUMERIC(12, 2) NOT NULL DEFAULT 1,
    serie VARCHAR(120),
    fecha_instalacion TIMESTAMP WITHOUT TIME ZONE
);

CREATE TABLE IF NOT EXISTS infraestructura_revisiones (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    infraestructura_id INTEGER NOT NULL REFERENCES infraestructura_nodos(id) ON DELETE CASCADE,
    fecha_mantenimiento TIMESTAMP WITHOUT TIME ZONE NOT NULL,
    tipo_mantenimiento VARCHAR(20) NOT NULL DEFAULT 'Correctivo',
    observaciones TEXT,
    tecnico_responsable VARCHAR(150),
    created_at TIMESTAMP WITHOUT TIME ZONE
);

CREATE TABLE IF NOT EXISTS infraestructura_revision_material (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    revision_id INTEGER NOT NULL REFERENCES infraestructura_revisiones(id) ON DELETE CASCADE,
    material_id INTEGER NOT NULL REFERENCES materiales(id) ON DELETE RESTRICT,
    cantidad NUMERIC(12, 2) NOT NULL DEFAULT 1,
    serie VARCHAR(120)
);

CREATE TABLE IF NOT EXISTS infraestructura_revision_evidencias (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    revision_id INTEGER NOT NULL REFERENCES infraestructura_revisiones(id) ON DELETE CASCADE,
    filename VARCHAR(255) NOT NULL,
    mimetype VARCHAR(100),
    uploaded_at TIMESTAMP WITHOUT TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS bitacoras_arco (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    arco_id INTEGER NOT NULL REFERENCES arcos(id) ON DELETE CASCADE,
    encargado VARCHAR(150),
    observaciones TEXT,
    fecha_registro TIMESTAMP WITHOUT TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS checklist_conceptos (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre VARCHAR(255) NOT NULL,
    activo INTEGER NOT NULL DEFAULT 1
);

CREATE TABLE IF NOT EXISTS bitacora_checklist (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    bitacora_id INTEGER NOT NULL REFERENCES bitacoras_arco(id) ON DELETE CASCADE,
    concepto_id INTEGER NOT NULL REFERENCES checklist_conceptos(id) ON DELETE RESTRICT,
    realizado INTEGER NOT NULL DEFAULT 1,
    UNIQUE (bitacora_id, concepto_id)
);

CREATE INDEX IF NOT EXISTS idx_arcos_ubicacion_id ON arcos (ubicacion_id);
CREATE INDEX IF NOT EXISTS idx_arco_material_arco_id ON arco_material (arco_id);
CREATE INDEX IF NOT EXISTS idx_arco_material_material_id ON arco_material (material_id);
CREATE INDEX IF NOT EXISTS idx_revisiones_arco_id ON revisiones (arco_id);
CREATE INDEX IF NOT EXISTS idx_revisiones_fecha ON revisiones (fecha_mantenimiento);
CREATE INDEX IF NOT EXISTS idx_revision_material_revision_id ON revision_material (revision_id);
CREATE INDEX IF NOT EXISTS idx_revision_material_arco_material_id ON revision_material (arco_material_id);
CREATE INDEX IF NOT EXISTS idx_revision_evidencias_revision_id ON revision_evidencias (revision_id);
CREATE INDEX IF NOT EXISTS idx_infraestructura_nodos_ubicacion_id ON infraestructura_nodos (ubicacion_id);
CREATE INDEX IF NOT EXISTS idx_infraestructura_material_infra_id ON infraestructura_material (infraestructura_id);
CREATE INDEX IF NOT EXISTS idx_infraestructura_revisiones_infra_id ON infraestructura_revisiones (infraestructura_id);
CREATE INDEX IF NOT EXISTS idx_infra_revision_material_revision_id ON infraestructura_revision_material (revision_id);
CREATE INDEX IF NOT EXISTS idx_infra_revision_evidencias_revision_id ON infraestructura_revision_evidencias (revision_id);
CREATE INDEX IF NOT EXISTS idx_bitacoras_arco_id ON bitacoras_arco (arco_id);
