<?php
include('../views/header.php');
include('../config/db.php');
require_once '../config/tecnicos_schema.php';

$pdo->exec("
  CREATE TABLE IF NOT EXISTS tecnicos (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre VARCHAR(150) NOT NULL UNIQUE,
    telefono VARCHAR(30),
    puesto VARCHAR(80),
    activo INTEGER NOT NULL DEFAULT 1,
    eliminado INTEGER NOT NULL DEFAULT 0,
    created_at TIMESTAMP WITHOUT TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP
  )
");
$pdo->exec("CREATE INDEX IF NOT EXISTS idx_tecnicos_activo ON tecnicos (activo)");
$pdo->exec("ALTER TABLE tecnicos ADD COLUMN IF NOT EXISTS eliminado INTEGER NOT NULL DEFAULT 0");
asegurarRelacionTecnicos($pdo);
$tecnicosActivos = $pdo->query("SELECT id, nombre FROM tecnicos WHERE activo = 1 AND COALESCE(eliminado, 0) = 0 ORDER BY nombre ASC")->fetchAll(PDO::FETCH_ASSOC);

$revisionesCssVersion = file_exists(__DIR__ . '/../css/revisiones.css') ? filemtime(__DIR__ . '/../css/revisiones.css') : time();
$revisionesJsVersion = file_exists(__DIR__ . '/../js/revisiones2.js') ? filemtime(__DIR__ . '/../js/revisiones2.js') : time();
?>

<link rel="stylesheet" href="../css/revisiones.css?v=<?= $revisionesCssVersion ?>">

<div class="d-flex justify-content-between align-items-center mb-3">
  <?php if (isset($_GET["msg"])): ?>
    <div id="notifSuccess" class="notification alert alert-success alert-dismissible fade show" style="position: fixed; top: 20px; right: 20px; width: 300px; z-index: 1050;
            background-color: #4CAF50; color: white; border-radius: 8px;
            box-shadow: 0 4px 12px rgba(0, 0, 0, 0.3); padding: 20px; padding-top: 30px; text-align: center;">
      <strong>Éxito!</strong> <?= htmlspecialchars($_GET["msg"]) ?>
    </div>

    <script>
      // Quitar el parámetro msg de la URL SIN recargar
      if (window.history.replaceState) {
        const url = new URL(window.location.href);
        url.searchParams.delete('msg');
        window.history.replaceState({}, document.title, url.toString());
      }

      // Ocultar notificación automáticamente
      setTimeout(() => {
        const n = document.getElementById('notifSuccess');
        if (n) {
          n.style.transition = "opacity 0.5s ease";
          n.style.opacity = "0";
          setTimeout(() => n.remove(), 500);
        }
      }, 3000);
    </script>
  <?php endif; ?>

  <?php if (isset($_GET["error"])): ?>
    <div id="notifSuccess" class="notification alert alert-success alert-dismissible fade show" style="position: fixed; top: 20px; right: 20px; width: 300px; z-index: 1050;
          background-color: #fe0000ff; color: white; border-radius: 8px;
          box-shadow: 0 4px 12px rgba(0, 0, 0, 0.3); padding: 20px; padding-top: 30px; text-align: center;">

      <strong>Error!</strong> <?= htmlspecialchars($_GET["error"]) ?>
    </div>

    <script>
      // Quitar el parámetro msg de la URL SIN recargar
      if (window.history.replaceState) {
        const url = new URL(window.location.href);
        url.searchParams.delete('error');
        window.history.replaceState({}, document.title, url.toString());
      }

      // Ocultar notificación automáticamente
      setTimeout(() => {
        const n = document.getElementById('notifSuccess');
        if (n) {
          n.style.transition = "opacity 0.5s ease";
          n.style.opacity = "0";
          setTimeout(() => n.remove(), 500);
        }
      }, 3000);
    </script>
  <?php endif; ?>
</div>

<div class="container">

  <div class="text-center revisiones-page-heading">
    <h1 class="fw-bold text-dark">
      📋Mantenimiento
    </h1>
    <hr class="mt-2 mx-auto" style="width:60%; border-top:3px solid #28a745; ">
  </div>

  <div class="revisiones-table-switch d-flex justify-content-center mb-3">
    <div class="btn-group shadow-sm" role="group" aria-label="Cambiar tabla de mantenimiento">
      <button type="button" class="btn btn-success active revision-tabla-toggle-btn" data-table-view-target="revisionViewArcos">
        <i class="bi bi-bounding-box-circles"></i> Arcos
      </button>
      <button type="button" class="btn btn-outline-primary revision-tabla-toggle-btn" data-table-view-target="revisionViewInfra">
        <i class="bi bi-broadcast-pin"></i> Puentes / Sitios
      </button>
    </div>
  </div>

  <div class="card shadow-sm rounded revisiones-table-view" id="revisionViewArcos">

    <div class=" interfaz justify-content-between align-items-center  gap-1 p-1" style="height: 80px; display:flex;">

      <!-- BOTÓN IZQUIERDA -->
      <button class="btn btn-success shadow-sm" style="padding: 8px 10px;" data-bs-toggle="modal"
        data-bs-target="#modalRevision">
        <i class="bi bi-plus-circle me-1"></i> Registrar Mantenimiento
      </button>

      <button class="btn btn-primary shadow-sm d-none" style="padding: 8px 10px;" data-bs-toggle="modal"
        data-bs-target="#modalRevisionInfra">
        <i class="bi bi-broadcast-pin me-1"></i> Puente/Sitio
      </button>

      <!-- BUSCADOR DERECHA -->
      <div class="input-group" style="width: 30%; padding: 8px 10px; ">
        <span class="input-group-text bg-success text-white">
          <i class="bi bi-search"></i>
        </span>
        <input type="search" id="searchRevisiones" class="form-control shadow-sm" placeholder="Buscar Mantenimiento..."
          onkeyup="filterTable('searchRevisiones', 'revisionesTable')">
      </div>
    </div>

    <div class="revision-tabla-scroll">
    <table id="revisionesTable" class="table table-striped align-middle mb-0">
      <thead class="table-dark text-center">
        <tr>
          <th>ID</th>
          <th>Arco</th>
          <th>Fecha</th>
          <th>Tipo</th>
          <th>Componentes Cambiados / Agregados</th>
          <th>Acciones</th>
        </tr>
      </thead>
      <tbody class="text-center">
        <?php
        $sql = "SELECT r.*, a.nombre AS arco, u.nombre AS ubic, a.lat AS lat, a.lng AS lng, t.nombre AS tecnicoresponsable,
                (SELECT COUNT(*) FROM revision_evidencias re WHERE re.revision_id = r.id) AS evidencias_count
                FROM revisiones r
                JOIN arcos a ON r.arco_id=a.id
                JOIN ubicaciones u ON a.ubicacion_id=u.id
                LEFT JOIN tecnicos t ON t.id = r.tecnico_id
                WHERE COALESCE(a.estado, 'Activo') <> 'Baja'
                ORDER BY r.fecha_mantenimiento DESC";

        $revisiones = $pdo->query($sql)->fetchAll(PDO::FETCH_ASSOC);
        if (count($revisiones) === 0): ?>

          <tr>
            <td colspan="6" class="text-center text-muted py-4">
              <i class="bi bi-info-circle"></i> No hay revisiones registradas.
            </td>
          </tr>
        <?php else: ?>
          <?php foreach ($revisiones as $r):
            $mats = $pdo->prepare("SELECT rm.*, rm.id AS relacion_id, m.medida as medida, m.foto as foto, m.nombre AS material, r.fecha_mantenimiento AS fecha_mantenimiento
                                FROM revision_material rm 
                                JOIN materiales m ON rm.material_id=m.id 
                                JOIN revisiones r ON rm.revision_id = r.id
                                WHERE rm.revision_id=?
                                ORDER BY rm.id ASC");
            $mats->execute([$r['id']]);
            $lista = $mats->fetchAll();
            $detalleMantenimiento = [
              'id' => $r['id'],
              'origen' => 'Arco',
              'objetivo' => $r['arco'],
              'ubicacion' => $r['ubic'],
              'fecha' => $r['fecha_mantenimiento'],
              'tipo' => $r['tipo_mantenimiento'] ?? 'Correctivo',
              'tecnico' => $r['tecnicoresponsable'] ?? '',
              'observaciones' => $r['observaciones'] ?? '',
              'evidencias' => (int)($r['evidencias_count'] ?? 0),
              'evidencias_ajax' => true,
              'pdf' => "../views/pdf/revision_pdf.php?id={$r['id']}",
              'pdf_download' => "../controllers/pdf_controller.php?action=mantenimiento&id={$r['id']}&download=1",
              'materiales' => $lista
            ];
            ?>
            <tr data-lat="<?= htmlspecialchars($r['lat'] ?? '') ?>" data-lng="<?= htmlspecialchars($r['lng'] ?? '') ?>">
              <td class="text-center fw-semibold"><?= $r['id'] ?></td>
              <td>
                <?= htmlspecialchars($r['arco']) ?><br>
                <small class="text-muted"><?= htmlspecialchars($r['ubic']) ?></small>
              </td>
              <td><?= date("d-m-Y", strtotime($r['fecha_mantenimiento'])) ?></td>
              <td>
                <?php $tipoMant = $r['tipo_mantenimiento'] ?? 'Correctivo'; ?>
                <span class="badge <?= $tipoMant === 'Correctivo' ? 'bg-warning text-dark' : 'bg-success' ?>">
                  <?= htmlspecialchars($tipoMant) ?>
                </span>
              </td>
              <td>
                <button class="btn btn-sm btn-info verMaterialesBtn" data-id="<?= $r['id'] ?>"
                  data-materiales='<?= htmlspecialchars(json_encode($lista), ENT_QUOTES, "UTF-8") ?>' data-bs-toggle="modal"
                  data-bs-target="#modalMateriales">
                  <i class="bi bi-box-seam"></i> Componentes
                </button>
              </td>
              <td class="text-center">
                <button type="button" class="btn btn-outline-success btn-sm verFormatosRevisionBtn"
                  data-revision-id="<?= $r['id'] ?>"
                  data-arco-id="<?= $r['arco_id'] ?>"
                  data-objetivo="<?= htmlspecialchars($r['arco'], ENT_QUOTES, 'UTF-8') ?>"
                  data-tipo-objetivo="Arco"
                  data-ubicacion="<?= htmlspecialchars($r['ubic'], ENT_QUOTES, 'UTF-8') ?>"
                  data-fecha="<?= htmlspecialchars($r['fecha_mantenimiento'], ENT_QUOTES, 'UTF-8') ?>"
                  data-tipo-mant="<?= htmlspecialchars($r['tipo_mantenimiento'] ?? 'Correctivo', ENT_QUOTES, 'UTF-8') ?>"
                  data-tecnico-id="<?= (int)($r['tecnico_id'] ?? 0) ?>"
                  data-tecnico-nombre="<?= htmlspecialchars($r['tecnicoresponsable'] ?? '', ENT_QUOTES, 'UTF-8') ?>"
                  data-bs-toggle="modal" data-bs-target="#modalFormatosMantenimiento"
                  title="Formatos de servicio (Checklist, Calidad, Herramientas)">
                  <i class="bi bi-file-earmark-check"></i>
                </button>

                <button type="button" class="btn btn-outline-secondary btn-sm verDetalleMantenimientoBtn"
                  data-detalle='<?= htmlspecialchars(json_encode($detalleMantenimiento, JSON_HEX_APOS | JSON_HEX_QUOT | JSON_HEX_AMP | JSON_HEX_TAG), ENT_QUOTES, "UTF-8") ?>'
                  data-bs-toggle="modal" data-bs-target="#modalDetalleMantenimiento"
                  title="Ver detalle">
                  <i class="bi bi-eye"></i>
                </button>

                <form action="../controllers/revisiones_controller.php" method="POST" class="d-inline eliminar-form">
                  <input type="hidden" name="action" value="delete">
                  <input type="hidden" name="id" value="<?= $r['id'] ?>">
                  <button type="submit" class="btn btn-outline-danger btn-sm" title="Eliminar revisión">
                    <i class="bi bi-trash"></i>
                  </button>
                </form>

                <a href="../views/pdf/revision_pdf.php?id=<?= $r['id'] ?>" 
                  target="_blank"
                  class="btn btn-danger btn-sm"
                  title="Ver / Imprimir PDF">
                  <i class="bi bi-file-earmark-pdf"></i>
                </a>
              </td>
            </tr>
          <?php endforeach; ?>
        <?php endif; ?>
      </tbody>
    </table>
    </div>
    <div id="pagination-revisiones" class="d-flex justify-content-center mt-3"></div>
  </div>

  <div class="card shadow-sm rounded revisiones-table-view d-none" id="revisionViewInfra">
    <div class="interfaz justify-content-between align-items-center gap-1 p-2 border-bottom d-flex">
      <!-- BOTÓN IZQUIERDA -->
      <button class="btn btn-success shadow-sm" style="padding: 8px 14px;" data-bs-toggle="modal"
        data-bs-target="#modalRevision">
        <i class="bi bi-plus-circle me-1"></i> Registrar Mantenimiento
      </button>

      <!-- BUSCADOR DERECHA -->
      <div class="input-group" style="max-width: 320px; width: 100%;">
        <span class="input-group-text bg-primary text-white">
          <i class="bi bi-search"></i>
        </span>
        <input type="search" id="searchInfraRevisiones" class="form-control shadow-sm" placeholder="Buscar Puente / Sitio..."
          onkeyup="filterTable('searchInfraRevisiones', 'infraRevisionesTable')">
      </div>
    </div>
    <div class="revision-tabla-scroll">
    <table id="infraRevisionesTable" class="table table-striped align-middle mb-0">
      <thead class="table-dark text-center">
        <tr>
          <th>ID</th>
          <th>Puente/Sitio</th>
          <th>Fecha</th>
          <th>Tipo</th>
          <th>Componentes</th>
          <th>Acciones</th>
        </tr>
      </thead>
      <tbody class="text-center">
        <?php
        $infraSql = "
          SELECT ir.*, n.nombre AS infraestructura, n.tipo AS tipo_infraestructura, u.nombre AS ubicacion,
                 t.nombre AS tecnico_nombre,
                 (SELECT COUNT(*) FROM infraestructura_revision_evidencias ire WHERE ire.revision_id = ir.id) AS evidencias_count
          FROM infraestructura_revisiones ir
          JOIN infraestructura_nodos n ON n.id = ir.infraestructura_id
          LEFT JOIN ubicaciones u ON u.id = n.ubicacion_id
          LEFT JOIN tecnicos t ON t.id = ir.tecnico_id
          ORDER BY ir.fecha_mantenimiento DESC
        ";
        $infraRevisiones = $pdo->query($infraSql)->fetchAll(PDO::FETCH_ASSOC);
        if (count($infraRevisiones) === 0): ?>
          <tr>
            <td colspan="6" class="text-center text-muted py-4">
              <i class="bi bi-info-circle"></i> No hay mantenimientos de puentes o sitios registrados.
            </td>
          </tr>
        <?php else: ?>
          <?php foreach ($infraRevisiones as $ir):
            $infraMats = $pdo->prepare("
              SELECT irm.*, irm.id AS relacion_id, m.medida, m.foto, m.nombre AS material, ir.fecha_mantenimiento
              FROM infraestructura_revision_material irm
              JOIN materiales m ON irm.material_id = m.id
              JOIN infraestructura_revisiones ir ON irm.revision_id = ir.id
              WHERE irm.revision_id = ?
              ORDER BY irm.id ASC
            ");
            $infraMats->execute([$ir['id']]);
            $infraLista = $infraMats->fetchAll(PDO::FETCH_ASSOC);
            $detalleInfraMantenimiento = [
              'id' => $ir['id'],
              'origen' => $ir['tipo_infraestructura'] ?? 'Puente/Sitio',
              'objetivo' => $ir['infraestructura'],
              'ubicacion' => $ir['ubicacion'] ?? '',
              'fecha' => $ir['fecha_mantenimiento'],
              'tipo' => $ir['tipo_mantenimiento'] ?? 'Correctivo',
              'tecnico' => $ir['tecnico_nombre'] ?? '',
              'observaciones' => $ir['observaciones'] ?? '',
              'evidencias' => (int)($ir['evidencias_count'] ?? 0),
              'evidencias_ajax' => true,
              'evidencias_tipo' => 'infra',
              'pdf' => '',
              'materiales' => $infraLista
            ];
          ?>
            <tr>
              <td class="fw-semibold"><?= htmlspecialchars($ir['id']) ?></td>
              <td>
                <?= htmlspecialchars($ir['infraestructura']) ?><br>
                <small class="text-muted"><?= htmlspecialchars($ir['tipo_infraestructura']) ?></small>
                <?php if (!empty($ir['ubicacion'])): ?>
                  <br><small class="text-muted"><?= htmlspecialchars($ir['ubicacion']) ?></small>
                <?php endif; ?>
              </td>
              <td><?= date("d-m-Y", strtotime($ir['fecha_mantenimiento'])) ?></td>
              <td>
                <span class="badge <?= $ir['tipo_mantenimiento'] === 'Correctivo' ? 'bg-warning text-dark' : 'bg-success' ?>">
                  <?= htmlspecialchars($ir['tipo_mantenimiento']) ?>
                </span>
              </td>
              <td>
                <button class="btn btn-sm btn-info verInfraMaterialesBtn"
                  data-materiales='<?= htmlspecialchars(json_encode($infraLista, JSON_HEX_APOS | JSON_HEX_QUOT | JSON_HEX_AMP | JSON_HEX_TAG), ENT_QUOTES, "UTF-8") ?>'
                  data-bs-toggle="modal" data-bs-target="#modalMateriales">
                  <i class="bi bi-box-seam"></i> Componentes
                </button>
              </td>
              <td class="text-center">
                <button type="button" class="btn btn-outline-success btn-sm verFormatosRevisionBtn"
                  data-infra-revision-id="<?= $ir['id'] ?>"
                  data-infraestructura-id="<?= $ir['infraestructura_id'] ?>"
                  data-objetivo="<?= htmlspecialchars($ir['infraestructura'], ENT_QUOTES, 'UTF-8') ?>"
                  data-tipo-objetivo="<?= htmlspecialchars($ir['tipo_infraestructura'] ?? 'Puente/Sitio', ENT_QUOTES, 'UTF-8') ?>"
                  data-ubicacion="<?= htmlspecialchars($ir['ubicacion'] ?? '', ENT_QUOTES, 'UTF-8') ?>"
                  data-fecha="<?= htmlspecialchars($ir['fecha_mantenimiento'], ENT_QUOTES, 'UTF-8') ?>"
                  data-tipo-mant="<?= htmlspecialchars($ir['tipo_mantenimiento'] ?? 'Correctivo', ENT_QUOTES, 'UTF-8') ?>"
                  data-tecnico-id="<?= (int)($ir['tecnico_id'] ?? 0) ?>"
                  data-tecnico-nombre="<?= htmlspecialchars($ir['tecnico_nombre'] ?? '', ENT_QUOTES, 'UTF-8') ?>"
                  data-bs-toggle="modal" data-bs-target="#modalFormatosMantenimiento"
                  title="Formatos de servicio (Checklist, Calidad, Herramientas)">
                  <i class="bi bi-file-earmark-check"></i>
                </button>

                <button type="button" class="btn btn-outline-secondary btn-sm verDetalleMantenimientoBtn"
                  data-detalle='<?= htmlspecialchars(json_encode($detalleInfraMantenimiento, JSON_HEX_APOS | JSON_HEX_QUOT | JSON_HEX_AMP | JSON_HEX_TAG), ENT_QUOTES, "UTF-8") ?>'
                  data-bs-toggle="modal" data-bs-target="#modalDetalleMantenimiento"
                  title="Ver detalle">
                  <i class="bi bi-eye"></i>
                </button>
                <form action="../controllers/revisiones_controller.php" method="POST" class="d-inline eliminar-form">
                  <input type="hidden" name="action" value="delete_infra">
                  <input type="hidden" name="id" value="<?= htmlspecialchars($ir['id']) ?>">
                  <button type="submit" class="btn btn-outline-danger btn-sm" title="Eliminar mantenimiento">
                    <i class="bi bi-trash"></i>
                  </button>
                </form>
                <a href="../views/pdf/revision_pdf.php?tipo=infra&id=<?= $ir['id'] ?>" 
                  target="_blank"
                  class="btn btn-danger btn-sm"
                  title="Ver / Imprimir PDF">
                  <i class="bi bi-file-earmark-pdf"></i>
                </a>
              </td>
            </tr>
          <?php endforeach; ?>
        <?php endif; ?>
      </tbody>
    </table>
    </div>
    <div id="pagination-infraRevisiones" class="d-flex justify-content-center mt-3"></div>
  </div>

  <div class="modal fade" id="modalRevision" tabindex="-1" aria-hidden="true">
    <div class="modal-dialog modal-xl modal-dialog-centered">
      <div class="modal-content shadow-lg border-0">

        <form action="../controllers/revisiones_controller.php" method="POST" enctype="multipart/form-data" class="d-flex flex-column m-0 flex-fill" style="min-height: 0;">
          <input type="hidden" name="action" value="add">

          <div class="modal-header bg-success text-white py-2 px-3">
            <h5 class="modal-title fs-5 fw-bold d-flex align-items-center gap-2">
              <i class="bi bi-tools"></i> Registrar Mantenimiento
            </h5>
            <button type="button" class="btn-close btn-close-white" data-bs-dismiss="modal"></button>
          </div>

          <!-- Body: dos columnas (form / materiales) -->
          <div class="modal-body p-0">
            <div class="modal-revision-grid">
              <!-- Left: formulario optimizado y compacto -->
              <div class="modal-revision-form-panel p-2 p-md-3">
                <div class="form-check form-switch mb-2 bg-white px-3 py-1.5 rounded border shadow-xs d-flex align-items-center justify-content-between">
                  <label class="form-check-label fw-bold text-dark small mb-0 cursor-pointer" for="checkMantenimientoInfra">
                    <i class="bi bi-broadcast-pin text-primary me-1"></i> Mantenimiento de Puente / Sitio
                  </label>
                  <input class="form-check-input m-0 cursor-pointer" type="checkbox" id="checkMantenimientoInfra" name="es_infraestructura_revision" value="1">
                </div>

                <div class="row g-2 mb-2">
                  <!-- UBICACIÓN -->
                  <div class="col-12 col-md-6">
                    <label class="form-label fw-bold small text-secondary mb-1">Ubicación</label>
                    <select id="ubicacionSelect" class="form-select form-select-sm" required>
                      <option value="">Seleccione ubicación...</option>
                      <?php
                        $ubic = $pdo->query("SELECT * FROM ubicaciones ORDER BY nombre")->fetchAll();
                        foreach ($ubic as $u)
                        echo "<option value='{$u['id']}'>" . htmlspecialchars($u['nombre']) . "</option>";
                      ?>
                    </select>
                  </div>
                  <!-- ARCO / SITIO -->
                  <div class="col-12 col-md-6">
                    <label class="form-label fw-bold small text-secondary mb-1" id="objetivoMantenimientoLabel">Arco</label>
                    <select name="arco_id" id="arcoSelect" class="form-select form-select-sm" required>
                      <option value="">Seleccione ubicación...</option>
                    </select>
                  </div>
                </div>

                <div class="row g-2 mb-2">
                  <!-- FECHA -->
                  <div class="col-12 col-md-6">
                    <label class="form-label fw-bold small text-secondary mb-1">Fecha mantenimiento</label>
                    <input type="datetime-local" name="fecha_mantenimiento" class="form-control form-control-sm" required>
                  </div>

                  <!-- TIPO -->
                  <div class="col-12 col-md-6">
                    <label class="form-label fw-bold small text-secondary mb-1">Tipo de mantenimiento</label>
                    <select name="tipo_mantenimiento" class="form-select form-select-sm" required>
                      <option value="Preventivo">Preventivo</option>
                      <option value="Correctivo" selected>Correctivo</option>
                    </select>
                  </div>
                </div>

                <!-- TÉCNICO -->
                <div class="mb-2">
                  <label class="form-label fw-bold small text-secondary mb-1" for="tecnico_id">Técnico responsable</label>
                  <select name="tecnico_id" id="tecnico_id" class="form-select form-select-sm" required>
                    <option value="">Seleccione técnico...</option>
                    <?php foreach ($tecnicosActivos as $tecnico): ?>
                      <option value="<?= htmlspecialchars((string)$tecnico['id'], ENT_QUOTES, 'UTF-8') ?>">
                        <?= htmlspecialchars($tecnico['nombre']) ?>
                      </option>
                    <?php endforeach; ?>
                  </select>
                </div>

                <!-- OBSERVACIONES -->
                <div class="mb-2">
                  <label class="form-label fw-bold small text-secondary mb-1">Observaciones</label>
                  <textarea name="observaciones" class="form-control form-control-sm" rows="2" placeholder="Detalles de la revisión o trabajo realizado..."></textarea>
                </div>

                <!-- EVIDENCIAS -->
                <div class="mb-1">
                  <div class="d-flex justify-content-between align-items-center mb-1">
                    <label class="form-label fw-bold small text-secondary mb-0">Evidencias (imágenes o PDF)</label>
                    <small class="text-muted" style="font-size: 0.72rem;">Opcional</small>
                  </div>
                  <input type="file" name="evidencias[]" id="evidenciasInput"
                    accept="image/*,application/pdf"
                    multiple class="form-control form-control-sm">

                  <div id="previewEvidencias" class="preview-evidencias mt-1"></div>
                </div>
              </div>

              <!-- Right: materiales -->
              <div class="modal-revision-materials-panel p-3">
                <div class="d-flex justify-content-between align-items-center gap-2 mb-2 pb-2 border-bottom">
                  <div>
                    <h6 class="fw-bold text-success mb-0" id="tituloMaterialesMantenimiento">
                      <i class="bi bi-box-seam me-1"></i> Componentes del Arco
                    </h6>
                    <small class="text-muted" style="font-size: 0.78rem;">Cambiados / Agregados / Retirados</small>
                  </div>
                  <button type="button" class="btn btn-sm btn-success d-none shadow-sm fw-semibold" id="btnAgregarMaterialMantenimiento">
                    <i class="bi bi-plus-lg"></i> Agregar material
                  </button>
                </div>
                <div id="materialesContainer" class="materiales-maintenance-scroll">
                  <div class="text-center text-muted py-5">
                    <i class="bi bi-arrow-left-circle fs-3 d-block mb-2 text-secondary"></i>
                    Seleccione una ubicación y un objetivo para mostrar sus componentes...
                  </div>
                </div>
              </div>

              <div id="materialesHidden"></div>
            </div>
          </div>

          <div class="modal-footer bg-white border-top py-2 px-3 justify-content-between">
            <span class="text-muted small d-none d-md-inline">
              <i class="bi bi-info-circle me-1"></i> Complete los campos y guarde los cambios.
            </span>
            <div class="d-flex gap-2 ms-auto">
              <button type="button" class="btn btn-secondary px-3" data-bs-dismiss="modal">
                Cancelar
              </button>
              <button type="submit" class="btn btn-success px-4 fw-bold shadow-sm">
                <i class="bi bi-check-lg me-1"></i> Guardar Registro
              </button>
            </div>
          </div>
        </form>
      </div>
    </div>
  </div>

  <div class="modal fade" id="modalRevisionInfra" tabindex="-1">
    <div class="modal-dialog modal-xl modal-dialog-centered">
      <div class="modal-content">
        <form action="../controllers/revisiones_controller.php" method="POST" enctype="multipart/form-data">
          <input type="hidden" name="action" value="add_infra">

          <div class="modal-header bg-primary text-white">
            <h5 class="modal-title"><i class="bi bi-broadcast-pin me-2"></i> Registrar Mantenimiento de Puente/Sitio</h5>
            <button type="button" class="btn-close btn-close-white" data-bs-dismiss="modal"></button>
          </div>

          <div class="modal-body p-0">
            <div class="d-flex flex-row">
              <div class="col col-xl-6 border-top bg-light p-3 flex-fill">
                <div class="row">
                  <div class="col mb-3">
                    <label class="form-label fw-semibold">Puente/Sitio</label>
                    <select name="infraestructura_id" class="form-select" required>
                      <option value="">Seleccione...</option>
                      <?php foreach ($pdo->query("SELECT n.id, n.tipo, n.nombre, u.nombre AS ubicacion FROM infraestructura_nodos n LEFT JOIN ubicaciones u ON u.id = n.ubicacion_id ORDER BY n.tipo, n.nombre") as $infra): ?>
                        <option value="<?= htmlspecialchars($infra['id']) ?>">
                          <?= htmlspecialchars($infra['tipo'] . ' - ' . $infra['nombre'] . (!empty($infra['ubicacion']) ? ' (' . $infra['ubicacion'] . ')' : '')) ?>
                        </option>
                      <?php endforeach; ?>
                    </select>
                  </div>
                  <div class="col mb-3">
                    <label class="form-label fw-semibold">Fecha mantenimiento</label>
                    <input type="datetime-local" name="fecha_mantenimiento" class="form-control" required>
                  </div>
                </div>

                <div class="col mb-3">
                  <label class="form-label fw-semibold">Tipo de mantenimiento</label>
                  <select name="tipo_mantenimiento" class="form-select" required>
                    <option value="Preventivo">Preventivo</option>
                    <option value="Correctivo" selected>Correctivo</option>
                  </select>
                </div>

                <div class="col mb-3">
                  <label class="form-label fw-semibold">TÃ©cnico responsable</label>
                  <select name="tecnico_id" class="form-select" required>
                    <option value="">Seleccione tecnico...</option>
                    <?php foreach ($tecnicosActivos as $tecnico): ?>
                      <option value="<?= htmlspecialchars((string)$tecnico['id'], ENT_QUOTES, 'UTF-8') ?>">
                        <?= htmlspecialchars($tecnico['nombre']) ?>
                      </option>
                    <?php endforeach; ?>
                  </select>
                </div>

                <div class="col mb-3">
                  <label class="form-label fw-semibold">Observaciones</label>
                  <textarea name="observaciones" class="form-control" rows="3"></textarea>
                </div>

                <div class="col mb-3">
                  <label class="form-label fw-semibold">Evidencias (imágenes o PDF)</label>
                  <input type="file" name="evidencias[]" accept="image/*,application/pdf" multiple class="form-control">
                  <small class="form-text text-muted">Puedes subir varias evidencias (opcional).</small>
                </div>
              </div>

              <div class="col col-xl-6 border-top bg-light p-3 flex-fill">
                <div class="d-flex justify-content-between align-items-center mb-3">
                  <h6 class="fw-semibold mb-0">Material(es) cambiados / agregados</h6>
                  <button type="button" class="btn btn-sm btn-outline-primary" id="btnAddInfraRevisionMaterial">
                    <i class="bi bi-plus-lg"></i> Material
                  </button>
                </div>

                <div id="infraRevisionMaterialRows" class="infra-revision-material-rows">
                  <div class="infra-revision-material-row">
                    <select name="infra_material_id[]" class="form-select infra-revision-material-select" required>
                      <option value="">Seleccione material...</option>
                      <?php foreach ($pdo->query('SELECT id, nombre, medida FROM materiales ORDER BY nombre') as $m): ?>
                        <option value="<?= htmlspecialchars($m['id']) ?>" data-medida="<?= htmlspecialchars($m['medida']) ?>">
                          <?= htmlspecialchars($m['nombre']) ?>
                        </option>
                      <?php endforeach; ?>
                    </select>
                    <input type="number" name="infra_cantidad[]" class="form-control infra-revision-cantidad" min="0.1" step="0.1" value="1">
                    <input type="text" name="infra_serie[]" class="form-control" placeholder="Serie">
                    <button type="button" class="btn btn-outline-danger infra-revision-remove-material">
                      <i class="bi bi-trash"></i>
                    </button>
                  </div>
                </div>
              </div>
            </div>
          </div>

          <div class="modal-footer">
            <button type="button" class="btn btn-outline-secondary" data-bs-dismiss="modal">Cancelar</button>
            <button type="submit" class="btn btn-primary">Guardar Registro</button>
          </div>
        </form>
      </div>
    </div>
  </div>

<div class="modal fade" id="modalSerie" tabindex="-1" aria-hidden="true" data-bs-backdrop="static">
  <div class="modal-dialog modal-xl modal-dialog-centered modal-dialog-scrollable">
    <div class="modal-content shadow-lg border-0">

      <div class="modal-header bg-success text-white py-2 px-3">
        <h6 class="modal-title fw-bold fs-6 mb-0 d-flex align-items-center gap-2">
          <i class="bi bi-pencil-square"></i> <span>Editar material</span>
        </h6>
        <button type="button" class="btn-close btn-close-white" data-bs-dismiss="modal"></button>
      </div>

      <div class="modal-body p-0 bg-light">
        <input type="hidden" id="modalSelectMaterial">
        <input type="hidden" id="modalMaterialId">

        <div class="modal-material-layout">
          <!-- PANEL IZQUIERDO: LISTA / GRID DE MATERIALES -->
          <div class="modal-material-list-panel p-3">
            <div class="d-flex justify-content-between align-items-center mb-2">
              <label class="form-label fw-bold small text-secondary mb-0">Catálogo de Materiales</label>
              <small class="text-muted" style="font-size: 0.75rem;">Haz clic para seleccionar</small>
            </div>
            <div class="input-group input-group-sm mb-2 shadow-sm">
              <span class="input-group-text bg-success text-white border-success"><i class="bi bi-search"></i></span>
              <input type="search" id="modalBuscarMaterial" class="form-control" placeholder="Buscar material por nombre...">
            </div>
            <div id="modalMaterialGrid" class="modal-material-grid">
              <div class="text-center text-muted py-4">
                <div class="spinner-border spinner-border-sm text-success me-2"></div> Cargando materiales...
              </div>
            </div>
          </div>

          <!-- PANEL DERECHO: CONFIGURACIÓN -->
          <aside class="modal-material-config-panel p-3">
            <div class="d-flex align-items-center gap-2 mb-2 pb-2 border-bottom">
              <i class="bi bi-sliders text-success fs-5"></i>
              <div>
                <h6 class="fw-bold text-dark mb-0" style="font-size: 0.92rem;">Configuración</h6>
                <small class="text-muted" style="font-size: 0.75rem;">Detalles del material seleccionado</small>
              </div>
            </div>

            <div id="modalMaterialSeleccionado" class="modal-material-selected mb-3">
              Selecciona el material que quedará instalado.
            </div>

            <div class="modal-material-fields">
              <div id="DatosSeries" class="d-none">
                <!-- SERIE -->
                <div class="config-field-group mb-2 p-2 border rounded bg-white shadow-xs">
                  <div class="d-flex justify-content-between align-items-center">
                    <label class="form-check-label small fw-semibold text-secondary mb-0 cursor-pointer" for="modalCheckSerie">
                      <i class="bi bi-upc-scan me-1 text-primary"></i> Número de Serie
                    </label>
                    <div class="form-check form-switch m-0">
                      <input class="form-check-input" type="checkbox" id="modalCheckSerie">
                    </div>
                  </div>
                  <div id="modalSerieField" class="modal-serie-input d-none mt-2">
                    <input type="text" id="modalSerieInput" class="form-control form-control-sm" placeholder="Ingrese el número de serie">
                  </div>
                </div>

                <!-- IP -->
                <div class="config-field-group mb-2 p-2 border rounded bg-white shadow-xs">
                  <div class="d-flex justify-content-between align-items-center">
                    <label class="form-check-label small fw-semibold text-secondary mb-0 cursor-pointer" for="modalCheckIp">
                      <i class="bi bi-hdd-network me-1 text-info"></i> Dirección IP
                    </label>
                    <div class="form-check form-switch m-0">
                      <input class="form-check-input" type="checkbox" id="modalCheckIp">
                    </div>
                  </div>
                  <div id="modalIpField" class="modal-serie-input d-none mt-2">
                    <div class="input-group input-group-sm">
                      <span class="input-group-text bg-light text-primary"><i class="bi bi-hdd-network"></i></span>
                      <input type="text" id="modalIpInput" class="form-control form-control-sm" placeholder="Ej. 192.168.1.50">
                    </div>
                  </div>
                </div>

                <!-- MAC -->
                <div class="config-field-group mb-2 p-2 border rounded bg-white shadow-xs">
                  <div class="d-flex justify-content-between align-items-center">
                    <label class="form-check-label small fw-semibold text-secondary mb-0 cursor-pointer" for="modalCheckMac">
                      <i class="bi bi-ethernet me-1 text-success"></i> Dirección MAC
                    </label>
                    <div class="form-check form-switch m-0">
                      <input class="form-check-input" type="checkbox" id="modalCheckMac">
                    </div>
                  </div>
                  <div id="modalMacField" class="modal-serie-input d-none mt-2">
                    <div class="input-group input-group-sm">
                      <span class="input-group-text bg-light text-success"><i class="bi bi-ethernet"></i></span>
                      <input type="text" id="modalMacInput" class="form-control form-control-sm text-uppercase" placeholder="Ej. AA:BB:CC:DD:EE:FF" maxlength="17">
                    </div>
                  </div>
                </div>
              </div>

              <!-- CANTIDAD -->
              <div class="d-none" id="DatosCantidad">
                <div class="config-field-group p-2 border rounded bg-white shadow-xs">
                  <label class="form-label small fw-semibold text-secondary mb-1">
                    <i class="bi bi-rulers me-1 text-warning"></i> Cantidad
                  </label>
                  <div class="input-group input-group-sm">
                    <input type="number" id="modalCantidadInput" class="form-control form-control-sm" min="0.1" step="0.1" value="1">
                    <span class="input-group-text text-muted" id="medida-label">pz</span>
                  </div>
                </div>
              </div>
            </div>
          </aside>
        </div>
        
      </div>

      <div class="modal-footer bg-white py-2 px-3 justify-content-between">
        <span class="text-muted small">
          <i class="bi bi-info-circle me-1"></i> Selecciona el material y ajusta sus datos.
        </span>
        <div class="d-flex gap-2">
          <button type="button" class="btn btn-sm btn-secondary px-3" data-bs-dismiss="modal">Cancelar</button>
          <button type="button" class="btn btn-sm btn-success px-4 fw-bold shadow-sm" id="btnGuardarSerie">
            <i class="bi bi-check-lg me-1"></i> Guardar
          </button>
        </div>
      </div>

    </div>
  </div>
</div>

<!-- ===================== MODAL VER MATERIALES ===================== -->
<div class="modal modalverMateriales" id="modalMateriales" tabindex="-1" aria-hidden="true">
  <div class="modal-dialog modal-lg modal-dialog-centered modal-dialog-scrollable">
    <div class="modal-content shadow-lg">

      <div class="modal-header bg-success text-white">
        <h5 class="modal-title"><i class="bi bi-box-seam"></i> Componentes del mantenimiento</h5>
        <button type="button" class="btn-close" data-bs-dismiss="modal"></button>
      </div>
      <div class="modal-body" id="contenedorMateriales" style="overflow-y: auto; max-height: 60vh;">
      </div>
      <div class="modal-footer">
        <button class="btn btn-secondary" data-bs-dismiss="modal">Cerrar</button>
      </div>
    </div>
  </div>
</div>

<!-- ===================== MODAL DETALLE MANTENIMIENTO ===================== -->
<div class="modal fade" id="modalDetalleMantenimiento" tabindex="-1" aria-hidden="true">
  <div class="modal-dialog modal-xl modal-dialog-centered modal-dialog-scrollable">
    <div class="modal-content shadow-lg">
      <div class="modal-header bg-secondary text-white">
        <h5 class="modal-title"><i class="bi bi-eye"></i> Detalle del mantenimiento</h5>
        <button type="button" class="btn-close btn-close-white" data-bs-dismiss="modal"></button>
      </div>
      <div class="modal-body" id="detalleMantenimientoContenido"></div>
      <div class="modal-footer">
        <button class="btn btn-secondary" data-bs-dismiss="modal">Cerrar</button>
      </div>
    </div>
  </div>
</div>

<!-- ===================== MODAL FORMATOS DE SERVICIO ===================== -->
<div class="modal fade" id="modalFormatosMantenimiento" tabindex="-1" aria-hidden="true">
  <div class="modal-dialog modal-xl modal-dialog-centered modal-dialog-scrollable">
    <div class="modal-content shadow-lg border-0">
      <div class="modal-header bg-success text-white py-2 px-3">
        <h5 class="modal-title fs-5 fw-bold d-flex align-items-center gap-2">
          <i class="bi bi-file-earmark-check-fill"></i> Formatos de Servicio del Mantenimiento
        </h5>
        <button type="button" class="btn-close btn-close-white" data-bs-dismiss="modal"></button>
      </div>
      <div class="modal-body p-3 p-md-4 bg-light">
        <div id="formatosModalHeader" class="formatos-modal-header mb-3">
          <div class="text-center text-muted py-3">
            <div class="spinner-border spinner-border-sm text-success me-2"></div> Cargando datos del mantenimiento...
          </div>
        </div>

        <div class="formatos-mantenimiento-grid" id="formatosMantenimientoGrid">
          <!-- Will render 3 cards: Checklist, Calidad, Herramientas -->
        </div>
      </div>
      <div class="modal-footer bg-white py-2 px-3 justify-content-between">
        <span class="text-muted small">
          <i class="bi bi-info-circle text-success me-1"></i> Información sincronizada automáticamente entre el mantenimiento y sus formatos.
        </span>
        <button type="button" class="btn btn-secondary px-4" data-bs-dismiss="modal">Cerrar</button>
      </div>
    </div>
  </div>
</div>

<!-- Modal para evidencias -->
<div class="modal fade" id="modalEvidencias" tabindex="-1" aria-hidden="true">
  <div class="modal-dialog modal-lg modal-dialog-centered modal-dialog-scrollable">
    <div class="modal-content">
      <div class="modal-header bg-primary text-white">
        <h5 class="modal-title tituloEvidencias"><i class="bi bi-camera"></i> Evidencias</h5>
        <button type="button" class="btn-close" data-bs-dismiss="modal"></button>
      </div>
      <div class="modal-body" 
        id="evidenciasContainer"
        style="
          max-height: 70vh;
          overflow-y: auto;
          display: grid;
          grid-template-columns: repeat(auto-fill, minmax(180px, 1fr));
          gap: 12px;
        ">
      </div>
      <div class="modal-footer">
        <button class="btn btn-secondary" data-bs-dismiss="modal">Cerrar</button>
      </div>
    </div>
  </div>
</div>

<!-- Modal visor de imagen -->
<div class="modal fade" id="modalImagen" tabindex="-1" aria-hidden="true">
<div class="modal-dialog modal-xl modal-dialog-centered">

    <div class="modal-content bg-dark border-0 position-relative">

      <div class="modal-body text-center position-relative" style="overflow-y: auto; max-height: 80vh;">
        <button type="button" class="btn-close btn-close-white ms-auto position-absolute top-0 end-0 m-2" data-bs-dismiss="modal"></button>

        <!-- Flecha izquierda -->
        <button id="btnPrevImg"
                class="btn btn-dark position-absolute top-50 start-0 translate-middle-y ms-3 z-3">
          <i class="bi bi-chevron-left fs-3"></i>
        </button>

        <!-- Imagen -->
        <img id="imagenAmpliada"
             src=""
             class="img-fluid"
             style="max-height: 70vh; object-fit: contain;">

        <!-- Flecha derecha -->
        <button id="btnNextImg"
                class="btn btn-dark position-absolute top-50 end-0 translate-middle-y me-3 z-3">
          <i class="bi bi-chevron-right fs-3"></i>
        </button>

      </div>
    </div>
  </div>
</div>

<!-- Modal visor PDF -->
<div class="modal fade" id="modalPdf" tabindex="-1" aria-hidden="true">
  <div class="modal-dialog modal-xl modal-dialog-centered">
    <div class="modal-content bg-dark border-0">

      <div class="modal-body position-relative p-2">
        <button type="button"
                class="btn-close btn-close-white position-absolute top-0 end-0 m-2 z-3"
                data-bs-dismiss="modal">
        </button>

        <iframe id="pdfAmpliado"
                src=""
                style="width:100%; height:85vh; border:none; border-radius:10px;">
        </iframe>
      </div>

    </div>
  </div>
</div>


<script src="../js/revisiones2.js?v=<?= $revisionesJsVersion ?>"></script>

<?php include('../views/footer.php'); ?>
