import datetime
import threading
import time
import tkinter as tk
from tkinter import messagebox, scrolledtext, ttk
from urllib.parse import urlparse

import psycopg2
from psycopg2.extras import execute_values

try:
    import mysql.connector
except ImportError:
    mysql = None

URL_LOCAL_DEFAULT = "postgresql://postgres:0806@localhost:5432/repuve_mantenimiento"
URL_REMOTA_DEFAULT = "postgresql://repuvebd_user:TD9eVqoRqNPfOKjZQctCp0kzBZwJCKm7@dpg-da4ugt3m8hqs73arpaq0-a.oregon-postgres.render.com/repuvebd?sslmode=require"

PLANTILLAS_SQL = {
    "Ver datos de 'arcos' (50 filas)": 'SELECT * FROM "arcos" ORDER BY id DESC LIMIT 50;',
    "Ver datos de 'tecnicos'": 'SELECT * FROM "tecnicos" ORDER BY id DESC;',
    "Ver todas las tablas de la BD": """SELECT table_name, 
       (SELECT COUNT(*) FROM information_schema.columns WHERE table_name = t.table_name) as total_columnas
FROM information_schema.tables t
WHERE table_schema = 'public' AND table_type = 'BASE TABLE'
ORDER BY table_name;""",
    "Ver estructura detallada de 'arcos'": """SELECT column_name, data_type, is_nullable, column_default, is_identity, identity_generation
FROM information_schema.columns
WHERE table_schema = 'public' AND table_name = 'arcos'
ORDER BY ordinal_position;""",
    "Ver secuencias e identidades existentes": """SELECT table_name, column_name, is_identity, column_default
FROM information_schema.columns
WHERE table_schema = 'public' AND (is_identity = 'YES' OR column_default LIKE '%nextval%')
ORDER BY table_name;""",
    "Reparar ID de 'arcos' (Configurar IDENTITY)": """-- Convierte la columna id en IDENTITY y sincroniza el contador al valor máximo actual
ALTER TABLE "arcos" ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY;
SELECT setval(pg_get_serial_sequence('"arcos"', 'id'), COALESCE((SELECT MAX(id) FROM "arcos"), 1));""",
    "Insertar nuevo Arco de prueba (RETURNING id)": """INSERT INTO "arcos" (nombre, ubicacion_id, fecha_instalacion, lat, lng, estado)
VALUES ('Arco de Prueba Sistema', 1, CURRENT_TIMESTAMP, '16.8531', '-99.8237', 'Activo')
RETURNING id, nombre, estado;""",
    "Eliminar Arco de prueba": """DELETE FROM "arcos" WHERE nombre = 'Arco de Prueba Sistema';""",
}


class UniversalMigratorApp:
    def __init__(self, root):
        self.root = root
        self.root.title("DataBridge Pro - Migrador Universal & Consola BD")
        self.root.geometry("1220x790")
        self.root.minsize(1040, 650)

        self.dark_mode = True
        self.datos_tablas = {}
        self.target_sql = tk.StringVar(value="destino")

        self._configurar_estilos()
        self.crear_interfaz()
        self.aplicar_tema()

    def _configurar_estilos(self):
        self.style = ttk.Style(self.root)
        self.style.theme_use("clam")

    def _definir_paletas(self):
        if self.dark_mode:
            return {
                "bg_app": "#121214",
                "bg_card": "#1e1e24",
                "bg_input": "#27272a",
                "fg_text": "#f4f4f5",
                "fg_muted": "#a1a1aa",
                "accent_blue": "#0284c7",
                "accent_green": "#10b981",
                "accent_orange": "#f59e0b",
                "accent_red": "#ef4444",
                "tree_heading": "#18181b",
                "console_bg": "#09090b",
                "console_fg": "#22c55e",
                "border": "#3f3f46"
            }
        else:
            return {
                "bg_app": "#f4f4f5",
                "bg_card": "#ffffff",
                "bg_input": "#e4e4e7",
                "fg_text": "#18181b",
                "fg_muted": "#71717a",
                "accent_blue": "#0284c7",
                "accent_green": "#16a34a",
                "accent_orange": "#d97706",
                "accent_red": "#dc2626",
                "tree_heading": "#e4e4e7",
                "console_bg": "#18181b",
                "console_fg": "#4ade80",
                "border": "#d4d4d8"
            }

    def aplicar_tema(self):
        p = self._definir_paletas()
        self.root.configure(bg=p["bg_app"])

        self.style.configure(".", background=p["bg_app"], foreground=p["fg_text"], font=("Segoe UI", 9))
        self.style.configure("TNotebook", background=p["bg_app"], borderwidth=0)
        self.style.configure("TNotebook.Tab", background=p["bg_card"], foreground=p["fg_muted"], padding=(12, 5), font=("Segoe UI", 9, "bold"))
        self.style.map("TNotebook.Tab", background=[("selected", p["bg_input"])], foreground=[("selected", p["accent_blue"])])

        self.style.configure("Card.TFrame", background=p["bg_card"])
        self.style.configure("TLabelframe", background=p["bg_card"], foreground=p["fg_muted"], bordercolor=p["border"])
        self.style.configure("TLabelframe.Label", background=p["bg_card"], foreground=p["accent_blue"], font=("Segoe UI", 9, "bold"))
        self.style.configure("TLabel", background=p["bg_card"], foreground=p["fg_text"])
        self.style.configure("TRadiobutton", background=p["bg_card"], foreground=p["fg_text"], font=("Segoe UI", 9, "bold"))

        self.style.configure("TEntry", fieldbackground=p["bg_input"], foreground=p["fg_text"], insertcolor=p["fg_text"], borderwidth=0)
        self.style.configure("TCombobox", fieldbackground=p["bg_input"], background=p["bg_input"], foreground=p["fg_text"], borderwidth=0)

        self.style.configure("Primary.TButton", background=p["accent_blue"], foreground="#ffffff", font=("Segoe UI", 9, "bold"), borderwidth=0)
        self.style.map("Primary.TButton", background=[("active", "#0369a1"), ("disabled", "#71717a")])

        self.style.configure("Success.TButton", background=p["accent_green"], foreground="#ffffff", font=("Segoe UI", 9, "bold"), borderwidth=0)
        self.style.map("Success.TButton", background=[("active", "#059669"), ("disabled", "#71717a")])

        self.style.configure("Warning.TButton", background=p["accent_orange"], foreground="#ffffff", font=("Segoe UI", 9, "bold"), borderwidth=0)
        self.style.map("Warning.TButton", background=[("active", "#b45309"), ("disabled", "#71717a")])

        self.style.configure("Ghost.TButton", background=p["bg_input"], foreground=p["fg_text"], font=("Segoe UI", 8), borderwidth=0)
        self.style.map("Ghost.TButton", background=[("active", p["border"])])

        self.style.configure("Treeview", background=p["bg_input"], foreground=p["fg_text"], fieldbackground=p["bg_input"], rowheight=26, borderwidth=0)
        self.style.map("Treeview", background=[("selected", p["accent_blue"])], foreground=[("selected", "#ffffff")])
        self.style.configure("Treeview.Heading", background=p["tree_heading"], foreground=p["accent_blue"], font=("Segoe UI", 9, "bold"), borderwidth=0)

        # Consolas y editores
        self.log_text.configure(background=p["console_bg"], foreground=p["console_fg"])
        self.sql_editor.configure(background=p["bg_input"], foreground=p["fg_text"], insertbackground=p["fg_text"])
        self.sql_log.configure(background=p["console_bg"], foreground=p["console_fg"])
        self.btn_tema.config(text="☀️ Modo Claro" if self.dark_mode else "🌙 Modo Oscuro")

    def toggle_tema(self):
        self.dark_mode = not self.dark_mode
        self.aplicar_tema()

    def crear_interfaz(self):
        # Barra Superior de Control (Tema y Título)
        frame_header = ttk.Frame(self.root)
        frame_header.pack(fill="x", padx=10, pady=(6, 2))

        ttk.Label(frame_header, text="⚡ DataBridge Pro", font=("Segoe UI", 12, "bold"), foreground="#0284c7").pack(side="left")
        ttk.Label(frame_header, text="  |  Migrador & Gestor de Bases de Datos", font=("Segoe UI", 10), foreground="#71717a").pack(side="left")

        self.btn_tema = ttk.Button(frame_header, text="☀️ Modo Claro", style="Ghost.TButton", command=self.toggle_tema)
        self.btn_tema.pack(side="right")

        # 1. Contenedor de Conexiones (Común para Migrador y Consola SQL)
        frame_top = ttk.Frame(self.root, padding=(10, 2, 10, 4))
        frame_top.pack(fill="x")

        self.notebook_conn = ttk.Notebook(frame_top)
        self.notebook_conn.pack(fill="x", expand=True)

        # Pestaña 1: URI
        tab_url = ttk.Frame(self.notebook_conn, style="Card.TFrame", padding=8)
        self.notebook_conn.add(tab_url, text="  Conexión Rápida (URL / URI)  ")

        ttk.Label(tab_url, text="BD Origen:").grid(row=0, column=0, sticky="w", pady=2)
        self.entry_url_origen = ttk.Entry(tab_url)
        self.entry_url_origen.insert(0, URL_LOCAL_DEFAULT)
        self.entry_url_origen.grid(row=0, column=1, padx=(6, 2), pady=2, sticky="ew")

        ttk.Label(tab_url, text="BD Destino (PG):").grid(row=1, column=0, sticky="w", pady=2)
        self.entry_url_destino = ttk.Entry(tab_url)
        self.entry_url_destino.insert(0, URL_REMOTA_DEFAULT)
        self.entry_url_destino.grid(row=1, column=1, padx=(6, 2), pady=2, sticky="ew")

        btn_cargar_url = ttk.Button(tab_url, text="⚡ Cargar Tablas", style="Primary.TButton", command=self.cargar_tablas)
        btn_cargar_url.grid(row=0, column=2, rowspan=2, padx=(6, 0), pady=2, sticky="nsew")
        tab_url.columnconfigure(1, weight=1)

        # Pestaña 2: Campos Separados
        tab_campos = ttk.Frame(self.notebook_conn, style="Card.TFrame", padding=8)
        self.notebook_conn.add(tab_campos, text="  Conexión por Campos Separados  ")

        # Fila Origen
        ttk.Label(tab_campos, text="Origen:", font=("Segoe UI", 9, "bold")).grid(row=0, column=0, sticky="w")
        self.combo_motor = ttk.Combobox(tab_campos, values=["postgresql", "mysql"], width=10, state="readonly")
        self.combo_motor.set("postgresql")
        self.combo_motor.grid(row=0, column=1, padx=3, pady=2)

        self.f_host_o = self._crear_input(tab_campos, "Host:", "localhost", 0, 2, 12)
        self.f_port_o = self._crear_input(tab_campos, "Puerto:", "5432", 0, 4, 5)
        self.f_user_o = self._crear_input(tab_campos, "User:", "postgres", 0, 6, 9)
        self.f_pass_o, _ = self._crear_input_password(tab_campos, "Pass:", "0806", 0, 8, 9)
        self.f_db_o = self._crear_input(tab_campos, "BD:", "repuve_mantenimiento", 0, 11, 14)

        # Fila Destino
        ttk.Label(tab_campos, text="Destino:", font=("Segoe UI", 9, "bold")).grid(row=1, column=0, sticky="w", pady=3)
        ttk.Label(tab_campos, text="postgresql", foreground="#0284c7").grid(row=1, column=1, padx=3)

        self.f_host_d = self._crear_input(tab_campos, "Host:", "dpg-da4ugt3m8hqs73arpaq0-a.oregon-postgres.render.com", 1, 2, 12)
        self.f_port_d = self._crear_input(tab_campos, "Puerto:", "5432", 1, 4, 5)
        self.f_user_d = self._crear_input(tab_campos, "User:", "repuvebd_user", 1, 6, 9)
        self.f_pass_d, _ = self._crear_input_password(tab_campos, "Pass:", "TD9eVqoRqNPfOKjZQctCp0kzBZwJCKm7", 1, 8, 9)
        self.f_db_d = self._crear_input(tab_campos, "BD:", "repuvebd", 1, 11, 14)

        btn_cargar_campos = ttk.Button(tab_campos, text="⚡ Cargar Tablas", style="Primary.TButton", command=self.cargar_tablas)
        btn_cargar_campos.grid(row=0, column=13, rowspan=2, padx=(8, 0), pady=2, sticky="nsew")

        # 2. PESTAÑAS PRINCIPALES: [Migrador] y [Consola SQL]
        self.main_notebook = ttk.Notebook(self.root)
        self.main_notebook.pack(fill="both", expand=True, padx=10, pady=(4, 8))

        # --- TAB 1: MIGRADOR ---
        tab_migrador = ttk.Frame(self.main_notebook)
        self.main_notebook.add(tab_migrador, text="  📦 Migrador de Base de Datos  ")
        self._construir_pestana_migrador(tab_migrador)

        # --- TAB 2: CONSOLA SQL & MODIFICADOR ---
        tab_sql = ttk.Frame(self.main_notebook)
        self.main_notebook.add(tab_sql, text="  ⚡ Consola SQL & Modificación de Tablas  ")
        self._construir_pestana_sql(tab_sql)

    def _construir_pestana_migrador(self, parent):
        paned = ttk.PanedWindow(parent, orient=tk.HORIZONTAL)
        paned.pack(fill="both", expand=True, padx=4, pady=4)

        # Panel Izquierdo: Tablas
        frame_izq = ttk.Frame(paned, style="Card.TFrame")
        paned.add(frame_izq, weight=3)

        frame_tablas = ttk.LabelFrame(frame_izq, text=" Tablas Detectadas ", padding=8)
        frame_tablas.pack(fill="both", expand=True)

        toolbar = ttk.Frame(frame_tablas, style="Card.TFrame")
        toolbar.pack(fill="x", pady=(0, 6))

        ttk.Label(toolbar, text="🔍 Buscar:").pack(side="left", padx=(0, 3))
        self.var_filtro = tk.StringVar()
        self.var_filtro.trace_add("write", lambda *args: self.actualizar_vista_tabla())
        ttk.Entry(toolbar, textvariable=self.var_filtro, width=14).pack(side="left", padx=(0, 8))

        self.btn_select_all = ttk.Button(toolbar, text="✔ Todas", style="Ghost.TButton", command=self.seleccionar_todas, state="disabled")
        self.btn_select_all.pack(side="left", padx=2)

        self.btn_deselect_all = ttk.Button(toolbar, text="✖ Ninguna", style="Ghost.TButton", command=self.deseleccionar_todas, state="disabled")
        self.btn_deselect_all.pack(side="left", padx=2)

        self.lbl_contador = ttk.Label(toolbar, text="0 sel.", font=("Segoe UI", 9, "bold"), foreground="#0284c7")
        self.lbl_contador.pack(side="right", padx=3)

        tree_box = ttk.Frame(frame_tablas, style="Card.TFrame")
        tree_box.pack(fill="both", expand=True)

        self.tree = ttk.Treeview(tree_box, columns=("sel", "tabla", "filas", "estado"), show="headings", selectmode="browse")
        self.tree.heading("sel", text="Sel", anchor="center")
        self.tree.heading("tabla", text="Tabla", anchor="w")
        self.tree.heading("filas", text="Registros", anchor="e")
        self.tree.heading("estado", text="Estado", anchor="w")

        self.tree.column("sel", width=42, anchor="center")
        self.tree.column("tabla", width=190, anchor="w")
        self.tree.column("filas", width=85, anchor="e")
        self.tree.column("estado", width=120, anchor="w")

        scroll_tree = ttk.Scrollbar(tree_box, orient="vertical", command=self.tree.yview)
        self.tree.configure(yscrollcommand=scroll_tree.set)
        self.tree.pack(side="left", fill="both", expand=True)
        scroll_tree.pack(side="right", fill="y")

        self.tree.bind("<Button-1>", self._on_tree_click)
        self.tree.bind("<space>", self._on_tree_space)

        self.btn_migrar = ttk.Button(frame_izq, text="🚀 Iniciar Migración a PostgreSQL", style="Success.TButton", command=self.iniciar_migracion_thread, state="disabled")
        self.btn_migrar.pack(fill="x", pady=(6, 0), ipady=5)

        # Panel Derecho: Terminal
        frame_der = ttk.Frame(paned, style="Card.TFrame")
        paned.add(frame_der, weight=2)

        frame_consola = ttk.LabelFrame(frame_der, text=" Terminal de Operaciones ", padding=8)
        frame_consola.pack(fill="both", expand=True)

        self.log_text = scrolledtext.ScrolledText(
            frame_consola,
            state="disabled",
            wrap="word",
            font=("Consolas", 9),
            borderwidth=0,
            highlightthickness=0,
        )
        self.log_text.pack(fill="both", expand=True)

    def _construir_pestana_sql(self, parent):
        frame_sql_main = ttk.Frame(parent, padding=6)
        frame_sql_main.pack(fill="both", expand=True)

        # 1. Barra superior de control y destino
        bar_top = ttk.LabelFrame(frame_sql_main, text=" Destino & Herramientas de Reparación Rápida ", padding=(8, 4))
        bar_top.pack(fill="x", pady=(0, 6))

        ttk.Label(bar_top, text="Ejecutar en:", font=("Segoe UI", 9, "bold")).pack(side="left", padx=(0, 6))
        r1 = ttk.Radiobutton(bar_top, text="Destino (Render - Remota)", value="destino", variable=self.target_sql)
        r1.pack(side="left", padx=4)
        r2 = ttk.Radiobutton(bar_top, text="Origen (Local)", value="origen", variable=self.target_sql)
        r2.pack(side="left", padx=4)

        btn_test_conn = ttk.Button(bar_top, text="🔌 Probar Conexión", style="Ghost.TButton", command=self.probar_conexion_sql)
        btn_test_conn.pack(side="left", padx=8)

        # Herramientas de reparación directa
        btn_fix_render = ttk.Button(
            bar_top,
            text="🔧 Reparar Auto-Increment (IDs) en Render",
            style="Warning.TButton",
            command=self.reparar_auto_increment_render_thread
        )
        btn_fix_render.pack(side="right", padx=4)

        # 2. Barra de plantillas y selección de tablas
        bar_plantillas = ttk.Frame(frame_sql_main, padding=(0, 2, 0, 6))
        bar_plantillas.pack(fill="x")

        ttk.Label(bar_plantillas, text="Plantillas Rápidas:").pack(side="left", padx=(0, 4))
        self.combo_plantillas = ttk.Combobox(bar_plantillas, values=list(PLANTILLAS_SQL.keys()), width=42, state="readonly")
        if PLANTILLAS_SQL:
            self.combo_plantillas.current(0)
        self.combo_plantillas.pack(side="left", padx=4)

        btn_cargar_plantilla = ttk.Button(bar_plantillas, text="📋 Cargar Plantilla", style="Ghost.TButton", command=self._cargar_plantilla_sql)
        btn_cargar_plantilla.pack(side="left", padx=4)

        ttk.Label(bar_plantillas, text="|   Acciones Rápidas:").pack(side="left", padx=(10, 4))
        btn_ver_arcos = ttk.Button(bar_plantillas, text="🔍 SELECT 'arcos'", style="Ghost.TButton", command=lambda: self._set_sql_and_run('SELECT * FROM "arcos" ORDER BY id DESC LIMIT 50;'))
        btn_ver_arcos.pack(side="left", padx=2)

        btn_ver_cols = ttk.Button(bar_plantillas, text="📋 Columnas 'arcos'", style="Ghost.TButton", command=lambda: self._set_sql_and_run(PLANTILLAS_SQL["Ver estructura detallada de 'arcos'"]))
        btn_ver_cols.pack(side="left", padx=2)

        # 3. Editor SQL
        frame_editor_box = ttk.LabelFrame(frame_sql_main, text=" Editor SQL (Escribe o modifica consultas SQL) ", padding=6)
        frame_editor_box.pack(fill="x", pady=(0, 6))

        editor_toolbar = ttk.Frame(frame_editor_box)
        editor_toolbar.pack(fill="x", pady=(0, 4))

        btn_run = ttk.Button(editor_toolbar, text="▶ Ejecutar Consulta (F5 / Ctrl+Enter)", style="Primary.TButton", command=self.ejecutar_consulta_sql_thread)
        btn_run.pack(side="left", padx=(0, 6))

        btn_clear = ttk.Button(editor_toolbar, text="🧹 Limpiar Editor", style="Ghost.TButton", command=self._limpiar_editor_sql)
        btn_clear.pack(side="left", padx=4)

        self.lbl_sql_status = ttk.Label(editor_toolbar, text="Listo para ejecutar consultas.", foreground="#71717a")
        self.lbl_sql_status.pack(side="right", padx=6)

        self.sql_editor = scrolledtext.ScrolledText(
            frame_editor_box,
            height=7,
            wrap="none",
            font=("Consolas", 10),
            borderwidth=0,
            highlightthickness=0,
            undo=True
        )
        self.sql_editor.pack(fill="both", expand=True)
        self.sql_editor.insert("1.0", PLANTILLAS_SQL["Ver datos de 'arcos' (50 filas)"])

        # Atajos de teclado para ejecutar
        self.sql_editor.bind("<F5>", lambda e: self.ejecutar_consulta_sql_thread())
        self.sql_editor.bind("<Control-Return>", lambda e: self.ejecutar_consulta_sql_thread())

        # 4. Panel de Resultados
        self.nb_sql_results = ttk.Notebook(frame_sql_main)
        self.nb_sql_results.pack(fill="both", expand=True)

        # Pestaña 1: Resultados Tabulares
        tab_tabla = ttk.Frame(self.nb_sql_results, padding=4)
        self.nb_sql_results.add(tab_tabla, text="  📊 Resultados (Tabla)  ")

        frame_tree_sql = ttk.Frame(tab_tabla)
        frame_tree_sql.pack(fill="both", expand=True)

        self.sql_tree = ttk.Treeview(frame_tree_sql, show="headings", selectmode="extended")
        scroll_sql_y = ttk.Scrollbar(frame_tree_sql, orient="vertical", command=self.sql_tree.yview)
        scroll_sql_x = ttk.Scrollbar(frame_tree_sql, orient="horizontal", command=self.sql_tree.xview)
        self.sql_tree.configure(yscrollcommand=scroll_sql_y.set, xscrollcommand=scroll_sql_x.set)

        self.sql_tree.grid(row=0, column=0, sticky="nsew")
        scroll_sql_y.grid(row=0, column=1, sticky="ns")
        scroll_sql_x.grid(row=1, column=0, sticky="ew")
        frame_tree_sql.columnconfigure(0, weight=1)
        frame_tree_sql.rowconfigure(0, weight=1)

        self.lbl_sql_metrics = ttk.Label(tab_tabla, text="Sin consultas ejecutadas aún.", font=("Segoe UI", 8), foreground="#71717a")
        self.lbl_sql_metrics.pack(fill="x", pady=(2, 0))

        # Pestaña 2: Log / Mensajes del Servidor
        tab_log = ttk.Frame(self.nb_sql_results, padding=4)
        self.nb_sql_results.add(tab_log, text="  💬 Mensajes & Registro  ")

        self.sql_log = scrolledtext.ScrolledText(
            tab_log,
            state="disabled",
            wrap="word",
            font=("Consolas", 9),
            borderwidth=0,
            highlightthickness=0
        )
        self.sql_log.pack(fill="both", expand=True)

    def _cargar_plantilla_sql(self):
        nombre = self.combo_plantillas.get()
        if nombre in PLANTILLAS_SQL:
            self.sql_editor.delete("1.0", tk.END)
            self.sql_editor.insert("1.0", PLANTILLAS_SQL[nombre])

    def _set_sql_and_run(self, query):
        self.sql_editor.delete("1.0", tk.END)
        self.sql_editor.insert("1.0", query)
        self.ejecutar_consulta_sql_thread()

    def _limpiar_editor_sql(self):
        self.sql_editor.delete("1.0", tk.END)

    def _log_sql(self, mensaje, error=False):
        timestamp = datetime.datetime.now().strftime("%H:%M:%S")
        self.sql_log.configure(state="normal")
        prefijo = "[ERROR]" if error else "[INFO]"
        self.sql_log.insert(tk.END, f"[{timestamp}] {prefijo} {mensaje}\n")
        self.sql_log.see(tk.END)
        self.sql_log.configure(state="disabled")

    def _crear_input(self, parent, label, default, r, c, w):
        ttk.Label(parent, text=label).grid(row=r, column=c, sticky="w", padx=(4, 1))
        e = ttk.Entry(parent, width=w)
        e.insert(0, default)
        e.grid(row=r, column=c + 1, padx=(1, 4), pady=2)
        return e

    def _crear_input_password(self, parent, label, default, r, c, w):
        ttk.Label(parent, text=label).grid(row=r, column=c, sticky="w", padx=(4, 1))
        e = ttk.Entry(parent, width=w, show="•")
        e.insert(0, default)
        e.grid(row=r, column=c + 1, padx=(1, 1), pady=2)

        btn_eye = ttk.Button(
            parent,
            text="👁",
            width=3,
            style="Ghost.TButton",
            command=lambda: self._toggle_password_visibility(e, btn_eye)
        )
        btn_eye.grid(row=r, column=c + 2, padx=(0, 4), pady=2)
        return e, btn_eye

    def _toggle_password_visibility(self, entry, button):
        if entry.cget("show") == "":
            entry.config(show="•")
            button.config(text="👁")
        else:
            entry.config(show="")
            button.config(text="🔒")

    def _obtener_configuraciones(self):
        if self.notebook_conn.index(self.notebook_conn.select()) == 0:
            uri_o = self.entry_url_origen.get().strip()
            uri_d = self.entry_url_destino.get().strip()
            motor = "mysql" if uri_o.startswith("mysql://") else "postgresql"
            return motor, None, uri_o, uri_d
        else:
            motor = self.combo_motor.get()
            cfg_o = {
                "host": self.f_host_o.get().strip(),
                "port": int(self.f_port_o.get().strip() or (3306 if motor == "mysql" else 5432)),
                "user": self.f_user_o.get().strip(),
                "password": self.f_pass_o.get().strip(),
                "database": self.f_db_o.get().strip(),
            }
            u_d = self.f_user_d.get().strip()
            p_d = self.f_pass_d.get().strip()
            h_d = self.f_host_d.get().strip()
            pr_d = self.f_port_d.get().strip() or "5432"
            db_d = self.f_db_d.get().strip()
            uri_d = f"postgresql://{u_d}:{p_d}@{h_d}:{pr_d}/{db_d}?sslmode=require"
            return motor, cfg_o, None, uri_d

    def _conectar_origen(self, motor, cfg, uri):
        if motor == "mysql":
            if not mysql:
                raise Exception("Librería mysql-connector-python no instalada. Ejecuta: pip install mysql-connector-python")
            if cfg:
                return mysql.connector.connect(**cfg)
            parsed = urlparse(uri)
            return mysql.connector.connect(
                host=parsed.hostname,
                port=parsed.port or 3306,
                user=parsed.username,
                password=parsed.password,
                database=parsed.path.lstrip("/"),
            )
        else:
            if cfg:
                return psycopg2.connect(**cfg)
            return psycopg2.connect(uri)

    def log(self, mensaje):
        self.log_text.configure(state="normal")
        self.log_text.insert(tk.END, mensaje + "\n")
        self.log_text.see(tk.END)
        self.log_text.configure(state="disabled")

    def _on_tree_click(self, event):
        if self.tree.identify("region", event.x, event.y) in ("tree", "cell"):
            item = self.tree.identify_row(event.y)
            if item:
                self._toggle_seleccion(item)

    def _on_tree_space(self, event):
        item = self.tree.focus()
        if item:
            self._toggle_seleccion(item)

    def _toggle_seleccion(self, tabla_id):
        if tabla_id in self.datos_tablas:
            self.datos_tablas[tabla_id]["selected"] = not self.datos_tablas[tabla_id]["selected"]
            self._actualizar_fila_tree(tabla_id)
            self._actualizar_contador_total()

    def _actualizar_fila_tree(self, tabla_id):
        info = self.datos_tablas[tabla_id]
        icono = "✔" if info["selected"] else "✖"
        self.tree.item(tabla_id, values=(icono, tabla_id, f"{info['count']:,}", info["status"]))

    def actualizar_vista_tabla(self):
        filtro = self.var_filtro.get().strip().lower()
        self.tree.delete(*self.tree.get_children())
        for tabla, info in self.datos_tablas.items():
            if filtro in tabla.lower():
                icono = "✔" if info["selected"] else "✖"
                self.tree.insert("", "end", iid=tabla, values=(icono, tabla, f"{info['count']:,}", info["status"]))

    def _actualizar_contador_total(self):
        total_sel = sum(1 for d in self.datos_tablas.values() if d["selected"])
        total_tablas = len(self.datos_tablas)
        total_filas = sum(d["count"] for d in self.datos_tablas.values() if d["selected"])
        self.lbl_contador.config(text=f"{total_sel}/{total_tablas} sel. ({total_filas:,} filas)")

    def seleccionar_todas(self):
        for tabla in self.datos_tablas:
            self.datos_tablas[tabla]["selected"] = True
        self.actualizar_vista_tabla()
        self._actualizar_contador_total()

    def deseleccionar_todas(self):
        for tabla in self.datos_tablas:
            self.datos_tablas[tabla]["selected"] = False
        self.actualizar_vista_tabla()
        self._actualizar_contador_total()

    def cargar_tablas(self):
        try:
            motor, cfg_o, uri_o, _ = self._obtener_configuraciones()
            conn = self._conectar_origen(motor, cfg_o, uri_o)
            cur = conn.cursor()

            if motor == "mysql":
                cur.execute("SHOW FULL TABLES WHERE Table_type = 'BASE TABLE';")
                tablas = [r[0] for r in cur.fetchall()]
            else:
                cur.execute(
                    "SELECT table_name FROM information_schema.tables WHERE table_schema = 'public' AND table_type = 'BASE TABLE' ORDER BY table_name;"
                )
                tablas = [r[0] for r in cur.fetchall()]

            self.datos_tablas.clear()

            if not tablas:
                cur.close()
                conn.close()
                messagebox.showwarning("Aviso", "No se encontraron tablas en la base de datos origen.")
                return

            for tabla in tablas:
                cur.execute(f"SELECT COUNT(*) FROM `{tabla}`" if motor == "mysql" else f'SELECT COUNT(*) FROM "{tabla}";')
                filas_count = cur.fetchone()[0]
                self.datos_tablas[tabla] = {"count": filas_count, "selected": True, "status": "Listo"}

            cur.close()
            conn.close()

            self.actualizar_vista_tabla()
            self._actualizar_contador_total()
            self.btn_select_all.config(state="normal")
            self.btn_deselect_all.config(state="normal")
            self.btn_migrar.config(state="normal")
            self.log(f"-> Conectado a [{motor.upper()}]. Se detectaron {len(tablas)} tablas.")

        except Exception as e:
            messagebox.showerror("Error Origen", f"Fallo al conectar con la base de datos origen:\n{e}")

    def iniciar_migracion_thread(self):
        tablas_a_migrar = [tabla for tabla, info in self.datos_tablas.items() if info["selected"]]
        if not tablas_a_migrar:
            messagebox.showwarning("Aviso", "Selecciona al menos una tabla para migrar.")
            return

        self.btn_migrar.config(state="disabled")
        threading.Thread(target=self.ejecutar_migracion, args=(tablas_a_migrar,), daemon=True).start()

    def _mapear_tipo_mysql_a_postgres(self, col_type, extra):
        c_type = col_type.lower()
        if "auto_increment" in extra.lower():
            return "BIGSERIAL" if "bigint" in c_type else "SERIAL"
        if "tinyint(1)" in c_type or c_type == "boolean":
            return "BOOLEAN"
        if "int" in c_type:
            if "bigint" in c_type:
                return "BIGINT"
            if "smallint" in c_type:
                return "SMALLINT"
            return "INTEGER"
        if "varchar" in c_type or "char" in c_type:
            return col_type.upper()
        if "text" in c_type or "longtext" in c_type or "mediumtext" in c_type:
            return "TEXT"
        if "decimal" in c_type or "numeric" in c_type or "double" in c_type or "float" in c_type:
            return col_type.upper()
        if "datetime" in c_type or "timestamp" in c_type:
            return "TIMESTAMP WITHOUT TIME ZONE"
        if "date" in c_type:
            return "DATE"
        if "json" in c_type:
            return "JSONB"
        return "TEXT"

    def clonar_estructura_tabla(self, motor, cur_origen, cur_remota, conn_remota, tabla):
        col_defs = []
        pk_cols = []

        if motor == "mysql":
            cur_origen.execute(f"DESCRIBE `{tabla}`;")
            columnas = cur_origen.fetchall()

            for col_name, data_type, is_null, key, default_val, extra in columnas:
                tipo_pg = self._mapear_tipo_mysql_a_postgres(data_type, extra)

                if "SERIAL" in tipo_pg:
                    col_def = f'"{col_name}" {tipo_pg}'
                else:
                    null_str = "NOT NULL" if is_null == "NO" else "NULL"
                    default_str = ""
                    if default_val is not None:
                        default_str = f"DEFAULT '{default_val}'" if not str(default_val).isdigit() else f"DEFAULT {default_val}"
                    col_def = f'"{col_name}" {tipo_pg} {default_str} {null_str}'.strip()

                col_defs.append(col_def)
                if key == "PRI":
                    pk_cols.append(f'"{col_name}"')
        else:
            cur_origen.execute(
                """
                SELECT c.column_name, c.data_type, c.character_maximum_length, c.is_nullable, c.column_default, c.udt_name,
                       COALESCE(c.is_identity, 'NO') as is_identity,
                       COALESCE(c.identity_generation, '') as identity_gen
                FROM information_schema.columns c
                WHERE c.table_schema = 'public' AND c.table_name = %s
                ORDER BY c.ordinal_position;
            """,
                (tabla,),
            )
            columnas = cur_origen.fetchall()

            cur_origen.execute(
                """
                SELECT kcu.column_name
                FROM information_schema.table_constraints tc
                JOIN information_schema.key_column_usage kcu 
                  ON tc.constraint_name = kcu.constraint_name AND tc.table_schema = kcu.table_schema
                WHERE tc.constraint_type = 'PRIMARY KEY' AND tc.table_schema = 'public' AND tc.table_name = %s;
            """,
                (tabla,),
            )
            pk_cols = [f'"{r[0]}"' for r in cur_origen.fetchall()]

            for col_name, data_type, max_len, is_null, default_val, udt_name, is_identity, identity_gen in columnas:
                tipo_sql = udt_name
                if max_len:
                    tipo_sql = f"{data_type}({max_len})"
                elif data_type in [
                    "integer",
                    "bigint",
                    "smallint",
                    "boolean",
                    "text",
                    "json",
                    "jsonb",
                    "date",
                    "timestamp without time zone",
                    "timestamp with time zone",
                ]:
                    tipo_sql = data_type

                # Manejo de IDENTITY y SERIAL en PostgreSQL
                if is_identity == "YES":
                    gen = "BY DEFAULT" if "BY DEFAULT" in identity_gen.upper() else "BY DEFAULT"
                    col_def = f'"{col_name}" {tipo_sql} GENERATED {gen} AS IDENTITY'
                elif default_val and "nextval" in str(default_val):
                    tipo_sql = "BIGSERIAL" if "bigint" in tipo_sql else "SERIAL"
                    col_def = f'"{col_name}" {tipo_sql}'
                else:
                    null_str = "NOT NULL" if is_null == "NO" else "NULL"
                    default_str = f"DEFAULT {default_val}" if default_val else ""
                    col_def = f'"{col_name}" {tipo_sql} {default_str} {null_str}'.strip()

                col_defs.append(col_def)

        if pk_cols:
            col_defs.append(f'PRIMARY KEY ({", ".join(pk_cols)})')

        ddl = f'CREATE TABLE IF NOT EXISTS "{tabla}" (\n  ' + ",\n  ".join(col_defs) + "\n);"
        cur_remota.execute(ddl)
        conn_remota.commit()

    def ejecutar_migracion(self, tablas):
        try:
            motor, cfg_o, uri_o, uri_d = self._obtener_configuraciones()
            self.log(f"\n================ Iniciando Migración [{motor.upper()} -> POSTGRESQL] ================")

            conn_origen = self._conectar_origen(motor, cfg_o, uri_o)
            conn_remota = psycopg2.connect(uri_d)

            cur_origen = conn_origen.cursor()
            cur_remota = conn_remota.cursor()

            for tabla in tablas:
                self.datos_tablas[tabla]["status"] = "Migrando..."
                self.root.after(0, lambda t=tabla: self._actualizar_fila_tree(t))

                self.log(f"\n[+] Verificando/Creando estructura para '{tabla}'...")
                self.clonar_estructura_tabla(motor, cur_origen, cur_remota, conn_remota, tabla)

                # Extraer datos
                if motor == "mysql":
                    cur_origen.execute(f"SELECT * FROM `{tabla}`;")
                else:
                    cur_origen.execute(f'SELECT * FROM "{tabla}";')

                filas = cur_origen.fetchall()

                if not filas:
                    self.log(f"    -> Tabla '{tabla}' vacía. Estructura lista.")
                    self.datos_tablas[tabla]["status"] = "Vacía / OK"
                    self.root.after(0, lambda t=tabla: self._actualizar_fila_tree(t))
                    continue

                columnas = [f'"{desc[0]}"' for desc in cur_origen.description]
                nombres_cols = ", ".join(columnas)
                query_insert = f'INSERT INTO "{tabla}" ({nombres_cols}) VALUES %s ON CONFLICT DO NOTHING;'

                batch_size = 1000
                for i in range(0, len(filas), batch_size):
                    lote = filas[i : i + batch_size]
                    execute_values(cur_remota, query_insert, lote)

                conn_remota.commit()
                self.datos_tablas[tabla]["status"] = "Completado"
                self.root.after(0, lambda t=tabla: self._actualizar_fila_tree(t))
                self.log(f"    -> Éxito: {len(filas)} filas pasadas a '{tabla}'.")

            # Sincronización robusta de secuencias e identidades en PostgreSQL
            self.log("\n[+] Sincronizando secuencias de IDs en destino...")
            for tab in tablas:
                try:
                    cur_remota.execute("""
                        SELECT column_name 
                        FROM information_schema.columns 
                        WHERE table_schema = 'public' AND table_name = %s
                          AND (is_identity = 'YES' OR column_default LIKE '%nextval%');
                    """, (tab,))
                    cols_seq = cur_remota.fetchall()
                    for (c_name,) in cols_seq:
                        cur_remota.execute(f"""
                            SELECT setval(pg_get_serial_sequence('"{tab}"', '{c_name}'), 
                                          COALESCE((SELECT MAX("{c_name}") FROM "{tab}"), 1));
                        """)
                except Exception as seq_err:
                    self.log(f"    [!] Advertencia al sincronizar secuencia en '{tab}': {seq_err}")
            conn_remota.commit()

            self.log("\n[✓] MIGRACIÓN FINALIZADA CON ÉXITO.")
            messagebox.showinfo("Completado", "La migración finalizó correctamente.")

            cur_origen.close()
            cur_remota.close()
            conn_origen.close()
            conn_remota.close()

        except Exception as e:
            self.log(f"\n[!] Error crítico: {e}")
            messagebox.showerror("Error en Migración", str(e))
        finally:
            self.btn_migrar.config(state="normal")

    # =========================================================================
    # MODULO: CONSOLA SQL Y GESTIÓN DE TABLAS
    # =========================================================================
    def probar_conexion_sql(self):
        target = self.target_sql.get()
        try:
            motor, cfg_o, uri_o, uri_d = self._obtener_configuraciones()
            if target == "destino":
                conn = psycopg2.connect(uri_d)
                cur = conn.cursor()
                cur.execute("SELECT current_database(), current_user, version();")
                db, user, ver = cur.fetchone()
                cur.close()
                conn.close()
                msg = f"Conexión exitosa a Destino (Render):\nBase de datos: {db}\nUsuario: {user}\nVersión: {ver[:60]}..."
                self._log_sql(f"Conexión verificada a Destino: {db} como {user}")
                messagebox.showinfo("Conexión Destino OK", msg)
            else:
                conn = self._conectar_origen(motor, cfg_o, uri_o)
                cur = conn.cursor()
                cur.execute("SELECT current_database(), current_user, version();" if motor != "mysql" else "SELECT database(), user(), version();")
                db, user, ver = cur.fetchone()
                cur.close()
                conn.close()
                msg = f"Conexión exitosa a Origen ({motor.upper()}):\nBase de datos: {db}\nUsuario: {user}\nVersión: {ver[:60]}..."
                self._log_sql(f"Conexión verificada a Origen [{motor}]: {db}")
                messagebox.showinfo("Conexión Origen OK", msg)
        except Exception as e:
            self._log_sql(f"Error al conectar con '{target}': {e}", error=True)
            messagebox.showerror("Error de Conexión", f"No se pudo conectar a {target.upper()}:\n{e}")

    def ejecutar_consulta_sql_thread(self):
        query = self.sql_editor.get("1.0", tk.END).strip()
        if not query:
            messagebox.showwarning("Aviso", "Escribe una consulta SQL antes de ejecutar.")
            return

        self.lbl_sql_status.config(text="Ejecutando consulta...")
        threading.Thread(target=self._ejecutar_consulta_sql_worker, args=(query,), daemon=True).start()

    def _ejecutar_consulta_sql_worker(self, query):
        target = self.target_sql.get()
        t0 = time.time()
        conn = None
        try:
            motor, cfg_o, uri_o, uri_d = self._obtener_configuraciones()

            if target == "destino":
                conn = psycopg2.connect(uri_d)
            else:
                conn = self._conectar_origen(motor, cfg_o, uri_o)

            cur = conn.cursor()
            cur.execute(query)
            elapsed = time.time() - t0

            # Verificar si la consulta devolvió filas (SELECT / RETURNING)
            if cur.description:
                columnas = [d[0] for d in cur.description]
                filas = cur.fetchall()
                conn.commit()
                cur.close()
                conn.close()

                self.root.after(0, lambda: self._mostrar_resultados_tabla(columnas, filas, elapsed))
                self.root.after(0, lambda: self._log_sql(f"Query SELECT completada en {elapsed:.3f}s. {len(filas)} filas obtenidas."))
                self.root.after(0, lambda: self.lbl_sql_status.config(text=f"✔ Éxito: {len(filas)} filas en {elapsed:.3f}s"))
            else:
                conn.commit()
                rowcount = cur.rowcount
                cur.close()
                conn.close()

                mensaje_exito = f"Comando ejecutado exitosamente en {elapsed:.3f}s. Filas afectadas: {rowcount if rowcount >= 0 else 'N/A'}."
                self.root.after(0, lambda: self._mostrar_mensaje_dml(mensaje_exito, elapsed))
                self.root.after(0, lambda: self._log_sql(mensaje_exito))
                self.root.after(0, lambda: self.lbl_sql_status.config(text=f"✔ Ejecutado en {elapsed:.3f}s (Afectadas: {rowcount})"))

        except Exception as e:
            if conn:
                try:
                    conn.rollback()
                    conn.close()
                except Exception:
                    pass
            elapsed = time.time() - t0
            err_msg = str(e)
            self.root.after(0, lambda: self._mostrar_error_sql(err_msg, elapsed))
            self.root.after(0, lambda: self._log_sql(f"Error al ejecutar: {err_msg}", error=True))
            self.root.after(0, lambda: self.lbl_sql_status.config(text="✖ Error en consulta."))

    def _mostrar_resultados_tabla(self, columnas, filas, elapsed):
        self.nb_sql_results.select(0)  # Pestaña de tabla
        self.sql_tree.delete(*self.sql_tree.get_children())

        # Configurar columnas dinámicamente
        self.sql_tree["columns"] = columnas
        for col in columnas:
            self.sql_tree.heading(col, text=col, anchor="w")
            # Ancho proporcional inicial
            ancho = max(len(col) * 11, 100)
            self.sql_tree.column(col, width=ancho, minwidth=60, anchor="w")

        # Insertar filas (formatear nulos y fechas)
        for fila in filas:
            fila_formateada = ["" if v is None else str(v) for v in fila]
            self.sql_tree.insert("", "end", values=fila_formateada)

        self.lbl_sql_metrics.config(text=f"📊 Total de registros: {len(filas):,}   |   Tiempo de ejecución: {elapsed:.3f}s   |   Columnas: {len(columnas)}")

    def _mostrar_mensaje_dml(self, mensaje, elapsed):
        self.nb_sql_results.select(1)  # Pestaña de Mensajes
        self.lbl_sql_metrics.config(text=f"Comando DDL/DML ejecutado en {elapsed:.3f}s.")
        self._log_sql(mensaje)

    def _mostrar_error_sql(self, err_msg, elapsed):
        self.nb_sql_results.select(1)  # Pestaña de Mensajes
        messagebox.showerror("Error SQL", f"Ocurrió un error al ejecutar la consulta:\n\n{err_msg}")

    def reparar_auto_increment_render_thread(self):
        confirm = messagebox.askyesno(
            "Confirmar Reparación",
            "Esta herramienta inspeccionará todas las tablas en Destino (Render) y configurará automáticamente las columnas ID primarias con IDENTITY y sus secuencias sincronizadas al valor máximo actual.\n\n¿Deseas continuar?"
        )
        if not confirm:
            return

        self.lbl_sql_status.config(text="Reparando Auto-Increment en Render...")
        threading.Thread(target=self._reparar_auto_increment_render_worker, daemon=True).start()

    def _reparar_auto_increment_render_worker(self):
        _, _, _, uri_d = self._obtener_configuraciones()
        self.root.after(0, lambda: self.nb_sql_results.select(1))
        self.root.after(0, lambda: self._log_sql("Iniciando análisis y reparación de Auto-Increment (IDENTITY) en Render..."))

        try:
            conn = psycopg2.connect(uri_d)
            cur = conn.cursor()

            # Buscar todas las columnas de tablas con clave primaria entera sin identity o sin secuencia
            cur.execute("""
                SELECT c.table_name, c.column_name
                FROM information_schema.columns c
                JOIN information_schema.table_constraints tc 
                  ON tc.table_name = c.table_name AND tc.table_schema = c.table_schema
                JOIN information_schema.key_column_usage kcu 
                  ON tc.constraint_name = kcu.constraint_name AND tc.table_schema = kcu.table_schema AND kcu.column_name = c.column_name
                WHERE c.table_schema = 'public'
                  AND tc.constraint_type = 'PRIMARY KEY'
                  AND c.data_type IN ('integer', 'bigint', 'smallint')
                  AND COALESCE(c.is_identity, 'NO') = 'NO'
                  AND (c.column_default IS NULL OR c.column_default NOT LIKE '%nextval%')
                  AND c.table_name IN (
                      SELECT table_name
                      FROM information_schema.key_column_usage
                      WHERE table_schema = 'public' AND constraint_name = tc.constraint_name
                      GROUP BY table_name
                      HAVING COUNT(*) = 1
                  )
                ORDER BY c.table_name;
            """)
            tablas_a_reparar = cur.fetchall()

            if not tablas_a_reparar:
                self.root.after(0, lambda: self._log_sql("✔ Todas las tablas ya cuentan con IDENTITY o secuencia configurada correctamente."))
                self.root.after(0, lambda: messagebox.showinfo("Información", "No se encontraron tablas pendientes de reparación. Todas las secuencias e identidades están en orden."))
                cur.close()
                conn.close()
                return

            reparadas = 0
            for t, col in tablas_a_reparar:
                try:
                    cur.execute(f'ALTER TABLE "{t}" ALTER COLUMN "{col}" ADD GENERATED BY DEFAULT AS IDENTITY;')
                    cur.execute(f"""
                        SELECT setval(pg_get_serial_sequence('"{t}"', '{col}'), COALESCE((SELECT MAX("{col}") FROM "{t}"), 1));
                    """)
                    conn.commit()
                    reparadas += 1
                    msg_ok = f" ✔ {t}.{col} -> Configurado con GENERATED BY DEFAULT AS IDENTITY (Secuencia sincronizada)."
                    self.root.after(0, lambda m=msg_ok: self._log_sql(m))
                except Exception as err_tab:
                    conn.rollback()
                    msg_err = f" ✖ Error reparando {t}.{col}: {err_tab}"
                    self.root.after(0, lambda m=msg_err: self._log_sql(m, error=True))

            cur.close()
            conn.close()

            res_final = f"Proceso finalizado. Se repararon {reparadas} de {len(tablas_a_reparar)} tablas candidatas en Render."
            self.root.after(0, lambda: self._log_sql(res_final))
            self.root.after(0, lambda: messagebox.showinfo("Reparación Completada", res_final))
            self.root.after(0, lambda: self.lbl_sql_status.config(text=f"✔ Reparadas {reparadas} tablas."))

        except Exception as e:
            self.root.after(0, lambda: self._log_sql(f"Error general en reparación: {e}", error=True))
            self.root.after(0, lambda: messagebox.showerror("Error", f"Fallo al ejecutar la reparación:\n{e}"))


if __name__ == "__main__":
    root = tk.Tk()
    app = UniversalMigratorApp(root)
    root.mainloop()