<?php
include('../config/db.php');

$action = $_REQUEST['action'] ?? '';

function asegurarTablaTecnicos(PDO $pdo): void
{
    $pdo->exec("
        CREATE TABLE IF NOT EXISTS tecnicos (
            id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            nombre VARCHAR(150) NOT NULL UNIQUE,
            telefono VARCHAR(30),
            puesto VARCHAR(80),
            activo INTEGER NOT NULL DEFAULT 1,
            eliminado INTEGER NOT NULL DEFAULT 0,
            created_at TIMESTAMP WITHOUT TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP
        )
    ");
    $pdo->exec("ALTER TABLE tecnicos ADD COLUMN IF NOT EXISTS eliminado INTEGER NOT NULL DEFAULT 0");
    $pdo->exec("CREATE INDEX IF NOT EXISTS idx_tecnicos_activo ON tecnicos (activo)");
}

asegurarTablaTecnicos($pdo);

try {
    switch ($action) {
        case 'add':
            $nombre = trim($_POST['nombre'] ?? '');
            $telefono = trim($_POST['telefono'] ?? '');
            $puesto = trim($_POST['puesto'] ?? '');

            if ($nombre === '') {
                header("Location: ../views/tecnicos.php?error=Nombre obligatorio");
                exit;
            }

            $stmt = $pdo->prepare("
                INSERT INTO tecnicos (nombre, telefono, puesto, activo)
                VALUES (?, ?, ?, 1)
                ON CONFLICT (nombre) DO UPDATE
                SET telefono = EXCLUDED.telefono,
                    puesto = EXCLUDED.puesto,
                    activo = 1,
                    eliminado = 0
            ");
            $stmt->execute([$nombre, $telefono ?: null, $puesto ?: null]);

            header("Location: ../views/tecnicos.php?msg=Tecnico registrado correctamente");
            exit;

        case 'update':
            $id = (int)($_POST['id'] ?? 0);
            $nombre = trim($_POST['nombre'] ?? '');
            $telefono = trim($_POST['telefono'] ?? '');
            $puesto = trim($_POST['puesto'] ?? '');
            $activo = isset($_POST['activo']) ? 1 : 0;

            if ($id <= 0 || $nombre === '') {
                header("Location: ../views/tecnicos.php?error=Datos incompletos");
                exit;
            }

            $stmt = $pdo->prepare("
                UPDATE tecnicos
                SET nombre = ?, telefono = ?, puesto = ?, activo = ?
                WHERE id = ?
            ");
            $stmt->execute([$nombre, $telefono ?: null, $puesto ?: null, $activo, $id]);

            header("Location: ../views/tecnicos.php?msg=Tecnico actualizado correctamente");
            exit;

        case 'toggle':
            $id = (int)($_GET['id'] ?? 0);
            if ($id <= 0) {
                header("Location: ../views/tecnicos.php?error=ID invalido");
                exit;
            }

            $stmt = $pdo->prepare("UPDATE tecnicos SET activo = CASE WHEN activo = 1 THEN 0 ELSE 1 END WHERE id = ?");
            $stmt->execute([$id]);

            header("Location: ../views/tecnicos.php?msg=Estado actualizado");
            exit;

        case 'delete':
            $id = (int)($_GET['id'] ?? 0);
            if ($id <= 0) {
                header("Location: ../views/tecnicos.php?error=ID invalido");
                exit;
            }

            $stmt = $pdo->prepare("UPDATE tecnicos SET activo = 0, eliminado = 1 WHERE id = ?");
            $stmt->execute([$id]);

            header("Location: ../views/tecnicos.php?msg=Tecnico eliminado");
            exit;

        default:
            header("Location: ../views/tecnicos.php");
            exit;
    }
} catch (Exception $e) {
    header("Location: ../views/tecnicos.php?error=" . urlencode($e->getMessage()));
    exit;
}
