<?php

return [
    'checklist' => [
        'title' => 'Diagnóstico Inicial',
        'pdf_title' => 'DIAGNÓSTICO INICIAL',
        'file_prefix' => 'Diagnostico_Inicial',
        'code' => 'INN-FOR-002-04',
        'fecha' => '02 -Abril-2026',
        'description' => 'Registra el estado, observaciones y cambios de cada componente del arco.',
        'icon' => 'bi-clipboard2-check',
        'blank' => 'INN-FOR-002-04  Diagnóstico Inicial.docx',
        'template' => 'INN-FOR-002-04  Diagnóstico Inicial.docx',
        'components' => [
            'Estructura Metálica',
            'Gabinete',
            'Lector SpeedWay / RFID',
            'Antenas Yagi',
            'Paneles Solares',
            'Baterías',
            'Cámaras / Videovigilancia',
            'Switch',
            'Enlace',
            'Cableado',
            'Otro',
        ],
    ],
    'quality' => [
        'title' => 'PRUEBAS DE CALIDAD',
        'pdf_title' => 'PRUEBAS DE CALIDAD',
        'file_prefix' => 'PRUEBAS DE CALIDAD',
        'code' => 'INN-FOR-002-01',
        'fecha' => '02 -Abril-2026',
        'description' => 'Documenta las pruebas por carril, energía, enlace y sistema de monitoreo.',
        'icon' => 'bi-patch-check',
        'blank' => 'INN-FOR-002-01  Pruebas de Calidad.docx',
        'template' => 'INN-FOR-002-01  Pruebas de Calidad.docx',
        'lanes' => 2,
    ],
    'tools' => [
        'title' => 'SALIDA DE HERRAMIENTA Y MATERIAL',
        'pdf_title' => 'SALIDA DE HERRAMIENTA Y MATERIAL',
        'file_prefix' => 'SALIDA DE HERRAMIENTA Y MATERIAL',
        'code' => 'INN-FOR-002-02',
        'fecha' => '02 -Abril-2026',
        'description' => 'Selecciona herramientas, consumibles y equipo de protección para el servicio.',
        'icon' => 'bi-tools',
        'blank' => 'INN-FOR-002-02 Salida de Herramienta y Material.docx',
        'template' => 'INN-FOR-002-02 Salida de Herramienta y Material.docx',
        'tools' => [
            ['Pinzas varias', 'Destornilladores varios'],
            ['Multímetro', 'Caja de puntas para atornillador eléctrico'],
            ['Escalera / Equipo de Altura', 'Polea'],
            ['Taladro / Rotomartillo', 'Inversor de 12V a 120V'],
            ['Laptop', 'Conector RJ45'],
            ['Atornillador impacto', 'Ferrules'],
            ['Atornillador eléctrico', 'Ojillos'],
            ['Metro', 'Tornillería varios'],
            ['Pinza Ponchadora Ferrules', 'Cinta Métrica'],
            ['Pinzas Conector M4', 'Serrucho'],
            ['Ponchadoras para Conector N', 'Llaves españolas'],
            ['Juego de dados', 'Cinchos de plástico'],
        ],
        'consumables' => [
            ['Antenas Yagi', 'Paneles Solares'],
            ['Baterías', 'Lector SpeedWay de repuesto'],
            ['Switch de repuesto', 'Cable de UTP'],
            ['Herrajes para Panel Solar', 'Cableado fotovoltaico'],
            ['Herrajes para Gabinete', 'Cable de luz 1+1'],
        ],
        'quantifiable_consumables' => [
            'Antenas Yagi',
            'Paneles Solares',
            'Baterías',
            'Lector SpeedWay de repuesto',
            'Switch de repuesto',
        ],
        'epp' => [
            ['Casco de seguridad', 'Guantes'],
            ['Chaleco con reflejantes', 'Lentes de Seguridad'],
            ['Botas de seguridad', 'Cinturón de Seguridad'],
        ],
    ],
    'bitacora' => [
        'title' => 'BITÁCORA INSTALACIÓN DE ARCO LECTOR',
        'pdf_title' => 'BITÁCORA INSTALACIÓN DE ARCO LECTOR',
        'file_prefix' => 'BITÁCORA INSTALACIÓN DE ARCO LECTOR',
        'code' => 'INN-FOR-002-03',
        'fecha' => '02 -Abril-2026',
        'description' => 'Registra las actividades realizadas durante el servicio de instalación.',
        'icon' => 'bi-journal-text',
        'blank' => 'INN-FOR-002-03 Bitácora instalación de Arco Lector.docx',
        'template' => 'INN-FOR-002-03 Bitácora instalación de Arco Lector.docx',
    ],
    'baja' => [
        'title' => 'BAJA DE ARCO LECTOR',
        'pdf_title' => 'BAJA DE ARCO LECTOR',
        'file_prefix' => 'BAJA DE ARCO LECTOR',
        'code' => 'INN-FOR-002-05',
        'fecha' => '12-septiembre-2026',
        'description' => 'Registra la baja de un arco lector y los motivos de la misma.',
        'icon' => 'bi-trash3',
        'blank' => 'INN-FOR-002-05 Baja de Arco Lector.docx',
        'template' => 'INN-FOR-002-05 Baja de Arco Lector.docx',
    ],
];
