<?php

return [
    'checklist' => [
        'title' => 'Check List de Diagnóstico Inicial',
        'pdf_title' => 'CHECK LIST DE DIAGNÓSTICO INICIAL',
        'code' => 'INN-FOR-002',
        'description' => 'Registra el estado, observaciones y cambios de cada componente del arco.',
        'icon' => 'bi-clipboard2-check',
        'blank' => 'checklist_diagnostico.docx',
        'template' => 'checklist_diagnostico_plantilla.docx',
        'components' => [
            'Estructura Metálica',
            'Gabinete',
            'Lector SpeedWay / RFID',
            'Antenas Yagi',
            'Paneles Solares',
            'Baterías',
            'Cámaras / Videovigilancia',
            'Switch',
            'Enlace',
            'Cableado',
            'Otro',
        ],
    ],
    'quality' => [
        'title' => 'Formato de Pruebas de Calidad',
        'pdf_title' => 'PRUEBAS DE CALIDAD',
        'code' => 'INN-FOR-003',
        'description' => 'Documenta las pruebas por carril, energía, enlace y sistema de monitoreo.',
        'icon' => 'bi-patch-check',
        'blank' => 'pruebas_calidad.docx',
        'template' => 'pruebas_calidad_plantilla.docx',
        'lanes' => 2,
    ],
    'tools' => [
        'title' => 'Formato de Herramientas',
        'pdf_title' => 'FORMATO DE HERRAMIENTAS',
        'code' => 'INN-FOR-004',
        'description' => 'Selecciona herramientas, consumibles y equipo de protección para el servicio.',
        'icon' => 'bi-tools',
        'blank' => 'herramientas.docx',
        'template' => 'herramientas_plantilla.docx',
        'tools' => [
            ['Pinzas varias', 'Destornilladores varios'],
            ['Multímetro', 'Caja de puntas para atornillador eléctrico'],
            ['Escalera / Equipo de Altura', 'Polea'],
            ['Taladro / Rotomartillo', 'Inversor de 12V a 120V'],
            ['Laptop', 'Conector RJ45'],
            ['Atornillador impacto', 'Ferrules'],
            ['Atornillador eléctrico', 'Ojillos'],
            ['Metro', 'Tornillería varios'],
            ['Pinza Ponchadora Ferrules', 'Cinta Métrica'],
            ['Pinzas Conector M4', 'Serrucho'],
            ['Ponchadoras para Conector N', 'Llaves españolas'],
            ['Juego de dados', 'Cinchos de plástico'],
        ],
        'consumables' => [
            ['Antenas Yagi', 'Cable de UTP'],
            ['Baterías', 'Lector SpeedWay de repuesto'],
            ['Herrajes para Panel Solar', 'Switch de repuesto'],
            ['Herrajes para Gabinete', 'Cable de luz 1+1'],
        ],
        'epp' => [
            ['Casco de seguridad', 'Guantes'],
            ['Chaleco con reflejantes', 'Lentes de Seguridad'],
            ['Botas de seguridad', 'Cinturón de Seguridad'],
        ],
    ],
];
