<?php

function asegurarTablaFormatosMantenimiento(PDO $pdo): void
{
    $pdo->exec("
        CREATE TABLE IF NOT EXISTS formatos_mantenimiento (
            id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            revision_id INTEGER REFERENCES revisiones(id) ON DELETE CASCADE,
            arco_id INTEGER REFERENCES arcos(id) ON DELETE CASCADE,
            tipo VARCHAR(30) NOT NULL,
            datos JSONB NOT NULL DEFAULT '{}'::jsonb,
            creado_por VARCHAR(120),
            created_at TIMESTAMP WITHOUT TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP
        )
    ");
    $pdo->exec("ALTER TABLE formatos_mantenimiento ADD COLUMN IF NOT EXISTS arco_id INTEGER REFERENCES arcos(id) ON DELETE CASCADE");
    $pdo->exec("ALTER TABLE formatos_mantenimiento ALTER COLUMN revision_id DROP NOT NULL");
    $pdo->exec("
        UPDATE formatos_mantenimiento fm
        SET arco_id = r.arco_id
        FROM revisiones r
        WHERE fm.revision_id = r.id AND fm.arco_id IS NULL
    ");
    $pdo->exec("
        CREATE INDEX IF NOT EXISTS idx_formatos_mantenimiento_revision
        ON formatos_mantenimiento (revision_id, created_at DESC)
    ");
    $pdo->exec("
        CREATE INDEX IF NOT EXISTS idx_formatos_mantenimiento_arco
        ON formatos_mantenimiento (arco_id, created_at DESC)
    ");
}
