<?php
/**
 * Esquema y utilidades para infraestructura_nodos y sus enlaces.
 */

function asegurarEsquemaInfraestructura(PDO $pdo): void
{
    static $asegurado = false;
    if ($asegurado) {
        return;
    }

    $pdo->exec("
        CREATE TABLE IF NOT EXISTS infraestructura_enlaces (
            id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            origen_id INTEGER NOT NULL REFERENCES infraestructura_nodos(id) ON DELETE CASCADE,
            destino_id INTEGER NOT NULL REFERENCES infraestructura_nodos(id) ON DELETE CASCADE,
            tipo VARCHAR(50) DEFAULT 'Radioenlace',
            observaciones TEXT,
            created_at TIMESTAMP WITHOUT TIME ZONE DEFAULT CURRENT_TIMESTAMP,
            CONSTRAINT uq_infra_enlace UNIQUE (origen_id, destino_id),
            CONSTRAINT chk_infra_distintos CHECK (origen_id <> destino_id)
        );

        CREATE INDEX IF NOT EXISTS idx_infra_enlaces_origen ON infraestructura_enlaces(origen_id);
        CREATE INDEX IF NOT EXISTS idx_infra_enlaces_destino ON infraestructura_enlaces(destino_id);

        CREATE TABLE IF NOT EXISTS enlace_enlace_relaciones (
            id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            enlace_origen_id INTEGER NOT NULL REFERENCES infraestructura_enlaces(id) ON DELETE CASCADE,
            enlace_destino_id INTEGER NOT NULL REFERENCES infraestructura_enlaces(id) ON DELETE CASCADE,
            tipo VARCHAR(50) DEFAULT 'Salto/Relevo',
            observaciones TEXT,
            created_at TIMESTAMP WITHOUT TIME ZONE DEFAULT CURRENT_TIMESTAMP,
            CONSTRAINT uq_enlace_enlace UNIQUE (enlace_origen_id, enlace_destino_id),
            CONSTRAINT chk_enlace_distintos CHECK (enlace_origen_id <> enlace_destino_id)
        );

        CREATE INDEX IF NOT EXISTS idx_enlace_rel_origen ON enlace_enlace_relaciones(enlace_origen_id);
        CREATE INDEX IF NOT EXISTS idx_enlace_rel_destino ON enlace_enlace_relaciones(enlace_destino_id);
    ");

    $asegurado = true;
}

/**
 * Obtiene todos los enlaces registrados con detalles de origen y destino.
 */
function obtenerTodosEnlaces(PDO $pdo, ?int $ubicacionId = null, ?int $excluirNodoId = null): array
{
    asegurarEsquemaInfraestructura($pdo);

    $sql = "
        SELECT 
            ie.id,
            ie.origen_id,
            no.nombre AS origen_nombre,
            no.tipo AS origen_tipo,
            ie.destino_id,
            nd.nombre AS destino_nombre,
            nd.tipo AS destino_tipo,
            COALESCE(no.ubicacion_id, nd.ubicacion_id) AS ubicacion_id,
            COALESCE(uo.nombre, ud.nombre, 'Sin ubicación') AS ubicacion_nombre,
            ie.tipo AS enlace_tipo,
            CONCAT(no.nombre, ' ⟷ ', nd.nombre) AS enlace_nombre
        FROM infraestructura_enlaces ie
        JOIN infraestructura_nodos no ON no.id = ie.origen_id
        LEFT JOIN ubicaciones uo ON uo.id = no.ubicacion_id
        JOIN infraestructura_nodos nd ON nd.id = ie.destino_id
        LEFT JOIN ubicaciones ud ON ud.id = nd.ubicacion_id
        WHERE 1=1
    ";

    $params = [];
    if ($ubicacionId !== null && $ubicacionId > 0) {
        $sql .= " AND (no.ubicacion_id = :ubi OR nd.ubicacion_id = :ubi)";
        $params['ubi'] = $ubicacionId;
    }
    if ($excluirNodoId !== null && $excluirNodoId > 0) {
        $sql .= " AND ie.origen_id <> :exc AND ie.destino_id <> :exc";
        $params['exc'] = $excluirNodoId;
    }

    $sql .= " ORDER BY ie.id ASC";
    $stmt = $pdo->prepare($sql);
    $stmt->execute($params);
    return $stmt->fetchAll(PDO::FETCH_ASSOC);
}

/**
 * Obtiene los IDs y datos de todos los nodos vinculados (Sitios o Postes) a un nodo de infraestructura dado.
 */
function obtenerEnlacesNodo(PDO $pdo, int $infraId): array
{
    asegurarEsquemaInfraestructura($pdo);

    $stmt = $pdo->prepare("
        SELECT 
            ie.id AS enlace_id,
            ie.tipo AS enlace_tipo,
            ie.observaciones,
            CASE WHEN ie.origen_id = :id THEN nd.id ELSE no.id END AS id,
            CASE WHEN ie.origen_id = :id THEN nd.tipo ELSE no.tipo END AS tipo,
            CASE WHEN ie.origen_id = :id THEN nd.nombre ELSE no.nombre END AS nombre,
            CASE WHEN ie.origen_id = :id THEN nd.ubicacion_id ELSE no.ubicacion_id END AS ubicacion_id,
            CASE WHEN ie.origen_id = :id THEN ud.nombre ELSE uo.nombre END AS ubicacion,
            CASE WHEN ie.origen_id = :id THEN nd.lat ELSE no.lat END AS lat,
            CASE WHEN ie.origen_id = :id THEN nd.lng ELSE no.lng END AS lng
        FROM infraestructura_enlaces ie
        JOIN infraestructura_nodos no ON no.id = ie.origen_id
        LEFT JOIN ubicaciones uo ON uo.id = no.ubicacion_id
        JOIN infraestructura_nodos nd ON nd.id = ie.destino_id
        LEFT JOIN ubicaciones ud ON ud.id = nd.ubicacion_id
        WHERE ie.origen_id = :id OR ie.destino_id = :id
        ORDER BY tipo ASC, nombre ASC
    ");
    $stmt->execute(['id' => $infraId]);
    return $stmt->fetchAll(PDO::FETCH_ASSOC);
}

/**
 * Obtiene los IDs de los enlaces interconectados (enlace con enlace) para un nodo dado.
 */
function obtenerEnlacesConEnlaces(PDO $pdo, int $infraId): array
{
    asegurarEsquemaInfraestructura($pdo);

    $stmtEnl = $pdo->prepare("SELECT id FROM infraestructura_enlaces WHERE origen_id = ? OR destino_id = ?");
    $stmtEnl->execute([$infraId, $infraId]);
    $misEnlacesIds = $stmtEnl->fetchAll(PDO::FETCH_COLUMN);

    if (empty($misEnlacesIds)) {
        return [];
    }

    $inPlaceholder = implode(',', array_fill(0, count($misEnlacesIds), '?'));
    $stmtRel = $pdo->prepare("
        SELECT DISTINCT
            CASE WHEN eer.enlace_origen_id IN ($inPlaceholder) THEN eer.enlace_destino_id ELSE eer.enlace_origen_id END AS enlace_relacionado_id
        FROM enlace_enlace_relaciones eer
        WHERE eer.enlace_origen_id IN ($inPlaceholder) OR eer.enlace_destino_id IN ($inPlaceholder)
    ");
    $params = array_merge($misEnlacesIds, $misEnlacesIds, $misEnlacesIds);
    $stmtRel->execute($params);
    $relIds = $stmtRel->fetchAll(PDO::FETCH_COLUMN);

    return array_values(array_map('intval', $relIds));
}

/**
 * Sincroniza las relaciones enlace con enlace (saltos y relevos de red).
 */
function sincronizarEnlacesConEnlaces(PDO $pdo, int $infraId, array $enlacesDestinoIds): void
{
    asegurarEsquemaInfraestructura($pdo);

    $stmtEnl = $pdo->prepare("SELECT id FROM infraestructura_enlaces WHERE origen_id = ? OR destino_id = ?");
    $stmtEnl->execute([$infraId, $infraId]);
    $misEnlacesIds = $stmtEnl->fetchAll(PDO::FETCH_COLUMN);

    if (empty($misEnlacesIds)) {
        return;
    }

    $inPlaceholder = implode(',', array_fill(0, count($misEnlacesIds), '?'));
    $stmtDel = $pdo->prepare("
        DELETE FROM enlace_enlace_relaciones 
        WHERE enlace_origen_id IN ($inPlaceholder) OR enlace_destino_id IN ($inPlaceholder)
    ");
    $stmtDel->execute(array_merge($misEnlacesIds, $misEnlacesIds));

    $enlacesDestinoIds = array_values(array_unique(array_filter(array_map('intval', $enlacesDestinoIds), function ($id) use ($misEnlacesIds) {
        return $id > 0 && !in_array($id, $misEnlacesIds);
    })));

    if (empty($enlacesDestinoIds)) {
        return;
    }

    $stmtIns = $pdo->prepare("
        INSERT INTO enlace_enlace_relaciones (enlace_origen_id, enlace_destino_id, tipo)
        VALUES (?, ?, 'Salto/Relevo')
        ON CONFLICT (enlace_origen_id, enlace_destino_id) DO NOTHING
    ");

    foreach ($misEnlacesIds as $miEnlaceId) {
        foreach ($enlacesDestinoIds as $destEnlaceId) {
            $origen = min((int)$miEnlaceId, (int)$destEnlaceId);
            $destino = max((int)$miEnlaceId, (int)$destEnlaceId);
            $stmtIns->execute([$origen, $destino]);
        }
    }
}

/**
 * Sincroniza los enlaces bidireccionales de un nodo de infraestructura con una lista de nodos destino.
 */
function sincronizarEnlacesNodo(PDO $pdo, int $infraId, array $nodosDestinoIds): void
{
    asegurarEsquemaInfraestructura($pdo);

    // Filtrar IDs válidos y excluir el propio nodo
    $nodosDestinoIds = array_values(array_unique(array_filter(array_map('intval', $nodosDestinoIds), function ($destId) use ($infraId) {
        return $destId > 0 && $destId !== $infraId;
    })));

    // Eliminar enlaces existentes donde participe este nodo
    $stmtDel = $pdo->prepare("DELETE FROM infraestructura_enlaces WHERE origen_id = ? OR destino_id = ?");
    $stmtDel->execute([$infraId, $infraId]);

    if (empty($nodosDestinoIds)) {
        return;
    }

    // Insertar enlaces garantizando una sola dirección canónica (menor ID -> mayor ID)
    $stmtInsert = $pdo->prepare("
        INSERT INTO infraestructura_enlaces (origen_id, destino_id, tipo)
        VALUES (?, ?, 'Radioenlace')
        ON CONFLICT (origen_id, destino_id) DO NOTHING
    ");

    foreach ($nodosDestinoIds as $destId) {
        $origen = min($infraId, $destId);
        $destino = max($infraId, $destId);
        $stmtInsert->execute([$origen, $destino]);
    }
}
