<?php

function asegurarRelacionTecnicos(PDO $pdo): void
{
    $pdo->exec("
        CREATE TABLE IF NOT EXISTS tecnicos (
            id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            nombre VARCHAR(150) NOT NULL UNIQUE,
            telefono VARCHAR(30),
            puesto VARCHAR(80),
            activo INTEGER NOT NULL DEFAULT 1,
            eliminado INTEGER NOT NULL DEFAULT 0,
            created_at TIMESTAMP WITHOUT TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP
        )
    ");

    $pdo->exec("ALTER TABLE tecnicos ADD COLUMN IF NOT EXISTS eliminado INTEGER NOT NULL DEFAULT 0");
    $pdo->exec("CREATE INDEX IF NOT EXISTS idx_tecnicos_activo ON tecnicos (activo)");

    $columnExists = static function (string $tabla, string $columna) use ($pdo): bool {
        $stmt = $pdo->prepare("
            SELECT 1
            FROM information_schema.columns
            WHERE table_schema = 'public'
              AND table_name = ?
              AND column_name = ?
        ");
        $stmt->execute([$tabla, $columna]);
        return (bool)$stmt->fetchColumn();
    };

    if ($columnExists('tecnicos', 'usuario_id')) {
        $pdo->exec("
            UPDATE tecnicos
            SET activo = 0,
                eliminado = 1
            WHERE usuario_id IS NOT NULL
              AND COALESCE(eliminado, 0) = 0
        ");
        $pdo->exec(<<<'SQL'
            DO $$
            BEGIN
                IF EXISTS (
                    SELECT 1
                    FROM pg_constraint
                    WHERE conname = 'fk_tecnicos_usuario'
                ) THEN
                    ALTER TABLE tecnicos
                    DROP CONSTRAINT fk_tecnicos_usuario;
                END IF;
            END $$;
SQL);
        $pdo->exec("DROP INDEX IF EXISTS idx_tecnicos_usuario_id_unique");
        $pdo->exec("ALTER TABLE tecnicos DROP COLUMN IF EXISTS usuario_id");
    }

    $fuentes = [
        ['revisiones', 'tecnico_responsable'],
        ['infraestructura_revisiones', 'tecnico_responsable'],
        ['bitacoras_arco', 'encargado'],
        ['arcos_bajas', 'tecnico_responsable'],
    ];

    foreach ($fuentes as [$tabla, $columna]) {
        if (!$columnExists($tabla, $columna)) {
            continue;
        }

        $pdo->exec("
            INSERT INTO tecnicos (nombre)
            SELECT DISTINCT TRIM({$columna})
            FROM {$tabla}
            WHERE {$columna} IS NOT NULL AND TRIM({$columna}) <> ''
            ON CONFLICT (nombre) DO NOTHING
        ");
    }

    $pdo->exec("
        CREATE TABLE IF NOT EXISTS formatos_mantenimiento (
            id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            revision_id INTEGER REFERENCES revisiones(id) ON DELETE CASCADE,
            arco_id INTEGER REFERENCES arcos(id) ON DELETE CASCADE,
            tipo VARCHAR(30) NOT NULL,
            datos JSONB NOT NULL DEFAULT '{}'::jsonb,
            creado_por VARCHAR(120),
            created_at TIMESTAMP WITHOUT TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP
        )
    ");

    $tablasRelacion = [
        'revisiones',
        'infraestructura_revisiones',
        'bitacoras_arco',
        'arcos_bajas',
        'formatos_mantenimiento',
    ];

    foreach ($tablasRelacion as $tabla) {
        $pdo->exec("ALTER TABLE {$tabla} ADD COLUMN IF NOT EXISTS tecnico_id INTEGER");
        $pdo->exec("CREATE INDEX IF NOT EXISTS idx_{$tabla}_tecnico_id ON {$tabla} (tecnico_id)");
    }

    if ($columnExists('revisiones', 'tecnico_responsable')) {
        $pdo->exec("
            UPDATE revisiones r
            SET tecnico_id = t.id
            FROM tecnicos t
            WHERE r.tecnico_id IS NULL
              AND r.tecnico_responsable IS NOT NULL
              AND TRIM(r.tecnico_responsable) = t.nombre
        ");
    }

    if ($columnExists('infraestructura_revisiones', 'tecnico_responsable')) {
        $pdo->exec("
            UPDATE infraestructura_revisiones ir
            SET tecnico_id = t.id
            FROM tecnicos t
            WHERE ir.tecnico_id IS NULL
              AND ir.tecnico_responsable IS NOT NULL
              AND TRIM(ir.tecnico_responsable) = t.nombre
        ");
    }

    if ($columnExists('bitacoras_arco', 'encargado')) {
        $pdo->exec("
            UPDATE bitacoras_arco b
            SET tecnico_id = t.id
            FROM tecnicos t
            WHERE b.tecnico_id IS NULL
              AND b.encargado IS NOT NULL
              AND TRIM(b.encargado) = t.nombre
        ");
    }

    if ($columnExists('arcos_bajas', 'tecnico_responsable')) {
        $pdo->exec("
            UPDATE arcos_bajas b
            SET tecnico_id = t.id
            FROM tecnicos t
            WHERE b.tecnico_id IS NULL
              AND b.tecnico_responsable IS NOT NULL
              AND TRIM(b.tecnico_responsable) = t.nombre
        ");
    }

    $pdo->exec(<<<'SQL'
        DO $$
        BEGIN
            IF NOT EXISTS (
                SELECT 1
                FROM pg_constraint
                WHERE conname = 'fk_revisiones_tecnico'
            ) THEN
                ALTER TABLE revisiones
                ADD CONSTRAINT fk_revisiones_tecnico
                FOREIGN KEY (tecnico_id) REFERENCES tecnicos(id) ON DELETE SET NULL;
            END IF;

            IF NOT EXISTS (
                SELECT 1
                FROM pg_constraint
                WHERE conname = 'fk_infra_revisiones_tecnico'
            ) THEN
                ALTER TABLE infraestructura_revisiones
                ADD CONSTRAINT fk_infra_revisiones_tecnico
                FOREIGN KEY (tecnico_id) REFERENCES tecnicos(id) ON DELETE SET NULL;
            END IF;

            IF NOT EXISTS (
                SELECT 1
                FROM pg_constraint
                WHERE conname = 'fk_bitacoras_arco_tecnico'
            ) THEN
                ALTER TABLE bitacoras_arco
                ADD CONSTRAINT fk_bitacoras_arco_tecnico
                FOREIGN KEY (tecnico_id) REFERENCES tecnicos(id) ON DELETE SET NULL;
            END IF;

            IF NOT EXISTS (
                SELECT 1
                FROM pg_constraint
                WHERE conname = 'fk_arcos_bajas_tecnico'
            ) THEN
                ALTER TABLE arcos_bajas
                ADD CONSTRAINT fk_arcos_bajas_tecnico
                FOREIGN KEY (tecnico_id) REFERENCES tecnicos(id) ON DELETE SET NULL;
            END IF;

            IF NOT EXISTS (
                SELECT 1
                FROM pg_constraint
                WHERE conname = 'fk_formatos_mantenimiento_tecnico'
            ) THEN
                ALTER TABLE formatos_mantenimiento
                ADD CONSTRAINT fk_formatos_mantenimiento_tecnico
                FOREIGN KEY (tecnico_id) REFERENCES tecnicos(id) ON DELETE SET NULL;
            END IF;
        END $$;
SQL);
}

function obtenerTecnicoPorId(PDO $pdo, int $tecnicoId): ?array
{
    if ($tecnicoId <= 0) {
        return null;
    }

    $stmt = $pdo->prepare("
        SELECT id, nombre
        FROM tecnicos
        WHERE id = ? AND activo = 1 AND COALESCE(eliminado, 0) = 0
    ");
    $stmt->execute([$tecnicoId]);
    $tecnico = $stmt->fetch(PDO::FETCH_ASSOC);

    return $tecnico ?: null;
}
