-- Conversion MySQL a PostgreSQL para Panel REPuve
-- Generado: 2026-07-13 03:22:59
-- Origen MySQL: repuve_db

BEGIN;

-- Estructura PostgreSQL
-- Esquema PostgreSQL para Panel REPuve Mantenimientos
-- Ejecutar dentro de la base de datos remota ya creada.

CREATE TABLE IF NOT EXISTS users (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    username VARCHAR(100) NOT NULL UNIQUE,
    password VARCHAR(255) NOT NULL,
    role VARCHAR(30) NOT NULL DEFAULT 'user',
    created_at TIMESTAMP WITHOUT TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS ubicaciones (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre VARCHAR(120) NOT NULL UNIQUE,
    lat VARCHAR(50),
    lng VARCHAR(50)
);

CREATE TABLE IF NOT EXISTS materiales (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre VARCHAR(150) NOT NULL,
    medida VARCHAR(30) NOT NULL DEFAULT 'pz',
    foto VARCHAR(255),
    serie VARCHAR(120)
);

CREATE TABLE IF NOT EXISTS tecnicos (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre VARCHAR(150) NOT NULL UNIQUE,
    telefono VARCHAR(30),
    puesto VARCHAR(80),
    activo INTEGER NOT NULL DEFAULT 1,
    eliminado INTEGER NOT NULL DEFAULT 0,
    created_at TIMESTAMP WITHOUT TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP
);

ALTER TABLE tecnicos ADD COLUMN IF NOT EXISTS eliminado INTEGER NOT NULL DEFAULT 0;

CREATE TABLE IF NOT EXISTS arcos (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre VARCHAR(150) NOT NULL UNIQUE,
    ubicacion_id INTEGER NOT NULL REFERENCES ubicaciones(id) ON DELETE RESTRICT,
    fecha_instalacion TIMESTAMP WITHOUT TIME ZONE,
    lat VARCHAR(50),
    lng VARCHAR(50),
    estado VARCHAR(20) NOT NULL DEFAULT 'Activo',
    fecha_baja TIMESTAMP WITHOUT TIME ZONE
);

ALTER TABLE arcos ADD COLUMN IF NOT EXISTS estado VARCHAR(20) NOT NULL DEFAULT 'Activo';
ALTER TABLE arcos ADD COLUMN IF NOT EXISTS fecha_baja TIMESTAMP WITHOUT TIME ZONE;

CREATE TABLE IF NOT EXISTS arco_material (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    arco_id INTEGER NOT NULL REFERENCES arcos(id) ON DELETE CASCADE,
    material_id INTEGER NOT NULL REFERENCES materiales(id) ON DELETE RESTRICT,
    cantidad NUMERIC(12, 2) NOT NULL DEFAULT 1,
    foto VARCHAR(255),
    serie VARCHAR(120),
    creado_at TIMESTAMP WITHOUT TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS revisiones (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    arco_id INTEGER NOT NULL REFERENCES arcos(id) ON DELETE CASCADE,
    fecha_mantenimiento TIMESTAMP WITHOUT TIME ZONE NOT NULL,
    tipo_mantenimiento VARCHAR(20) NOT NULL DEFAULT 'Correctivo',
    observaciones TEXT,
    tecnico_id INTEGER REFERENCES tecnicos(id) ON DELETE SET NULL
);

ALTER TABLE revisiones ADD COLUMN IF NOT EXISTS tecnico_id INTEGER REFERENCES tecnicos(id) ON DELETE SET NULL;

CREATE TABLE IF NOT EXISTS revision_material (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    revision_id INTEGER NOT NULL REFERENCES revisiones(id) ON DELETE CASCADE,
    arco_material_id INTEGER REFERENCES arco_material(id) ON DELETE SET NULL,
    material_id INTEGER NOT NULL REFERENCES materiales(id) ON DELETE RESTRICT,
    cantidad NUMERIC(12, 2) NOT NULL DEFAULT 1,
    foto VARCHAR(255),
    serie VARCHAR(120),
    accion VARCHAR(20) NOT NULL DEFAULT 'cambio'
);

CREATE TABLE IF NOT EXISTS revision_evidencias (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    revision_id INTEGER NOT NULL REFERENCES revisiones(id) ON DELETE CASCADE,
    filename VARCHAR(255) NOT NULL,
    mimetype VARCHAR(100),
    created_at TIMESTAMP WITHOUT TIME ZONE,
    uploaded_at TIMESTAMP WITHOUT TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS formatos_mantenimiento (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    revision_id INTEGER REFERENCES revisiones(id) ON DELETE CASCADE,
    arco_id INTEGER REFERENCES arcos(id) ON DELETE CASCADE,
    tipo VARCHAR(30) NOT NULL,
    datos JSONB NOT NULL DEFAULT '{}'::jsonb,
    tecnico_id INTEGER REFERENCES tecnicos(id) ON DELETE SET NULL,
    creado_por VARCHAR(120),
    created_at TIMESTAMP WITHOUT TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP
);

ALTER TABLE formatos_mantenimiento ADD COLUMN IF NOT EXISTS tecnico_id INTEGER REFERENCES tecnicos(id) ON DELETE SET NULL;

CREATE TABLE IF NOT EXISTS arcos_bajas (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    arco_id INTEGER NOT NULL REFERENCES arcos(id) ON DELETE CASCADE,
    fecha_baja TIMESTAMP WITHOUT TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    motivo VARCHAR(180) NOT NULL,
    tecnico_id INTEGER REFERENCES tecnicos(id) ON DELETE SET NULL,
    observaciones TEXT,
    created_at TIMESTAMP WITHOUT TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP
);

ALTER TABLE arcos_bajas ADD COLUMN IF NOT EXISTS tecnico_id INTEGER REFERENCES tecnicos(id) ON DELETE SET NULL;

CREATE TABLE IF NOT EXISTS arcos_bajas_evidencias (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    baja_id INTEGER NOT NULL REFERENCES arcos_bajas(id) ON DELETE CASCADE,
    filename VARCHAR(255) NOT NULL,
    mimetype VARCHAR(100),
    uploaded_at TIMESTAMP WITHOUT TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS infraestructura_nodos (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tipo VARCHAR(40) NOT NULL DEFAULT 'Puente/Poste',
    nombre VARCHAR(150) NOT NULL,
    ubicacion_id INTEGER REFERENCES ubicaciones(id) ON DELETE SET NULL,
    lat VARCHAR(50),
    lng VARCHAR(50),
    descripcion TEXT,
    created_at TIMESTAMP WITHOUT TIME ZONE,
    creado_at TIMESTAMP WITHOUT TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    UNIQUE (tipo, nombre)
);

CREATE TABLE IF NOT EXISTS arco_infraestructura (
    id INTEGER,
    arco_id INTEGER NOT NULL REFERENCES arcos(id) ON DELETE CASCADE,
    infraestructura_id INTEGER NOT NULL REFERENCES infraestructura_nodos(id) ON DELETE CASCADE,
    created_at TIMESTAMP WITHOUT TIME ZONE,
    PRIMARY KEY (arco_id, infraestructura_id)
);

ALTER TABLE arco_infraestructura ADD COLUMN IF NOT EXISTS created_at TIMESTAMP WITHOUT TIME ZONE;

CREATE TABLE IF NOT EXISTS infraestructura_material (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    infraestructura_id INTEGER NOT NULL REFERENCES infraestructura_nodos(id) ON DELETE CASCADE,
    material_id INTEGER NOT NULL REFERENCES materiales(id) ON DELETE RESTRICT,
    cantidad NUMERIC(12, 2) NOT NULL DEFAULT 1,
    serie VARCHAR(120),
    fecha_instalacion TIMESTAMP WITHOUT TIME ZONE
);

CREATE TABLE IF NOT EXISTS infraestructura_revisiones (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    infraestructura_id INTEGER NOT NULL REFERENCES infraestructura_nodos(id) ON DELETE CASCADE,
    fecha_mantenimiento TIMESTAMP WITHOUT TIME ZONE NOT NULL,
    tipo_mantenimiento VARCHAR(20) NOT NULL DEFAULT 'Correctivo',
    observaciones TEXT,
    tecnico_id INTEGER REFERENCES tecnicos(id) ON DELETE SET NULL,
    created_at TIMESTAMP WITHOUT TIME ZONE
);

ALTER TABLE infraestructura_revisiones ADD COLUMN IF NOT EXISTS tecnico_id INTEGER REFERENCES tecnicos(id) ON DELETE SET NULL;

CREATE TABLE IF NOT EXISTS infraestructura_revision_material (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    revision_id INTEGER NOT NULL REFERENCES infraestructura_revisiones(id) ON DELETE CASCADE,
    material_id INTEGER NOT NULL REFERENCES materiales(id) ON DELETE RESTRICT,
    cantidad NUMERIC(12, 2) NOT NULL DEFAULT 1,
    serie VARCHAR(120)
);

CREATE TABLE IF NOT EXISTS infraestructura_revision_evidencias (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    revision_id INTEGER NOT NULL REFERENCES infraestructura_revisiones(id) ON DELETE CASCADE,
    filename VARCHAR(255) NOT NULL,
    mimetype VARCHAR(100),
    uploaded_at TIMESTAMP WITHOUT TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS bitacoras_arco (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    arco_id INTEGER NOT NULL REFERENCES arcos(id) ON DELETE CASCADE,
    tecnico_id INTEGER REFERENCES tecnicos(id) ON DELETE SET NULL,
    observaciones TEXT,
    fecha_registro TIMESTAMP WITHOUT TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP
);

ALTER TABLE bitacoras_arco ADD COLUMN IF NOT EXISTS tecnico_id INTEGER REFERENCES tecnicos(id) ON DELETE SET NULL;

CREATE TABLE IF NOT EXISTS checklist_conceptos (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre VARCHAR(255) NOT NULL,
    activo INTEGER NOT NULL DEFAULT 1
);

CREATE TABLE IF NOT EXISTS bitacora_checklist (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    bitacora_id INTEGER NOT NULL REFERENCES bitacoras_arco(id) ON DELETE CASCADE,
    concepto_id INTEGER NOT NULL REFERENCES checklist_conceptos(id) ON DELETE RESTRICT,
    realizado INTEGER NOT NULL DEFAULT 1,
    UNIQUE (bitacora_id, concepto_id)
);

CREATE INDEX IF NOT EXISTS idx_arcos_ubicacion_id ON arcos (ubicacion_id);
CREATE INDEX IF NOT EXISTS idx_tecnicos_activo ON tecnicos (activo);
CREATE INDEX IF NOT EXISTS idx_arco_material_arco_id ON arco_material (arco_id);
CREATE INDEX IF NOT EXISTS idx_arco_material_material_id ON arco_material (material_id);
CREATE INDEX IF NOT EXISTS idx_revisiones_arco_id ON revisiones (arco_id);
CREATE INDEX IF NOT EXISTS idx_revisiones_tecnico_id ON revisiones (tecnico_id);
CREATE INDEX IF NOT EXISTS idx_revisiones_fecha ON revisiones (fecha_mantenimiento);
CREATE INDEX IF NOT EXISTS idx_revisiones_arco_fecha ON revisiones (arco_id, fecha_mantenimiento DESC);
CREATE INDEX IF NOT EXISTS idx_revision_material_revision_id ON revision_material (revision_id);
CREATE INDEX IF NOT EXISTS idx_revision_material_arco_material_id ON revision_material (arco_material_id);
CREATE INDEX IF NOT EXISTS idx_revision_evidencias_revision_id ON revision_evidencias (revision_id);
CREATE INDEX IF NOT EXISTS idx_formatos_mantenimiento_revision ON formatos_mantenimiento (revision_id, created_at DESC);
CREATE INDEX IF NOT EXISTS idx_formatos_mantenimiento_arco ON formatos_mantenimiento (arco_id, created_at DESC);
CREATE INDEX IF NOT EXISTS idx_formatos_mantenimiento_tecnico_id ON formatos_mantenimiento (tecnico_id);
CREATE INDEX IF NOT EXISTS idx_arcos_estado ON arcos (estado);
CREATE INDEX IF NOT EXISTS idx_arcos_bajas_arco_id ON arcos_bajas (arco_id);
CREATE INDEX IF NOT EXISTS idx_arcos_bajas_tecnico_id ON arcos_bajas (tecnico_id);
CREATE INDEX IF NOT EXISTS idx_arcos_bajas_fecha ON arcos_bajas (fecha_baja);
CREATE INDEX IF NOT EXISTS idx_arcos_bajas_evidencias_baja_id ON arcos_bajas_evidencias (baja_id);
CREATE INDEX IF NOT EXISTS idx_infraestructura_nodos_ubicacion_id ON infraestructura_nodos (ubicacion_id);
CREATE INDEX IF NOT EXISTS idx_infraestructura_material_infra_id ON infraestructura_material (infraestructura_id);
CREATE INDEX IF NOT EXISTS idx_infraestructura_revisiones_infra_id ON infraestructura_revisiones (infraestructura_id);
CREATE INDEX IF NOT EXISTS idx_infraestructura_revisiones_tecnico_id ON infraestructura_revisiones (tecnico_id);
CREATE INDEX IF NOT EXISTS idx_infra_revisiones_infra_fecha ON infraestructura_revisiones (infraestructura_id, fecha_mantenimiento DESC);
CREATE INDEX IF NOT EXISTS idx_infra_revision_material_revision_id ON infraestructura_revision_material (revision_id);
CREATE INDEX IF NOT EXISTS idx_infra_revision_evidencias_revision_id ON infraestructura_revision_evidencias (revision_id);
CREATE INDEX IF NOT EXISTS idx_bitacoras_arco_id ON bitacoras_arco (arco_id);
CREATE INDEX IF NOT EXISTS idx_bitacoras_arco_tecnico_id ON bitacoras_arco (tecnico_id);
CREATE INDEX IF NOT EXISTS idx_bitacoras_arco_fecha ON bitacoras_arco (arco_id, fecha_registro DESC);


-- Limpieza de tablas importadas
TRUNCATE TABLE "bitacora_checklist", "checklist_conceptos", "bitacoras_arco", "infraestructura_revision_evidencias", "infraestructura_revision_material", "infraestructura_revisiones", "infraestructura_material", "arco_infraestructura", "infraestructura_nodos", "revision_evidencias", "revision_material", "revisiones", "arco_material", "arcos", "tecnicos", "materiales", "ubicaciones", "users" RESTART IDENTITY CASCADE;

-- Datos convertidos
-- users: 1 registro(s)
INSERT INTO "users" ("id", "username", "password", "role") VALUES ('3', 'jlromero', '$2y$10$CXwyF7DhaIufmCM6HOGqNeet4lRAkugpdXrdMfivyyIV6.FmUY9a2', 'admin');

-- ubicaciones: 8 registro(s)
INSERT INTO "ubicaciones" ("id", "nombre", "lat", "lng") VALUES ('3', 'Chilpancingo', '17.460713', '-99.497681');
INSERT INTO "ubicaciones" ("id", "nombre", "lat", "lng") VALUES ('4', 'Acapulco', '16.851862', '-99.821777');
INSERT INTO "ubicaciones" ("id", "nombre", "lat", "lng") VALUES ('5', 'Taxco', NULL, NULL);
INSERT INTO "ubicaciones" ("id", "nombre", "lat", "lng") VALUES ('6', 'Iguala', NULL, NULL);
INSERT INTO "ubicaciones" ("id", "nombre", "lat", "lng") VALUES ('7', 'Zihuatanejo', NULL, NULL);
INSERT INTO "ubicaciones" ("id", "nombre", "lat", "lng") VALUES ('8', 'San Marcos', NULL, NULL);
INSERT INTO "ubicaciones" ("id", "nombre", "lat", "lng") VALUES ('9', 'Ometepec', NULL, NULL);
INSERT INTO "ubicaciones" ("id", "nombre", "lat", "lng") VALUES ('10', 'Coyuca', '17.007186', '-100084279');

-- materiales: 25 registro(s)
INSERT INTO "materiales" ("id", "nombre", "medida", "foto", "serie") VALUES ('7', 'Camara LPR', 'pz', '1764729971_camara lpr.png', NULL);
INSERT INTO "materiales" ("id", "nombre", "medida", "foto", "serie") VALUES ('8', 'Enlace Ubiquiti M5', 'pz', '1779659842_Enlace Ubiquiti M5.png', NULL);
INSERT INTO "materiales" ("id", "nombre", "medida", "foto", "serie") VALUES ('9', 'Switch 5 Puertos Controntolador Solar Wiltek', 'pz', '1764729996_switch 5 puertos panel solar.png', NULL);
INSERT INTO "materiales" ("id", "nombre", "medida", "foto", "serie") VALUES ('10', 'SpeedWay 4 Conectores', 'pz', '1764730013_speedway.jpg', NULL);
INSERT INTO "materiales" ("id", "nombre", "medida", "foto", "serie") VALUES ('11', 'Antena Yagi RFID 5 Elementos', 'pz', '1780038784_Antena Yagi de 5 Elementos.png', NULL);
INSERT INTO "materiales" ("id", "nombre", "medida", "foto", "serie") VALUES ('12', 'Panel Solar Epcom 19V 150W', 'pz', '1764730052_PANEL SOLAR.PNG', NULL);
INSERT INTO "materiales" ("id", "nombre", "medida", "foto", "serie") VALUES ('13', 'Bateria Solar', 'pz', '1764730062_bateria.png', NULL);
INSERT INTO "materiales" ("id", "nombre", "medida", "foto", "serie") VALUES ('14', 'Cable FotoVoltaico Positivo', 'm', '1764730460_cable fotovoltaico positivo.png', NULL);
INSERT INTO "materiales" ("id", "nombre", "medida", "foto", "serie") VALUES ('15', 'Cable FotoVoltaico Negativo', 'm', '1764730481_cable fotovoltaico negativo.png', NULL);
INSERT INTO "materiales" ("id", "nombre", "medida", "foto", "serie") VALUES ('16', 'Cable TNC', 'm', '1764731117_Cable TNC.png', NULL);
INSERT INTO "materiales" ("id", "nombre", "medida", "foto", "serie") VALUES ('17', 'Gabinete Doble Cerradura', 'pz', '1772599896_Gabinete doble Cerradura.jpg', NULL);
INSERT INTO "materiales" ("id", "nombre", "medida", "foto", "serie") VALUES ('18', 'Cable 1+1', 'm', '1772600756_cable 1+1.jpg', NULL);
INSERT INTO "materiales" ("id", "nombre", "medida", "foto", "serie") VALUES ('19', 'Gabinete 1 nivel', 'pz', '1779087212_gabinete 1 nivel.png', NULL);
INSERT INTO "materiales" ("id", "nombre", "medida", "foto", "serie") VALUES ('20', 'Gabinete con soporte en forma L', 'pz', '1779658323_Gabinete con soporte en forma de L.jpg', NULL);
INSERT INTO "materiales" ("id", "nombre", "medida", "foto", "serie") VALUES ('21', 'Enlace Ubiquiti AC', 'pz', '1779659869_Enlace Ubiquiti AC.png', NULL);
INSERT INTO "materiales" ("id", "nombre", "medida", "foto", "serie") VALUES ('22', 'Switch 8 Puetos Controlador Solar Wiltek', 'pz', '1779659937_switch 8 puertos.jpg', NULL);
INSERT INTO "materiales" ("id", "nombre", "medida", "foto", "serie") VALUES ('23', 'Switch 16 Puertos Wiltek', 'pz', '1779659957_switch 16 puertos.png', NULL);
INSERT INTO "materiales" ("id", "nombre", "medida", "foto", "serie") VALUES ('24', 'Switch 5 Puertos TP Link', 'pz', '1779661807_switch 5 puertos TP Link.jpg', NULL);
INSERT INTO "materiales" ("id", "nombre", "medida", "foto", "serie") VALUES ('25', 'Controlador Solar POE', 'pz', '1779663102_Controlador Solar POE.png', NULL);
INSERT INTO "materiales" ("id", "nombre", "medida", "foto", "serie") VALUES ('26', 'SpeedWay 2 Conectores', 'pz', '1779663580_Speedway 2 Conectores .jpg', NULL);
INSERT INTO "materiales" ("id", "nombre", "medida", "foto", "serie") VALUES ('27', 'Switch 24 Puertos cisco', 'pz', '1780024851_switch 24 puertos cisco.jpg', NULL);
INSERT INTO "materiales" ("id", "nombre", "medida", "foto", "serie") VALUES ('28', 'Swich 5 puertos HikVision', 'pz', '1780203061_switch 5 puertos Hikvision.jpg', NULL);
INSERT INTO "materiales" ("id", "nombre", "medida", "foto", "serie") VALUES ('29', 'Enlace Ubiquiti AC ISO', 'pz', '1780217319_enlace Ubiquiti AC ISO.png', NULL);
INSERT INTO "materiales" ("id", "nombre", "medida", "foto", "serie") VALUES ('30', 'UTP Cat 5e Exterior', 'm', '1780217657_Cable UTP Cat 5e Exterior.png', NULL);
INSERT INTO "materiales" ("id", "nombre", "medida", "foto", "serie") VALUES ('31', 'Cambium Force 300', 'pz', '1780271136_Enlace Cambium force 300.png', NULL);

