-- Conversion MySQL a PostgreSQL para Panel REPuve
-- Generado: 2026-07-11 07:30:25
-- Origen MySQL: repuve_db

BEGIN;

-- Estructura PostgreSQL
-- Esquema PostgreSQL para Panel REPuve Mantenimientos
-- Ejecutar dentro de la base de datos remota ya creada.

CREATE TABLE IF NOT EXISTS users (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    username VARCHAR(100) NOT NULL UNIQUE,
    password VARCHAR(255) NOT NULL,
    role VARCHAR(30) NOT NULL DEFAULT 'user',
    created_at TIMESTAMP WITHOUT TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS ubicaciones (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre VARCHAR(120) NOT NULL UNIQUE,
    lat VARCHAR(50),
    lng VARCHAR(50)
);

CREATE TABLE IF NOT EXISTS materiales (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre VARCHAR(150) NOT NULL,
    medida VARCHAR(30) NOT NULL DEFAULT 'pz',
    foto VARCHAR(255),
    serie VARCHAR(120)
);

CREATE TABLE IF NOT EXISTS tecnicos (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre VARCHAR(150) NOT NULL UNIQUE,
    telefono VARCHAR(30),
    puesto VARCHAR(80),
    activo INTEGER NOT NULL DEFAULT 1,
    eliminado INTEGER NOT NULL DEFAULT 0,
    created_at TIMESTAMP WITHOUT TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP
);

ALTER TABLE tecnicos ADD COLUMN IF NOT EXISTS eliminado INTEGER NOT NULL DEFAULT 0;

CREATE TABLE IF NOT EXISTS arcos (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre VARCHAR(150) NOT NULL UNIQUE,
    ubicacion_id INTEGER NOT NULL REFERENCES ubicaciones(id) ON DELETE RESTRICT,
    fecha_instalacion TIMESTAMP WITHOUT TIME ZONE,
    lat VARCHAR(50),
    lng VARCHAR(50),
    estado VARCHAR(20) NOT NULL DEFAULT 'Activo',
    fecha_baja TIMESTAMP WITHOUT TIME ZONE
);

ALTER TABLE arcos ADD COLUMN IF NOT EXISTS estado VARCHAR(20) NOT NULL DEFAULT 'Activo';
ALTER TABLE arcos ADD COLUMN IF NOT EXISTS fecha_baja TIMESTAMP WITHOUT TIME ZONE;

CREATE TABLE IF NOT EXISTS arco_material (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    arco_id INTEGER NOT NULL REFERENCES arcos(id) ON DELETE CASCADE,
    material_id INTEGER NOT NULL REFERENCES materiales(id) ON DELETE RESTRICT,
    cantidad NUMERIC(12, 2) NOT NULL DEFAULT 1,
    foto VARCHAR(255),
    serie VARCHAR(120),
    creado_at TIMESTAMP WITHOUT TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS revisiones (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    arco_id INTEGER NOT NULL REFERENCES arcos(id) ON DELETE CASCADE,
    fecha_mantenimiento TIMESTAMP WITHOUT TIME ZONE NOT NULL,
    tipo_mantenimiento VARCHAR(20) NOT NULL DEFAULT 'Correctivo',
    observaciones TEXT,
    tecnico_responsable VARCHAR(150)
);

CREATE TABLE IF NOT EXISTS revision_material (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    revision_id INTEGER NOT NULL REFERENCES revisiones(id) ON DELETE CASCADE,
    arco_material_id INTEGER REFERENCES arco_material(id) ON DELETE SET NULL,
    material_id INTEGER NOT NULL REFERENCES materiales(id) ON DELETE RESTRICT,
    cantidad NUMERIC(12, 2) NOT NULL DEFAULT 1,
    foto VARCHAR(255),
    serie VARCHAR(120),
    accion VARCHAR(20) NOT NULL DEFAULT 'cambio'
);

CREATE TABLE IF NOT EXISTS revision_evidencias (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    revision_id INTEGER NOT NULL REFERENCES revisiones(id) ON DELETE CASCADE,
    filename VARCHAR(255) NOT NULL,
    mimetype VARCHAR(100),
    created_at TIMESTAMP WITHOUT TIME ZONE,
    uploaded_at TIMESTAMP WITHOUT TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS formatos_mantenimiento (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    revision_id INTEGER REFERENCES revisiones(id) ON DELETE CASCADE,
    arco_id INTEGER REFERENCES arcos(id) ON DELETE CASCADE,
    tipo VARCHAR(30) NOT NULL,
    datos JSONB NOT NULL DEFAULT '{}'::jsonb,
    creado_por VARCHAR(120),
    created_at TIMESTAMP WITHOUT TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS arcos_bajas (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    arco_id INTEGER NOT NULL REFERENCES arcos(id) ON DELETE CASCADE,
    fecha_baja TIMESTAMP WITHOUT TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    motivo VARCHAR(180) NOT NULL,
    tecnico_responsable VARCHAR(150),
    observaciones TEXT,
    created_at TIMESTAMP WITHOUT TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS arcos_bajas_evidencias (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    baja_id INTEGER NOT NULL REFERENCES arcos_bajas(id) ON DELETE CASCADE,
    filename VARCHAR(255) NOT NULL,
    mimetype VARCHAR(100),
    uploaded_at TIMESTAMP WITHOUT TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS infraestructura_nodos (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tipo VARCHAR(40) NOT NULL DEFAULT 'Puente/Poste',
    nombre VARCHAR(150) NOT NULL,
    ubicacion_id INTEGER REFERENCES ubicaciones(id) ON DELETE SET NULL,
    lat VARCHAR(50),
    lng VARCHAR(50),
    descripcion TEXT,
    created_at TIMESTAMP WITHOUT TIME ZONE,
    creado_at TIMESTAMP WITHOUT TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    UNIQUE (tipo, nombre)
);

CREATE TABLE IF NOT EXISTS arco_infraestructura (
    id INTEGER,
    arco_id INTEGER NOT NULL REFERENCES arcos(id) ON DELETE CASCADE,
    infraestructura_id INTEGER NOT NULL REFERENCES infraestructura_nodos(id) ON DELETE CASCADE,
    created_at TIMESTAMP WITHOUT TIME ZONE,
    PRIMARY KEY (arco_id, infraestructura_id)
);

ALTER TABLE arco_infraestructura ADD COLUMN IF NOT EXISTS created_at TIMESTAMP WITHOUT TIME ZONE;

CREATE TABLE IF NOT EXISTS infraestructura_material (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    infraestructura_id INTEGER NOT NULL REFERENCES infraestructura_nodos(id) ON DELETE CASCADE,
    material_id INTEGER NOT NULL REFERENCES materiales(id) ON DELETE RESTRICT,
    cantidad NUMERIC(12, 2) NOT NULL DEFAULT 1,
    serie VARCHAR(120),
    fecha_instalacion TIMESTAMP WITHOUT TIME ZONE
);

CREATE TABLE IF NOT EXISTS infraestructura_revisiones (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    infraestructura_id INTEGER NOT NULL REFERENCES infraestructura_nodos(id) ON DELETE CASCADE,
    fecha_mantenimiento TIMESTAMP WITHOUT TIME ZONE NOT NULL,
    tipo_mantenimiento VARCHAR(20) NOT NULL DEFAULT 'Correctivo',
    observaciones TEXT,
    tecnico_responsable VARCHAR(150),
    created_at TIMESTAMP WITHOUT TIME ZONE
);

CREATE TABLE IF NOT EXISTS infraestructura_revision_material (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    revision_id INTEGER NOT NULL REFERENCES infraestructura_revisiones(id) ON DELETE CASCADE,
    material_id INTEGER NOT NULL REFERENCES materiales(id) ON DELETE RESTRICT,
    cantidad NUMERIC(12, 2) NOT NULL DEFAULT 1,
    serie VARCHAR(120)
);

CREATE TABLE IF NOT EXISTS infraestructura_revision_evidencias (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    revision_id INTEGER NOT NULL REFERENCES infraestructura_revisiones(id) ON DELETE CASCADE,
    filename VARCHAR(255) NOT NULL,
    mimetype VARCHAR(100),
    uploaded_at TIMESTAMP WITHOUT TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS bitacoras_arco (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    arco_id INTEGER NOT NULL REFERENCES arcos(id) ON DELETE CASCADE,
    encargado VARCHAR(150),
    observaciones TEXT,
    fecha_registro TIMESTAMP WITHOUT TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS checklist_conceptos (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre VARCHAR(255) NOT NULL,
    activo INTEGER NOT NULL DEFAULT 1
);

CREATE TABLE IF NOT EXISTS bitacora_checklist (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    bitacora_id INTEGER NOT NULL REFERENCES bitacoras_arco(id) ON DELETE CASCADE,
    concepto_id INTEGER NOT NULL REFERENCES checklist_conceptos(id) ON DELETE RESTRICT,
    realizado INTEGER NOT NULL DEFAULT 1,
    UNIQUE (bitacora_id, concepto_id)
);

CREATE INDEX IF NOT EXISTS idx_arcos_ubicacion_id ON arcos (ubicacion_id);
CREATE INDEX IF NOT EXISTS idx_tecnicos_activo ON tecnicos (activo);
CREATE INDEX IF NOT EXISTS idx_arco_material_arco_id ON arco_material (arco_id);
CREATE INDEX IF NOT EXISTS idx_arco_material_material_id ON arco_material (material_id);
CREATE INDEX IF NOT EXISTS idx_revisiones_arco_id ON revisiones (arco_id);
CREATE INDEX IF NOT EXISTS idx_revisiones_fecha ON revisiones (fecha_mantenimiento);
CREATE INDEX IF NOT EXISTS idx_revisiones_arco_fecha ON revisiones (arco_id, fecha_mantenimiento DESC);
CREATE INDEX IF NOT EXISTS idx_revision_material_revision_id ON revision_material (revision_id);
CREATE INDEX IF NOT EXISTS idx_revision_material_arco_material_id ON revision_material (arco_material_id);
CREATE INDEX IF NOT EXISTS idx_revision_evidencias_revision_id ON revision_evidencias (revision_id);
CREATE INDEX IF NOT EXISTS idx_formatos_mantenimiento_revision ON formatos_mantenimiento (revision_id, created_at DESC);
CREATE INDEX IF NOT EXISTS idx_formatos_mantenimiento_arco ON formatos_mantenimiento (arco_id, created_at DESC);
CREATE INDEX IF NOT EXISTS idx_arcos_estado ON arcos (estado);
CREATE INDEX IF NOT EXISTS idx_arcos_bajas_arco_id ON arcos_bajas (arco_id);
CREATE INDEX IF NOT EXISTS idx_arcos_bajas_fecha ON arcos_bajas (fecha_baja);
CREATE INDEX IF NOT EXISTS idx_arcos_bajas_evidencias_baja_id ON arcos_bajas_evidencias (baja_id);
CREATE INDEX IF NOT EXISTS idx_infraestructura_nodos_ubicacion_id ON infraestructura_nodos (ubicacion_id);
CREATE INDEX IF NOT EXISTS idx_infraestructura_material_infra_id ON infraestructura_material (infraestructura_id);
CREATE INDEX IF NOT EXISTS idx_infraestructura_revisiones_infra_id ON infraestructura_revisiones (infraestructura_id);
CREATE INDEX IF NOT EXISTS idx_infra_revisiones_infra_fecha ON infraestructura_revisiones (infraestructura_id, fecha_mantenimiento DESC);
CREATE INDEX IF NOT EXISTS idx_infra_revision_material_revision_id ON infraestructura_revision_material (revision_id);
CREATE INDEX IF NOT EXISTS idx_infra_revision_evidencias_revision_id ON infraestructura_revision_evidencias (revision_id);
CREATE INDEX IF NOT EXISTS idx_bitacoras_arco_id ON bitacoras_arco (arco_id);
CREATE INDEX IF NOT EXISTS idx_bitacoras_arco_fecha ON bitacoras_arco (arco_id, fecha_registro DESC);


-- Limpieza de tablas importadas
TRUNCATE TABLE "bitacora_checklist", "checklist_conceptos", "bitacoras_arco", "infraestructura_revision_evidencias", "infraestructura_revision_material", "infraestructura_revisiones", "infraestructura_material", "arco_infraestructura", "infraestructura_nodos", "revision_evidencias", "revision_material", "revisiones", "arco_material", "arcos", "materiales", "ubicaciones", "users" RESTART IDENTITY CASCADE;

-- Datos convertidos
-- users: 1 registro(s)
INSERT INTO "users" ("id", "username", "password", "role") VALUES ('3', 'jlromero', '$2y$10$CXwyF7DhaIufmCM6HOGqNeet4lRAkugpdXrdMfivyyIV6.FmUY9a2', 'admin');

-- ubicaciones: 8 registro(s)
INSERT INTO "ubicaciones" ("id", "nombre", "lat", "lng") VALUES ('3', 'Chilpancingo', '17.460713', '-99.497681');
INSERT INTO "ubicaciones" ("id", "nombre", "lat", "lng") VALUES ('4', 'Acapulco', '16.851862', '-99.821777');
INSERT INTO "ubicaciones" ("id", "nombre", "lat", "lng") VALUES ('5', 'Taxco', NULL, NULL);
INSERT INTO "ubicaciones" ("id", "nombre", "lat", "lng") VALUES ('6', 'Iguala', NULL, NULL);
INSERT INTO "ubicaciones" ("id", "nombre", "lat", "lng") VALUES ('7', 'Zihuatanejo', NULL, NULL);
INSERT INTO "ubicaciones" ("id", "nombre", "lat", "lng") VALUES ('8', 'San Marcos', NULL, NULL);
INSERT INTO "ubicaciones" ("id", "nombre", "lat", "lng") VALUES ('9', 'Ometepec', NULL, NULL);
INSERT INTO "ubicaciones" ("id", "nombre", "lat", "lng") VALUES ('10', 'Coyuca', '17.007186', '-100084279');

-- materiales: 25 registro(s)
INSERT INTO "materiales" ("id", "nombre", "medida", "foto", "serie") VALUES ('7', 'Camara LPR', 'pz', '1764729971_camara lpr.png', NULL);
INSERT INTO "materiales" ("id", "nombre", "medida", "foto", "serie") VALUES ('8', 'Enlace Ubiquiti M5', 'pz', '1779659842_Enlace Ubiquiti M5.png', NULL);
INSERT INTO "materiales" ("id", "nombre", "medida", "foto", "serie") VALUES ('9', 'Switch 5 Puertos Controntolador Solar Wiltek', 'pz', '1764729996_switch 5 puertos panel solar.png', NULL);
INSERT INTO "materiales" ("id", "nombre", "medida", "foto", "serie") VALUES ('10', 'SpeedWay 4 Conectores', 'pz', '1764730013_speedway.jpg', NULL);
INSERT INTO "materiales" ("id", "nombre", "medida", "foto", "serie") VALUES ('11', 'Antena Yagi RFID 5 Elementos', 'pz', '1780038784_Antena Yagi de 5 Elementos.png', NULL);
INSERT INTO "materiales" ("id", "nombre", "medida", "foto", "serie") VALUES ('12', 'Panel Solar Epcom 19V 150W', 'pz', '1764730052_PANEL SOLAR.PNG', NULL);
INSERT INTO "materiales" ("id", "nombre", "medida", "foto", "serie") VALUES ('13', 'Bateria Solar', 'pz', '1764730062_bateria.png', NULL);
INSERT INTO "materiales" ("id", "nombre", "medida", "foto", "serie") VALUES ('14', 'Cable FotoVoltaico Positivo', 'm', '1764730460_cable fotovoltaico positivo.png', NULL);
INSERT INTO "materiales" ("id", "nombre", "medida", "foto", "serie") VALUES ('15', 'Cable FotoVoltaico Negativo', 'm', '1764730481_cable fotovoltaico negativo.png', NULL);
INSERT INTO "materiales" ("id", "nombre", "medida", "foto", "serie") VALUES ('16', 'Cable TNC', 'm', '1764731117_Cable TNC.png', NULL);
INSERT INTO "materiales" ("id", "nombre", "medida", "foto", "serie") VALUES ('17', 'Gabinete Doble Cerradura', 'pz', '1772599896_Gabinete doble Cerradura.jpg', NULL);
INSERT INTO "materiales" ("id", "nombre", "medida", "foto", "serie") VALUES ('18', 'Cable 1+1', 'm', '1772600756_cable 1+1.jpg', NULL);
INSERT INTO "materiales" ("id", "nombre", "medida", "foto", "serie") VALUES ('19', 'Gabinete 1 nivel', 'pz', '1779087212_gabinete 1 nivel.png', NULL);
INSERT INTO "materiales" ("id", "nombre", "medida", "foto", "serie") VALUES ('20', 'Gabinete con soporte en forma L', 'pz', '1779658323_Gabinete con soporte en forma de L.jpg', NULL);
INSERT INTO "materiales" ("id", "nombre", "medida", "foto", "serie") VALUES ('21', 'Enlace Ubiquiti AC', 'pz', '1779659869_Enlace Ubiquiti AC.png', NULL);
INSERT INTO "materiales" ("id", "nombre", "medida", "foto", "serie") VALUES ('22', 'Switch 8 Puetos Controlador Solar Wiltek', 'pz', '1779659937_switch 8 puertos.jpg', NULL);
INSERT INTO "materiales" ("id", "nombre", "medida", "foto", "serie") VALUES ('23', 'Switch 16 Puertos Wiltek', 'pz', '1779659957_switch 16 puertos.png', NULL);
INSERT INTO "materiales" ("id", "nombre", "medida", "foto", "serie") VALUES ('24', 'Switch 5 Puertos TP Link', 'pz', '1779661807_switch 5 puertos TP Link.jpg', NULL);
INSERT INTO "materiales" ("id", "nombre", "medida", "foto", "serie") VALUES ('25', 'Controlador Solar POE', 'pz', '1779663102_Controlador Solar POE.png', NULL);
INSERT INTO "materiales" ("id", "nombre", "medida", "foto", "serie") VALUES ('26', 'SpeedWay 2 Conectores', 'pz', '1779663580_Speedway 2 Conectores .jpg', NULL);
INSERT INTO "materiales" ("id", "nombre", "medida", "foto", "serie") VALUES ('27', 'Switch 24 Puertos cisco', 'pz', '1780024851_switch 24 puertos cisco.jpg', NULL);
INSERT INTO "materiales" ("id", "nombre", "medida", "foto", "serie") VALUES ('28', 'Swich 5 puertos HikVision', 'pz', '1780203061_switch 5 puertos Hikvision.jpg', NULL);
INSERT INTO "materiales" ("id", "nombre", "medida", "foto", "serie") VALUES ('29', 'Enlace Ubiquiti AC ISO', 'pz', '1780217319_enlace Ubiquiti AC ISO.png', NULL);
INSERT INTO "materiales" ("id", "nombre", "medida", "foto", "serie") VALUES ('30', 'UTP Cat 5e Exterior', 'm', '1780217657_Cable UTP Cat 5e Exterior.png', NULL);
INSERT INTO "materiales" ("id", "nombre", "medida", "foto", "serie") VALUES ('31', 'Cambium Force 300', 'pz', '1780271136_Enlace Cambium force 300.png', NULL);

-- arcos: 23 registro(s)
INSERT INTO "arcos" ("id", "nombre", "ubicacion_id", "fecha_instalacion", "lng", "lat") VALUES ('3', 'Cinca', '3', '2019-10-29 00:00:00', '-99.475129', '17.507284');
INSERT INTO "arcos" ("id", "nombre", "ubicacion_id", "fecha_instalacion", "lng", "lat") VALUES ('5', 'Bulevar de las Naciones', '4', '2025-12-20 04:00:00', '-99.802755', '16.791057');
INSERT INTO "arcos" ("id", "nombre", "ubicacion_id", "fecha_instalacion", "lng", "lat") VALUES ('6', 'Salida Taxco', '5', '2025-12-03 00:00:00', NULL, NULL);
INSERT INTO "arcos" ("id", "nombre", "ubicacion_id", "fecha_instalacion", "lng", "lat") VALUES ('7', 'Entrada Taxco', '5', '2025-12-02 00:00:00', NULL, NULL);
INSERT INTO "arcos" ("id", "nombre", "ubicacion_id", "fecha_instalacion", "lng", "lat") VALUES ('11', 'Cima', '4', '2026-02-13 00:00:00', ' -99.859994', '16.877297');
INSERT INTO "arcos" ("id", "nombre", "ubicacion_id", "fecha_instalacion", "lng", "lat") VALUES ('18', 'Entrada Iguala', '6', '2026-03-27 00:00:00', '-99.501801', '18.314115');
INSERT INTO "arcos" ("id", "nombre", "ubicacion_id", "fecha_instalacion", "lng", "lat") VALUES ('21', 'Libramiento Tixtla', '3', '2022-10-12 00:00:00', '-99.501286', '17.592812');
INSERT INTO "arcos" ("id", "nombre", "ubicacion_id", "fecha_instalacion", "lng", "lat") VALUES ('22', 'Horquetas', '4', '2026-03-21 00:00:00', '-99.574117', '16.755672');
INSERT INTO "arcos" ("id", "nombre", "ubicacion_id", "fecha_instalacion", "lng", "lat") VALUES ('23', 'San Juan de los llanos', '9', '2026-04-01 00:00:00', '-98.446532,3a', '16.6832135');
INSERT INTO "arcos" ("id", "nombre", "ubicacion_id", "fecha_instalacion", "lng", "lat") VALUES ('31', 'Cayaco - Las Cruces', '4', '2017-06-17 21:04:00', '99.8103806,3a', '16.8651166');
INSERT INTO "arcos" ("id", "nombre", "ubicacion_id", "fecha_instalacion", "lng", "lat") VALUES ('32', 'Lazaro Cardenas', '3', '2019-12-06 00:13:00', '-99.515489', '17.583102');
INSERT INTO "arcos" ("id", "nombre", "ubicacion_id", "fecha_instalacion", "lng", "lat") VALUES ('33', 'Hospital', '3', '2021-01-16 01:34:00', '-99.522409', '17.605768');
INSERT INTO "arcos" ("id", "nombre", "ubicacion_id", "fecha_instalacion", "lng", "lat") VALUES ('34', 'Tierras Pietras - Tixtla', '3', '2021-09-29 16:04:00', '-99.515833', '17.603447');
INSERT INTO "arcos" ("id", "nombre", "ubicacion_id", "fecha_instalacion", "lng", "lat") VALUES ('35', 'Autopista Chilpancingo - Acapulco', '3', '2021-11-11 16:30:00', '-99.481361', '17.513030');
INSERT INTO "arcos" ("id", "nombre", "ubicacion_id", "fecha_instalacion", "lng", "lat") VALUES ('36', 'Chichihualco', '3', '2023-11-16 15:40:00', '-99.5192992', '17.5917693');
INSERT INTO "arcos" ("id", "nombre", "ubicacion_id", "fecha_instalacion", "lng", "lat") VALUES ('37', 'Amojileca', '3', '2021-09-29 15:04:00', '-99.525065', '17.5551348');
INSERT INTO "arcos" ("id", "nombre", "ubicacion_id", "fecha_instalacion", "lng", "lat") VALUES ('38', 'Renacimiento', '4', '2024-04-30 02:35:00', '-99.8306721', '16.8981042');
INSERT INTO "arcos" ("id", "nombre", "ubicacion_id", "fecha_instalacion", "lng", "lat") VALUES ('39', 'OMETEPEC-IGUALAPA', '9', '2021-02-20 16:40:00', '98.428594', '16.708102');
INSERT INTO "arcos" ("id", "nombre", "ubicacion_id", "fecha_instalacion", "lng", "lat") VALUES ('40', 'OMETEPEC-LAS IGUANAS', '9', '2021-10-21 15:30:00', '-98.4242755,3a', '16.6809867');
INSERT INTO "arcos" ("id", "nombre", "ubicacion_id", "fecha_instalacion", "lng", "lat") VALUES ('41', 'OMETEPEC-XOCHIS', '9', '2021-10-22 14:40:00', '-98.3869374,3a', '16.6987012');
INSERT INTO "arcos" ("id", "nombre", "ubicacion_id", "fecha_instalacion", "lng", "lat") VALUES ('42', 'AEROPUERTO-ZIHUATANEJO', '7', '2004-10-04 15:00:00', '-101.52811409', '17.647651');
INSERT INTO "arcos" ("id", "nombre", "ubicacion_id", "fecha_instalacion", "lng", "lat") VALUES ('43', 'LAZARO CARDENAS-IXTAPA', '7', '2024-10-03 14:04:00', '-101.5748369', '17.6593304');
INSERT INTO "arcos" ("id", "nombre", "ubicacion_id", "fecha_instalacion", "lng", "lat") VALUES ('44', 'ZIHUATANEJO-MIRADOR', '7', '2024-10-03 15:04:00', '101.6021398', '17.6785773');

-- arco_material: 276 registro(s)
INSERT INTO "arco_material" ("id", "arco_id", "material_id", "cantidad", "foto", "serie") VALUES ('20', '6', '11', '2', NULL, NULL);
INSERT INTO "arco_material" ("id", "arco_id", "material_id", "cantidad", "foto", "serie") VALUES ('21', '6', '13', '2', NULL, NULL);
INSERT INTO "arco_material" ("id", "arco_id", "material_id", "cantidad", "foto", "serie") VALUES ('22', '6', '12', '2', NULL, NULL);
INSERT INTO "arco_material" ("id", "arco_id", "material_id", "cantidad", "foto", "serie") VALUES ('23', '6', '9', '1', NULL, NULL);
INSERT INTO "arco_material" ("id", "arco_id", "material_id", "cantidad", "foto", "serie") VALUES ('24', '6', '10', '1', NULL, NULL);
INSERT INTO "arco_material" ("id", "arco_id", "material_id", "cantidad", "foto", "serie") VALUES ('25', '6', '8', '1', NULL, NULL);
INSERT INTO "arco_material" ("id", "arco_id", "material_id", "cantidad", "foto", "serie") VALUES ('26', '6', '16', '10', NULL, NULL);
INSERT INTO "arco_material" ("id", "arco_id", "material_id", "cantidad", "foto", "serie") VALUES ('27', '6', '15', '5', NULL, NULL);
INSERT INTO "arco_material" ("id", "arco_id", "material_id", "cantidad", "foto", "serie") VALUES ('28', '6', '14', '5', NULL, NULL);
INSERT INTO "arco_material" ("id", "arco_id", "material_id", "cantidad", "foto", "serie") VALUES ('29', '7', '11', '2', NULL, NULL);
INSERT INTO "arco_material" ("id", "arco_id", "material_id", "cantidad", "foto", "serie") VALUES ('30', '7', '13', '2', NULL, NULL);
INSERT INTO "arco_material" ("id", "arco_id", "material_id", "cantidad", "foto", "serie") VALUES ('31', '7', '15', '4', NULL, NULL);
INSERT INTO "arco_material" ("id", "arco_id", "material_id", "cantidad", "foto", "serie") VALUES ('32', '7', '14', '4', NULL, NULL);
INSERT INTO "arco_material" ("id", "arco_id", "material_id", "cantidad", "foto", "serie") VALUES ('33', '7', '16', '14', NULL, NULL);
INSERT INTO "arco_material" ("id", "arco_id", "material_id", "cantidad", "foto", "serie") VALUES ('34', '7', '8', '1', NULL, NULL);
INSERT INTO "arco_material" ("id", "arco_id", "material_id", "cantidad", "foto", "serie") VALUES ('35', '7', '12', '2', NULL, NULL);
INSERT INTO "arco_material" ("id", "arco_id", "material_id", "cantidad", "foto", "serie") VALUES ('36', '7', '10', '1', NULL, NULL);
INSERT INTO "arco_material" ("id", "arco_id", "material_id", "cantidad", "foto", "serie") VALUES ('37', '7', '9', '1', NULL, NULL);
INSERT INTO "arco_material" ("id", "arco_id", "material_id", "cantidad", "foto", "serie") VALUES ('239', '3', '7', '2', NULL, '9E0F44CPAJFFE7B');
INSERT INTO "arco_material" ("id", "arco_id", "material_id", "cantidad", "foto", "serie") VALUES ('240', '3', '10', '1', NULL, '370-20-12-0287');
INSERT INTO "arco_material" ("id", "arco_id", "material_id", "cantidad", "foto", "serie") VALUES ('241', '3', '7', '1', NULL, '8B0159EAAJ3FAD7');
INSERT INTO "arco_material" ("id", "arco_id", "material_id", "cantidad", "foto", "serie") VALUES ('242', '3', '10', '1', NULL, '370-11-41-0260');
INSERT INTO "arco_material" ("id", "arco_id", "material_id", "cantidad", "foto", "serie") VALUES ('243', '3', '8', '1', NULL, '');
INSERT INTO "arco_material" ("id", "arco_id", "material_id", "cantidad", "foto", "serie") VALUES ('244', '3', '9', '1', NULL, '');
INSERT INTO "arco_material" ("id", "arco_id", "material_id", "cantidad", "foto", "serie") VALUES ('245', '3', '11', '1', NULL, '');
INSERT INTO "arco_material" ("id", "arco_id", "material_id", "cantidad", "foto", "serie") VALUES ('246', '3', '11', '1', NULL, '');
INSERT INTO "arco_material" ("id", "arco_id", "material_id", "cantidad", "foto", "serie") VALUES ('247', '3', '11', '1', NULL, '');
INSERT INTO "arco_material" ("id", "arco_id", "material_id", "cantidad", "foto", "serie") VALUES ('248', '3', '11', '1', NULL, '');
INSERT INTO "arco_material" ("id", "arco_id", "material_id", "cantidad", "foto", "serie") VALUES ('261', '31', '11', '1', NULL, NULL);
INSERT INTO "arco_material" ("id", "arco_id", "material_id", "cantidad", "foto", "serie") VALUES ('262', '31', '11', '1', NULL, NULL);
INSERT INTO "arco_material" ("id", "arco_id", "material_id", "cantidad", "foto", "serie") VALUES ('263', '31', '15', '4', NULL, NULL);
INSERT INTO "arco_material" ("id", "arco_id", "material_id", "cantidad", "foto", "serie") VALUES ('264', '31', '14', '4', NULL, NULL);
INSERT INTO "arco_material" ("id", "arco_id", "material_id", "cantidad", "foto", "serie") VALUES ('265', '31', '8', '1', NULL, NULL);
INSERT INTO "arco_material" ("id", "arco_id", "material_id", "cantidad", "foto", "serie") VALUES ('266', '31', '10', '1', NULL, NULL);
INSERT INTO "arco_material" ("id", "arco_id", "material_id", "cantidad", "foto", "serie") VALUES ('267', '31', '13', '1', NULL, '5661015500079');
INSERT INTO "arco_material" ("id", "arco_id", "material_id", "cantidad", "foto", "serie") VALUES ('268', '31', '13', '1', NULL, '5661015500080');
INSERT INTO "arco_material" ("id", "arco_id", "material_id", "cantidad", "foto", "serie") VALUES ('269', '31', '9', '1', NULL, '5661001000009');
INSERT INTO "arco_material" ("id", "arco_id", "material_id", "cantidad", "foto", "serie") VALUES ('284', '21', '11', '1', NULL, NULL);
INSERT INTO "arco_material" ("id", "arco_id", "material_id", "cantidad", "foto", "serie") VALUES ('285', '21', '13', '1', NULL, NULL);
INSERT INTO "arco_material" ("id", "arco_id", "material_id", "cantidad", "foto", "serie") VALUES ('286', '21', '13', '1', NULL, NULL);
INSERT INTO "arco_material" ("id", "arco_id", "material_id", "cantidad", "foto", "serie") VALUES ('287', '21', '8', '1', NULL, NULL);
INSERT INTO "arco_material" ("id", "arco_id", "material_id", "cantidad", "foto", "serie") VALUES ('288', '21', '11', '1', NULL, NULL);
INSERT INTO "arco_material" ("id", "arco_id", "material_id", "cantidad", "foto", "serie") VALUES ('289', '21', '8', '1', NULL, NULL);
INSERT INTO "arco_material" ("id", "arco_id", "material_id", "cantidad", "foto", "serie") VALUES ('290', '21', '10', '1', NULL, NULL);
INSERT INTO "arco_material" ("id", "arco_id", "material_id", "cantidad", "foto", "serie") VALUES ('322', '33', '11', '1', NULL, NULL);
INSERT INTO "arco_material" ("id", "arco_id", "material_id", "cantidad", "foto", "serie") VALUES ('323', '33', '11', '1', NULL, NULL);
INSERT INTO "arco_material" ("id", "arco_id", "material_id", "cantidad", "foto", "serie") VALUES ('324', '33', '18', '15', NULL, NULL);
INSERT INTO "arco_material" ("id", "arco_id", "material_id", "cantidad", "foto", "serie") VALUES ('325', '33', '16', '14', NULL, NULL);
INSERT INTO "arco_material" ("id", "arco_id", "material_id", "cantidad", "foto", "serie") VALUES ('326', '33', '8', '1', NULL, NULL);
INSERT INTO "arco_material" ("id", "arco_id", "material_id", "cantidad", "foto", "serie") VALUES ('327', '33', '19', '1', NULL, NULL);
INSERT INTO "arco_material" ("id", "arco_id", "material_id", "cantidad", "foto", "serie") VALUES ('328', '33', '10', '1', NULL, '370-14-22-0101');
INSERT INTO "arco_material" ("id", "arco_id", "material_id", "cantidad", "foto", "serie") VALUES ('329', '33', '24', '1', NULL, NULL);
INSERT INTO "arco_material" ("id", "arco_id", "material_id", "cantidad", "foto", "serie") VALUES ('330', '33', '20', '1', NULL, NULL);
INSERT INTO "arco_material" ("id", "arco_id", "material_id", "cantidad", "foto", "serie") VALUES ('344', '34', '11', '1', NULL, NULL);
INSERT INTO "arco_material" ("id", "arco_id", "material_id", "cantidad", "foto", "serie") VALUES ('345', '34', '11', '1', NULL, NULL);
INSERT INTO "arco_material" ("id", "arco_id", "material_id", "cantidad", "foto", "serie") VALUES ('346', '34', '13', '1', NULL, NULL);
INSERT INTO "arco_material" ("id", "arco_id", "material_id", "cantidad", "foto", "serie") VALUES ('347', '34', '13', '1', NULL, NULL);
INSERT INTO "arco_material" ("id", "arco_id", "material_id", "cantidad", "foto", "serie") VALUES ('348', '34', '15', '2.5', NULL, NULL);
INSERT INTO "arco_material" ("id", "arco_id", "material_id", "cantidad", "foto", "serie") VALUES ('349', '34', '14', '2.5', NULL, NULL);
INSERT INTO "arco_material" ("id", "arco_id", "material_id", "cantidad", "foto", "serie") VALUES ('350', '34', '16', '16', NULL, NULL);
INSERT INTO "arco_material" ("id", "arco_id", "material_id", "cantidad", "foto", "serie") VALUES ('351', '34', '25', '1', NULL, NULL);
INSERT INTO "arco_material" ("id", "arco_id", "material_id", "cantidad", "foto", "serie") VALUES ('352', '34', '25', '1', NULL, NULL);
INSERT INTO "arco_material" ("id", "arco_id", "material_id", "cantidad", "foto", "serie") VALUES ('353', '34', '26', '1', NULL, NULL);
INSERT INTO "arco_material" ("id", "arco_id", "material_id", "cantidad", "foto", "serie") VALUES ('354', '34', '20', '1', NULL, NULL);
INSERT INTO "arco_material" ("id", "arco_id", "material_id", "cantidad", "foto", "serie") VALUES ('355', '34', '21', '1', NULL, NULL);
INSERT INTO "arco_material" ("id", "arco_id", "material_id", "cantidad", "foto", "serie") VALUES ('356', '34', '12', '1', NULL, NULL);
INSERT INTO "arco_material" ("id", "arco_id", "material_id", "cantidad", "foto", "serie") VALUES ('385', '5', '10', '1', NULL, NULL);
INSERT INTO "arco_material" ("id", "arco_id", "material_id", "cantidad", "foto", "serie") VALUES ('386', '5', '9', '1', NULL, 'PS306GF-UPS-15A2408MX024');
INSERT INTO "arco_material" ("id", "arco_id", "material_id", "cantidad", "foto", "serie") VALUES ('387', '5', '11', '1', NULL, NULL);
INSERT INTO "arco_material" ("id", "arco_id", "material_id", "cantidad", "foto", "serie") VALUES ('388', '5', '11', '1', NULL, NULL);
INSERT INTO "arco_material" ("id", "arco_id", "material_id", "cantidad", "foto", "serie") VALUES ('389', '5', '8', '1', NULL, NULL);
INSERT INTO "arco_material" ("id", "arco_id", "material_id", "cantidad", "foto", "serie") VALUES ('390', '5', '16', '18', NULL, NULL);
INSERT INTO "arco_material" ("id", "arco_id", "material_id", "cantidad", "foto", "serie") VALUES ('391', '5', '11', '1', NULL, NULL);
INSERT INTO "arco_material" ("id", "arco_id", "material_id", "cantidad", "foto", "serie") VALUES ('392', '5', '11', '1', NULL, NULL);
INSERT INTO "arco_material" ("id", "arco_id", "material_id", "cantidad", "foto", "serie") VALUES ('393', '5', '13', '1', NULL, 'MX05452857');
INSERT INTO "arco_material" ("id", "arco_id", "material_id", "cantidad", "foto", "serie") VALUES ('394', '5', '13', '1', NULL, NULL);
INSERT INTO "arco_material" ("id", "arco_id", "material_id", "cantidad", "foto", "serie") VALUES ('395', '5', '15', '2', NULL, NULL);
INSERT INTO "arco_material" ("id", "arco_id", "material_id", "cantidad", "foto", "serie") VALUES ('396', '5', '14', '2', NULL, NULL);
INSERT INTO "arco_material" ("id", "arco_id", "material_id", "cantidad", "foto", "serie") VALUES ('397', '5', '12', '1', NULL, NULL);
INSERT INTO "arco_material" ("id", "arco_id", "material_id", "cantidad", "foto", "serie") VALUES ('398', '5', '12', '1', NULL, NULL);
INSERT INTO "arco_material" ("id", "arco_id", "material_id", "cantidad", "foto", "serie") VALUES ('399', '35', '11', '1', NULL, NULL);
INSERT INTO "arco_material" ("id", "arco_id", "material_id", "cantidad", "foto", "serie") VALUES ('400', '35', '11', '1', NULL, NULL);
INSERT INTO "arco_material" ("id", "arco_id", "material_id", "cantidad", "foto", "serie") VALUES ('401', '35', '11', '1', NULL, NULL);
INSERT INTO "arco_material" ("id", "arco_id", "material_id", "cantidad", "foto", "serie") VALUES ('402', '35', '11', '1', NULL, NULL);
INSERT INTO "arco_material" ("id", "arco_id", "material_id", "cantidad", "foto", "serie") VALUES ('403', '35', '13', '1', NULL, NULL);
INSERT INTO "arco_material" ("id", "arco_id", "material_id", "cantidad", "foto", "serie") VALUES ('404', '35', '13', '1', NULL, NULL);
INSERT INTO "arco_material" ("id", "arco_id", "material_id", "cantidad", "foto", "serie") VALUES ('405', '35', '15', '2.5', NULL, NULL);
INSERT INTO "arco_material" ("id", "arco_id", "material_id", "cantidad", "foto", "serie") VALUES ('406', '35', '14', '2.5', NULL, NULL);
INSERT INTO "arco_material" ("id", "arco_id", "material_id", "cantidad", "foto", "serie") VALUES ('407', '35', '16', '35', NULL, NULL);
INSERT INTO "arco_material" ("id", "arco_id", "material_id", "cantidad", "foto", "serie") VALUES ('408', '35', '21', '1', NULL, NULL);
INSERT INTO "arco_material" ("id", "arco_id", "material_id", "cantidad", "foto", "serie") VALUES ('409', '35', '20', '1', NULL, NULL);
INSERT INTO "arco_material" ("id", "arco_id", "material_id", "cantidad", "foto", "serie") VALUES ('410', '35', '10', '1', NULL, NULL);
INSERT INTO "arco_material" ("id", "arco_id", "material_id", "cantidad", "foto", "serie") VALUES ('411', '35', '12', '1', NULL, NULL);
INSERT INTO "arco_material" ("id", "arco_id", "material_id", "cantidad", "foto", "serie") VALUES ('412', '35', '12', '1', NULL, NULL);
INSERT INTO "arco_material" ("id", "arco_id", "material_id", "cantidad", "foto", "serie") VALUES ('413', '35', '9', '1', NULL, NULL);
INSERT INTO "arco_material" ("id", "arco_id", "material_id", "cantidad", "foto", "serie") VALUES ('472', '36', '25', '1', NULL, NULL);
INSERT INTO "arco_material" ("id", "arco_id", "material_id", "cantidad", "foto", "serie") VALUES ('473', '36', '25', '1', NULL, NULL);
INSERT INTO "arco_material" ("id", "arco_id", "material_id", "cantidad", "foto", "serie") VALUES ('474', '36', '11', '1', NULL, NULL);
INSERT INTO "arco_material" ("id", "arco_id", "material_id", "cantidad", "foto", "serie") VALUES ('475', '36', '11', '1', NULL, NULL);
INSERT INTO "arco_material" ("id", "arco_id", "material_id", "cantidad", "foto", "serie") VALUES ('476', '36', '18', '10', NULL, NULL);
INSERT INTO "arco_material" ("id", "arco_id", "material_id", "cantidad", "foto", "serie") VALUES ('477', '36', '8', '1', NULL, NULL);
INSERT INTO "arco_material" ("id", "arco_id", "material_id", "cantidad", "foto", "serie") VALUES ('478', '36', '10', '1', NULL, NULL);
INSERT INTO "arco_material" ("id", "arco_id", "material_id", "cantidad", "foto", "serie") VALUES ('479', '36', '19', '1', NULL, NULL);
INSERT INTO "arco_material" ("id", "arco_id", "material_id", "cantidad", "foto", "serie") VALUES ('480', '36', '16', '15', NULL, NULL);
INSERT INTO "arco_material" ("id", "arco_id", "material_id", "cantidad", "foto", "serie") VALUES ('481', '32', '11', '1', NULL, NULL);
INSERT INTO "arco_material" ("id", "arco_id", "material_id", "cantidad", "foto", "serie") VALUES ('482', '32', '11', '1', NULL, NULL);
INSERT INTO "arco_material" ("id", "arco_id", "material_id", "cantidad", "foto", "serie") VALUES ('483', '32', '11', '1', NULL, NULL);
INSERT INTO "arco_material" ("id", "arco_id", "material_id", "cantidad", "foto", "serie") VALUES ('484', '32', '11', '1', NULL, NULL);
INSERT INTO "arco_material" ("id", "arco_id", "material_id", "cantidad", "foto", "serie") VALUES ('485', '32', '18', '8', NULL, NULL);
INSERT INTO "arco_material" ("id", "arco_id", "material_id", "cantidad", "foto", "serie") VALUES ('486', '32', '16', '30', NULL, NULL);
INSERT INTO "arco_material" ("id", "arco_id", "material_id", "cantidad", "foto", "serie") VALUES ('487', '32', '8', '1', NULL, NULL);
INSERT INTO "arco_material" ("id", "arco_id", "material_id", "cantidad", "foto", "serie") VALUES ('488', '32', '10', '1', NULL, '370-12-38-0199');
INSERT INTO "arco_material" ("id", "arco_id", "material_id", "cantidad", "foto", "serie") VALUES ('489', '32', '10', '1', NULL, '370-19-49-0864');
INSERT INTO "arco_material" ("id", "arco_id", "material_id", "cantidad", "foto", "serie") VALUES ('490', '32', '28', '1', NULL, NULL);
INSERT INTO "arco_material" ("id", "arco_id", "material_id", "cantidad", "foto", "serie") VALUES ('491', '32', '7', '1', NULL, '8B0159EAAJ81B1A');
INSERT INTO "arco_material" ("id", "arco_id", "material_id", "cantidad", "foto", "serie") VALUES ('492', '32', '7', '1', NULL, '8B0159EAAJ3FF94');
INSERT INTO "arco_material" ("id", "arco_id", "material_id", "cantidad", "foto", "serie") VALUES ('493', '32', '17', '1', NULL, NULL);
INSERT INTO "arco_material" ("id", "arco_id", "material_id", "cantidad", "foto", "serie") VALUES ('494', '32', '9', '1', NULL, NULL);
INSERT INTO "arco_material" ("id", "arco_id", "material_id", "cantidad", "foto", "serie") VALUES ('497', '22', '13', '1', NULL, NULL);
INSERT INTO "arco_material" ("id", "arco_id", "material_id", "cantidad", "foto", "serie") VALUES ('498', '22', '13', '1', NULL, NULL);
INSERT INTO "arco_material" ("id", "arco_id", "material_id", "cantidad", "foto", "serie") VALUES ('508', '11', '9', '1', NULL, NULL);
INSERT INTO "arco_material" ("id", "arco_id", "material_id", "cantidad", "foto", "serie") VALUES ('509', '11', '10', '1', NULL, NULL);
INSERT INTO "arco_material" ("id", "arco_id", "material_id", "cantidad", "foto", "serie") VALUES ('510', '11', '8', '1', NULL, NULL);
INSERT INTO "arco_material" ("id", "arco_id", "material_id", "cantidad", "foto", "serie") VALUES ('511', '11', '16', '18', NULL, NULL);
INSERT INTO "arco_material" ("id", "arco_id", "material_id", "cantidad", "foto", "serie") VALUES ('512', '11', '17', '1', NULL, NULL);
INSERT INTO "arco_material" ("id", "arco_id", "material_id", "cantidad", "foto", "serie") VALUES ('513', '11', '11', '1', NULL, NULL);
INSERT INTO "arco_material" ("id", "arco_id", "material_id", "cantidad", "foto", "serie") VALUES ('514', '11', '11', '1', NULL, NULL);
INSERT INTO "arco_material" ("id", "arco_id", "material_id", "cantidad", "foto", "serie") VALUES ('515', '11', '13', '1', NULL, NULL);
INSERT INTO "arco_material" ("id", "arco_id", "material_id", "cantidad", "foto", "serie") VALUES ('516', '11', '13', '1', NULL, NULL);
INSERT INTO "arco_material" ("id", "arco_id", "material_id", "cantidad", "foto", "serie") VALUES ('517', '11', '12', '1', NULL, NULL);
INSERT INTO "arco_material" ("id", "arco_id", "material_id", "cantidad", "foto", "serie") VALUES ('518', '11', '12', '1', NULL, NULL);
INSERT INTO "arco_material" ("id", "arco_id", "material_id", "cantidad", "foto", "serie") VALUES ('519', '11', '17', '1', NULL, NULL);
INSERT INTO "arco_material" ("id", "arco_id", "material_id", "cantidad", "foto", "serie") VALUES ('520', '11', '14', '2.5', NULL, NULL);
INSERT INTO "arco_material" ("id", "arco_id", "material_id", "cantidad", "foto", "serie") VALUES ('521', '11', '15', '2.5', NULL, NULL);
INSERT INTO "arco_material" ("id", "arco_id", "material_id", "cantidad", "foto", "serie") VALUES ('555', '18', '11', '1', NULL, NULL);
INSERT INTO "arco_material" ("id", "arco_id", "material_id", "cantidad", "foto", "serie") VALUES ('556', '18', '11', '1', NULL, NULL);
INSERT INTO "arco_material" ("id", "arco_id", "material_id", "cantidad", "foto", "serie") VALUES ('557', '18', '13', '1', NULL, NULL);
INSERT INTO "arco_material" ("id", "arco_id", "material_id", "cantidad", "foto", "serie") VALUES ('558', '18', '13', '1', NULL, NULL);
INSERT INTO "arco_material" ("id", "arco_id", "material_id", "cantidad", "foto", "serie") VALUES ('559', '18', '8', '1', NULL, NULL);
INSERT INTO "arco_material" ("id", "arco_id", "material_id", "cantidad", "foto", "serie") VALUES ('560', '18', '12', '1', NULL, NULL);
INSERT INTO "arco_material" ("id", "arco_id", "material_id", "cantidad", "foto", "serie") VALUES ('561', '18', '12', '1', NULL, NULL);
INSERT INTO "arco_material" ("id", "arco_id", "material_id", "cantidad", "foto", "serie") VALUES ('562', '18', '10', '1', NULL, NULL);
INSERT INTO "arco_material" ("id", "arco_id", "material_id", "cantidad", "foto", "serie") VALUES ('563', '18', '9', '1', NULL, NULL);
INSERT INTO "arco_material" ("id", "arco_id", "material_id", "cantidad", "foto", "serie") VALUES ('564', '18', '16', '15', NULL, NULL);
INSERT INTO "arco_material" ("id", "arco_id", "material_id", "cantidad", "foto", "serie") VALUES ('565', '18', '14', '2.5', NULL, NULL);
INSERT INTO "arco_material" ("id", "arco_id", "material_id", "cantidad", "foto", "serie") VALUES ('566', '18', '15', '2.5', NULL, NULL);
INSERT INTO "arco_material" ("id", "arco_id", "material_id", "cantidad", "foto", "serie") VALUES ('567', '18', '30', '4', NULL, NULL);
INSERT INTO "arco_material" ("id", "arco_id", "material_id", "cantidad", "foto", "serie") VALUES ('568', '38', '11', '1', NULL, NULL);
INSERT INTO "arco_material" ("id", "arco_id", "material_id", "cantidad", "foto", "serie") VALUES ('569', '38', '11', '1', NULL, NULL);
INSERT INTO "arco_material" ("id", "arco_id", "material_id", "cantidad", "foto", "serie") VALUES ('570', '38', '11', '1', NULL, NULL);
INSERT INTO "arco_material" ("id", "arco_id", "material_id", "cantidad", "foto", "serie") VALUES ('571', '38', '11', '1', NULL, NULL);
INSERT INTO "arco_material" ("id", "arco_id", "material_id", "cantidad", "foto", "serie") VALUES ('572', '38', '11', '1', NULL, NULL);
INSERT INTO "arco_material" ("id", "arco_id", "material_id", "cantidad", "foto", "serie") VALUES ('573', '38', '11', '1', NULL, NULL);
INSERT INTO "arco_material" ("id", "arco_id", "material_id", "cantidad", "foto", "serie") VALUES ('574', '38', '20', '1', NULL, NULL);
INSERT INTO "arco_material" ("id", "arco_id", "material_id", "cantidad", "foto", "serie") VALUES ('575', '38', '10', '1', NULL, NULL);
INSERT INTO "arco_material" ("id", "arco_id", "material_id", "cantidad", "foto", "serie") VALUES ('576', '38', '26', '1', NULL, NULL);
INSERT INTO "arco_material" ("id", "arco_id", "material_id", "cantidad", "foto", "serie") VALUES ('577', '38', '18', '20', NULL, NULL);
INSERT INTO "arco_material" ("id", "arco_id", "material_id", "cantidad", "foto", "serie") VALUES ('578', '38', '9', '1', NULL, NULL);
INSERT INTO "arco_material" ("id", "arco_id", "material_id", "cantidad", "foto", "serie") VALUES ('579', '38', '29', '1', NULL, NULL);
INSERT INTO "arco_material" ("id", "arco_id", "material_id", "cantidad", "foto", "serie") VALUES ('580', '38', '30', '10', NULL, NULL);
INSERT INTO "arco_material" ("id", "arco_id", "material_id", "cantidad", "foto", "serie") VALUES ('581', '37', '11', '1', NULL, NULL);
INSERT INTO "arco_material" ("id", "arco_id", "material_id", "cantidad", "foto", "serie") VALUES ('582', '37', '11', '1', NULL, NULL);
INSERT INTO "arco_material" ("id", "arco_id", "material_id", "cantidad", "foto", "serie") VALUES ('583', '37', '13', '1', NULL, NULL);
INSERT INTO "arco_material" ("id", "arco_id", "material_id", "cantidad", "foto", "serie") VALUES ('584', '37', '13', '1', NULL, NULL);
INSERT INTO "arco_material" ("id", "arco_id", "material_id", "cantidad", "foto", "serie") VALUES ('585', '37', '15', '1.5', NULL, NULL);
INSERT INTO "arco_material" ("id", "arco_id", "material_id", "cantidad", "foto", "serie") VALUES ('586', '37', '14', '1.5', NULL, NULL);
INSERT INTO "arco_material" ("id", "arco_id", "material_id", "cantidad", "foto", "serie") VALUES ('587', '37', '16', '15', NULL, NULL);
INSERT INTO "arco_material" ("id", "arco_id", "material_id", "cantidad", "foto", "serie") VALUES ('588', '37', '25', '1', NULL, NULL);
INSERT INTO "arco_material" ("id", "arco_id", "material_id", "cantidad", "foto", "serie") VALUES ('589', '37', '25', '1', NULL, NULL);
INSERT INTO "arco_material" ("id", "arco_id", "material_id", "cantidad", "foto", "serie") VALUES ('590', '37', '29', '1', NULL, NULL);
INSERT INTO "arco_material" ("id", "arco_id", "material_id", "cantidad", "foto", "serie") VALUES ('591', '37', '20', '1', NULL, NULL);
INSERT INTO "arco_material" ("id", "arco_id", "material_id", "cantidad", "foto", "serie") VALUES ('592', '37', '12', '1', NULL, NULL);
INSERT INTO "arco_material" ("id", "arco_id", "material_id", "cantidad", "foto", "serie") VALUES ('593', '37', '12', '1', NULL, NULL);
INSERT INTO "arco_material" ("id", "arco_id", "material_id", "cantidad", "foto", "serie") VALUES ('594', '37', '26', '1', NULL, NULL);
INSERT INTO "arco_material" ("id", "arco_id", "material_id", "cantidad", "foto", "serie") VALUES ('595', '5', '13', '1', NULL, '5661015500076');
INSERT INTO "arco_material" ("id", "arco_id", "material_id", "cantidad", "foto", "serie") VALUES ('596', '5', '13', '1', NULL, '5661015500077');
INSERT INTO "arco_material" ("id", "arco_id", "material_id", "cantidad", "foto", "serie") VALUES ('631', '39', '13', '1', NULL, NULL);
INSERT INTO "arco_material" ("id", "arco_id", "material_id", "cantidad", "foto", "serie") VALUES ('632', '39', '13', '1', NULL, NULL);
INSERT INTO "arco_material" ("id", "arco_id", "material_id", "cantidad", "foto", "serie") VALUES ('633', '39', '11', '1', NULL, NULL);
INSERT INTO "arco_material" ("id", "arco_id", "material_id", "cantidad", "foto", "serie") VALUES ('634', '39', '11', '1', NULL, NULL);
INSERT INTO "arco_material" ("id", "arco_id", "material_id", "cantidad", "foto", "serie") VALUES ('635', '39', '15', '2.5', NULL, NULL);
INSERT INTO "arco_material" ("id", "arco_id", "material_id", "cantidad", "foto", "serie") VALUES ('636', '39', '14', '2.5', NULL, NULL);
INSERT INTO "arco_material" ("id", "arco_id", "material_id", "cantidad", "foto", "serie") VALUES ('637', '39', '16', '14', NULL, NULL);
INSERT INTO "arco_material" ("id", "arco_id", "material_id", "cantidad", "foto", "serie") VALUES ('638', '39', '29', '1', NULL, NULL);
INSERT INTO "arco_material" ("id", "arco_id", "material_id", "cantidad", "foto", "serie") VALUES ('639', '39', '12', '1', NULL, NULL);
INSERT INTO "arco_material" ("id", "arco_id", "material_id", "cantidad", "foto", "serie") VALUES ('640', '39', '12', '1', NULL, NULL);
INSERT INTO "arco_material" ("id", "arco_id", "material_id", "cantidad", "foto", "serie") VALUES ('642', '39', '9', '1', NULL, NULL);
INSERT INTO "arco_material" ("id", "arco_id", "material_id", "cantidad", "foto", "serie") VALUES ('643', '39', '30', '4', NULL, NULL);
INSERT INTO "arco_material" ("id", "arco_id", "material_id", "cantidad", "foto", "serie") VALUES ('644', '23', '11', '1', NULL, NULL);
INSERT INTO "arco_material" ("id", "arco_id", "material_id", "cantidad", "foto", "serie") VALUES ('645', '23', '11', '1', NULL, NULL);
INSERT INTO "arco_material" ("id", "arco_id", "material_id", "cantidad", "foto", "serie") VALUES ('646', '23', '13', '1', NULL, NULL);
INSERT INTO "arco_material" ("id", "arco_id", "material_id", "cantidad", "foto", "serie") VALUES ('647', '23', '13', '1', NULL, NULL);
INSERT INTO "arco_material" ("id", "arco_id", "material_id", "cantidad", "foto", "serie") VALUES ('648', '23', '16', '30', NULL, NULL);
INSERT INTO "arco_material" ("id", "arco_id", "material_id", "cantidad", "foto", "serie") VALUES ('649', '23', '20', '1', NULL, NULL);
INSERT INTO "arco_material" ("id", "arco_id", "material_id", "cantidad", "foto", "serie") VALUES ('650', '23', '29', '1', NULL, NULL);
INSERT INTO "arco_material" ("id", "arco_id", "material_id", "cantidad", "foto", "serie") VALUES ('651', '23', '26', '1', NULL, NULL);
INSERT INTO "arco_material" ("id", "arco_id", "material_id", "cantidad", "foto", "serie") VALUES ('652', '23', '30', '8', NULL, NULL);
INSERT INTO "arco_material" ("id", "arco_id", "material_id", "cantidad", "foto", "serie") VALUES ('653', '23', '18', '10', NULL, NULL);
INSERT INTO "arco_material" ("id", "arco_id", "material_id", "cantidad", "foto", "serie") VALUES ('654', '40', '20', '1', NULL, NULL);
INSERT INTO "arco_material" ("id", "arco_id", "material_id", "cantidad", "foto", "serie") VALUES ('655', '40', '12', '1', NULL, NULL);
INSERT INTO "arco_material" ("id", "arco_id", "material_id", "cantidad", "foto", "serie") VALUES ('656', '40', '12', '1', NULL, NULL);
INSERT INTO "arco_material" ("id", "arco_id", "material_id", "cantidad", "foto", "serie") VALUES ('657', '40', '13', '1', NULL, NULL);
INSERT INTO "arco_material" ("id", "arco_id", "material_id", "cantidad", "foto", "serie") VALUES ('658', '40', '13', '1', NULL, NULL);
INSERT INTO "arco_material" ("id", "arco_id", "material_id", "cantidad", "foto", "serie") VALUES ('659', '40', '15', '2.5', NULL, NULL);
INSERT INTO "arco_material" ("id", "arco_id", "material_id", "cantidad", "foto", "serie") VALUES ('660', '40', '14', '2.5', NULL, NULL);
INSERT INTO "arco_material" ("id", "arco_id", "material_id", "cantidad", "foto", "serie") VALUES ('661', '40', '16', '13', NULL, NULL);
INSERT INTO "arco_material" ("id", "arco_id", "material_id", "cantidad", "foto", "serie") VALUES ('662', '40', '10', '1', NULL, NULL);
INSERT INTO "arco_material" ("id", "arco_id", "material_id", "cantidad", "foto", "serie") VALUES ('663', '40', '29', '1', NULL, NULL);
INSERT INTO "arco_material" ("id", "arco_id", "material_id", "cantidad", "foto", "serie") VALUES ('664', '40', '9', '1', NULL, NULL);
INSERT INTO "arco_material" ("id", "arco_id", "material_id", "cantidad", "foto", "serie") VALUES ('665', '41', '13', '1', NULL, NULL);
INSERT INTO "arco_material" ("id", "arco_id", "material_id", "cantidad", "foto", "serie") VALUES ('666', '41', '13', '1', NULL, NULL);
INSERT INTO "arco_material" ("id", "arco_id", "material_id", "cantidad", "foto", "serie") VALUES ('667', '41', '11', '1', NULL, NULL);
INSERT INTO "arco_material" ("id", "arco_id", "material_id", "cantidad", "foto", "serie") VALUES ('668', '41', '11', '1', NULL, NULL);
INSERT INTO "arco_material" ("id", "arco_id", "material_id", "cantidad", "foto", "serie") VALUES ('669', '41', '15', '2.5', NULL, NULL);
INSERT INTO "arco_material" ("id", "arco_id", "material_id", "cantidad", "foto", "serie") VALUES ('670', '41', '14', '2.5', NULL, NULL);
INSERT INTO "arco_material" ("id", "arco_id", "material_id", "cantidad", "foto", "serie") VALUES ('671', '41', '16', '15', NULL, NULL);
INSERT INTO "arco_material" ("id", "arco_id", "material_id", "cantidad", "foto", "serie") VALUES ('672', '41', '29', '1', NULL, NULL);
INSERT INTO "arco_material" ("id", "arco_id", "material_id", "cantidad", "foto", "serie") VALUES ('673', '41', '12', '1', NULL, NULL);
INSERT INTO "arco_material" ("id", "arco_id", "material_id", "cantidad", "foto", "serie") VALUES ('674', '41', '12', '1', NULL, NULL);
INSERT INTO "arco_material" ("id", "arco_id", "material_id", "cantidad", "foto", "serie") VALUES ('675', '41', '20', '1', NULL, NULL);
INSERT INTO "arco_material" ("id", "arco_id", "material_id", "cantidad", "foto", "serie") VALUES ('676', '41', '9', '1', NULL, NULL);
INSERT INTO "arco_material" ("id", "arco_id", "material_id", "cantidad", "foto", "serie") VALUES ('677', '41', '30', '20', NULL, NULL);
INSERT INTO "arco_material" ("id", "arco_id", "material_id", "cantidad", "foto", "serie") VALUES ('697', '22', '11', '1', NULL, NULL);
INSERT INTO "arco_material" ("id", "arco_id", "material_id", "cantidad", "foto", "serie") VALUES ('698', '22', '11', '1', NULL, NULL);
INSERT INTO "arco_material" ("id", "arco_id", "material_id", "cantidad", "foto", "serie") VALUES ('701', '22', '14', '4', NULL, NULL);
INSERT INTO "arco_material" ("id", "arco_id", "material_id", "cantidad", "foto", "serie") VALUES ('702', '22', '15', '4', NULL, NULL);
INSERT INTO "arco_material" ("id", "arco_id", "material_id", "cantidad", "foto", "serie") VALUES ('703', '22', '26', '1', NULL, NULL);
INSERT INTO "arco_material" ("id", "arco_id", "material_id", "cantidad", "foto", "serie") VALUES ('704', '22', '9', '1', NULL, NULL);
INSERT INTO "arco_material" ("id", "arco_id", "material_id", "cantidad", "foto", "serie") VALUES ('705', '22', '16', '18', NULL, NULL);
INSERT INTO "arco_material" ("id", "arco_id", "material_id", "cantidad", "foto", "serie") VALUES ('706', '22', '17', '1', NULL, NULL);
INSERT INTO "arco_material" ("id", "arco_id", "material_id", "cantidad", "foto", "serie") VALUES ('707', '22', '8', '1', NULL, NULL);
INSERT INTO "arco_material" ("id", "arco_id", "material_id", "cantidad", "foto", "serie") VALUES ('708', '22', '12', '1', NULL, NULL);
INSERT INTO "arco_material" ("id", "arco_id", "material_id", "cantidad", "foto", "serie") VALUES ('709', '22', '12', '1', NULL, NULL);
INSERT INTO "arco_material" ("id", "arco_id", "material_id", "cantidad", "foto", "serie") VALUES ('710', '22', '30', '6', NULL, NULL);
INSERT INTO "arco_material" ("id", "arco_id", "material_id", "cantidad", "foto", "serie") VALUES ('711', '39', '26', '1', NULL, NULL);
INSERT INTO "arco_material" ("id", "arco_id", "material_id", "cantidad", "foto", "serie") VALUES ('712', '39', '20', '1', NULL, NULL);
INSERT INTO "arco_material" ("id", "arco_id", "material_id", "cantidad", "foto", "serie") VALUES ('713', '42', '13', '1', NULL, NULL);
INSERT INTO "arco_material" ("id", "arco_id", "material_id", "cantidad", "foto", "serie") VALUES ('714', '42', '13', '1', NULL, NULL);
INSERT INTO "arco_material" ("id", "arco_id", "material_id", "cantidad", "foto", "serie") VALUES ('715', '42', '11', '1', NULL, NULL);
INSERT INTO "arco_material" ("id", "arco_id", "material_id", "cantidad", "foto", "serie") VALUES ('716', '42', '11', '1', NULL, NULL);
INSERT INTO "arco_material" ("id", "arco_id", "material_id", "cantidad", "foto", "serie") VALUES ('717', '42', '15', '6', NULL, NULL);
INSERT INTO "arco_material" ("id", "arco_id", "material_id", "cantidad", "foto", "serie") VALUES ('718', '42', '14', '6', NULL, NULL);
INSERT INTO "arco_material" ("id", "arco_id", "material_id", "cantidad", "foto", "serie") VALUES ('719', '42', '17', '1', NULL, NULL);
INSERT INTO "arco_material" ("id", "arco_id", "material_id", "cantidad", "foto", "serie") VALUES ('721', '42', '12', '1', NULL, NULL);
INSERT INTO "arco_material" ("id", "arco_id", "material_id", "cantidad", "foto", "serie") VALUES ('722', '42', '12', '1', NULL, NULL);
INSERT INTO "arco_material" ("id", "arco_id", "material_id", "cantidad", "foto", "serie") VALUES ('723', '42', '9', '1', NULL, NULL);
INSERT INTO "arco_material" ("id", "arco_id", "material_id", "cantidad", "foto", "serie") VALUES ('724', '42', '30', '6', NULL, NULL);
INSERT INTO "arco_material" ("id", "arco_id", "material_id", "cantidad", "foto", "serie") VALUES ('725', '42', '16', '16', NULL, NULL);
INSERT INTO "arco_material" ("id", "arco_id", "material_id", "cantidad", "foto", "serie") VALUES ('726', '42', '31', '1', NULL, NULL);
INSERT INTO "arco_material" ("id", "arco_id", "material_id", "cantidad", "foto", "serie") VALUES ('727', '43', '11', '1', NULL, NULL);
INSERT INTO "arco_material" ("id", "arco_id", "material_id", "cantidad", "foto", "serie") VALUES ('728', '43', '11', '1', NULL, NULL);
INSERT INTO "arco_material" ("id", "arco_id", "material_id", "cantidad", "foto", "serie") VALUES ('729', '43', '13', '1', NULL, NULL);
INSERT INTO "arco_material" ("id", "arco_id", "material_id", "cantidad", "foto", "serie") VALUES ('730', '43', '13', '1', NULL, NULL);
INSERT INTO "arco_material" ("id", "arco_id", "material_id", "cantidad", "foto", "serie") VALUES ('731', '43', '15', '5', NULL, NULL);
INSERT INTO "arco_material" ("id", "arco_id", "material_id", "cantidad", "foto", "serie") VALUES ('732', '43', '14', '5', NULL, NULL);
INSERT INTO "arco_material" ("id", "arco_id", "material_id", "cantidad", "foto", "serie") VALUES ('733', '43', '16', '17', NULL, NULL);
INSERT INTO "arco_material" ("id", "arco_id", "material_id", "cantidad", "foto", "serie") VALUES ('734', '43', '31', '1', NULL, NULL);
INSERT INTO "arco_material" ("id", "arco_id", "material_id", "cantidad", "foto", "serie") VALUES ('735', '43', '17', '1', NULL, NULL);
INSERT INTO "arco_material" ("id", "arco_id", "material_id", "cantidad", "foto", "serie") VALUES ('736', '43', '12', '1', NULL, NULL);
INSERT INTO "arco_material" ("id", "arco_id", "material_id", "cantidad", "foto", "serie") VALUES ('737', '43', '12', '1', NULL, NULL);
INSERT INTO "arco_material" ("id", "arco_id", "material_id", "cantidad", "foto", "serie") VALUES ('738', '43', '26', '1', NULL, NULL);
INSERT INTO "arco_material" ("id", "arco_id", "material_id", "cantidad", "foto", "serie") VALUES ('739', '43', '30', '6', NULL, NULL);
INSERT INTO "arco_material" ("id", "arco_id", "material_id", "cantidad", "foto", "serie") VALUES ('740', '44', '13', '1', NULL, NULL);
INSERT INTO "arco_material" ("id", "arco_id", "material_id", "cantidad", "foto", "serie") VALUES ('741', '44', '13', '1', NULL, NULL);
INSERT INTO "arco_material" ("id", "arco_id", "material_id", "cantidad", "foto", "serie") VALUES ('742', '44', '11', '1', NULL, NULL);
INSERT INTO "arco_material" ("id", "arco_id", "material_id", "cantidad", "foto", "serie") VALUES ('743', '44', '11', '1', NULL, NULL);
INSERT INTO "arco_material" ("id", "arco_id", "material_id", "cantidad", "foto", "serie") VALUES ('744', '44', '15', '3', NULL, NULL);
INSERT INTO "arco_material" ("id", "arco_id", "material_id", "cantidad", "foto", "serie") VALUES ('745', '44', '14', '3', NULL, NULL);
INSERT INTO "arco_material" ("id", "arco_id", "material_id", "cantidad", "foto", "serie") VALUES ('746', '44', '16', '17', NULL, NULL);
INSERT INTO "arco_material" ("id", "arco_id", "material_id", "cantidad", "foto", "serie") VALUES ('747', '44', '31', '1', NULL, NULL);
INSERT INTO "arco_material" ("id", "arco_id", "material_id", "cantidad", "foto", "serie") VALUES ('748', '44', '17', '1', NULL, NULL);
INSERT INTO "arco_material" ("id", "arco_id", "material_id", "cantidad", "foto", "serie") VALUES ('749', '44', '12', '1', NULL, NULL);
INSERT INTO "arco_material" ("id", "arco_id", "material_id", "cantidad", "foto", "serie") VALUES ('750', '44', '12', '1', NULL, NULL);
INSERT INTO "arco_material" ("id", "arco_id", "material_id", "cantidad", "foto", "serie") VALUES ('751', '44', '26', '1', NULL, NULL);
INSERT INTO "arco_material" ("id", "arco_id", "material_id", "cantidad", "foto", "serie") VALUES ('752', '44', '9', '1', NULL, NULL);
INSERT INTO "arco_material" ("id", "arco_id", "material_id", "cantidad", "foto", "serie") VALUES ('753', '44', '30', '6', NULL, NULL);

-- revisiones: 14 registro(s)
INSERT INTO "revisiones" ("id", "arco_id", "fecha_mantenimiento", "tipo_mantenimiento", "observaciones", "tecnico_responsable") VALUES ('65', '31', '2026-05-12 13:03:00', 'Correctivo', 'Se cambiaron baterias por deterioro ', 'Carlos Serafin Chavelas Gonzalez');
INSERT INTO "revisiones" ("id", "arco_id", "fecha_mantenimiento", "tipo_mantenimiento", "observaciones", "tecnico_responsable") VALUES ('67', '32', '2026-05-07 15:00:00', 'Correctivo', 'Se reparo camara LPR Sur Norte y se reparo conecto de luz AC', 'Carlos Serafin Chavelas Gonzalez');
INSERT INTO "revisiones" ("id", "arco_id", "fecha_mantenimiento", "tipo_mantenimiento", "observaciones", "tecnico_responsable") VALUES ('70', '5', '2026-05-25 11:00:00', 'Correctivo', 'Se cambiaron las baterias por que ya no retienen carga, comprobado con el tester de baterias', 'Carlos Serafin Chavelas Gonzalez');
INSERT INTO "revisiones" ("id", "arco_id", "fecha_mantenimiento", "tipo_mantenimiento", "observaciones", "tecnico_responsable") VALUES ('74', '32', '2026-05-29 11:14:00', 'Correctivo', 'Se cambio el swich uno de la marca hikvision por un wiltek porque ya se bloqueo y dejo de pasar datos de red', 'Carlos Serafin Chavelas Gonzalez');
INSERT INTO "revisiones" ("id", "arco_id", "fecha_mantenimiento", "tipo_mantenimiento", "observaciones", "tecnico_responsable") VALUES ('76', '32', '2025-12-29 04:22:00', 'Correctivo', 'Cambio de enlace por daño', 'Luis Alberto Castro Garcia');
INSERT INTO "revisiones" ("id", "arco_id", "fecha_mantenimiento", "tipo_mantenimiento", "observaciones", "tecnico_responsable") VALUES ('78', '22', '2026-04-25 02:19:00', 'Correctivo', 'Cambio de baterias por incendio lo que ocaciono que se inflaran las baterias', 'Carlos Serafin Chavelas Gonzalez');
INSERT INTO "revisiones" ("id", "arco_id", "fecha_mantenimiento", "tipo_mantenimiento", "observaciones", "tecnico_responsable") VALUES ('79', '11', '2026-04-25 02:29:00', 'Correctivo', 'Cambio de baterias medio uso', 'Carlos Serafin Chavelas Gonzalez');
INSERT INTO "revisiones" ("id", "arco_id", "fecha_mantenimiento", "tipo_mantenimiento", "observaciones", "tecnico_responsable") VALUES ('80', '38', '2026-04-25 02:57:00', 'Correctivo', 'Se cambio Cable UTP por que fue cortado', 'Carlos Serafin Chavelas Gonzolez');
INSERT INTO "revisiones" ("id", "arco_id", "fecha_mantenimiento", "tipo_mantenimiento", "observaciones", "tecnico_responsable") VALUES ('81', '40', '2026-03-31 14:11:00', 'Preventivo', 'Limpieza de paneles Solares y cambio de baterias ', 'Carlos Serafin Chavelas Gonzalez');
INSERT INTO "revisiones" ("id", "arco_id", "fecha_mantenimiento", "tipo_mantenimiento", "observaciones", "tecnico_responsable") VALUES ('82', '41', '2026-03-31 14:04:00', 'Preventivo', 'Cambio de baterias vida util proxima acabar', 'Carlos Serafin Chavelas Gonzalez');
INSERT INTO "revisiones" ("id", "arco_id", "fecha_mantenimiento", "tipo_mantenimiento", "observaciones", "tecnico_responsable") VALUES ('83', '39', '2026-03-30 16:11:00', 'Correctivo', 'vestido de arco por daño causado por huracan, ', 'Carlos Serafin Chavelas Gonzalez');
INSERT INTO "revisiones" ("id", "arco_id", "fecha_mantenimiento", "tipo_mantenimiento", "observaciones", "tecnico_responsable") VALUES ('84', '42', '2026-04-21 15:49:00', 'Correctivo', 'Cambio de baterias ya no retienen carga', 'Carlos Serafin Chavelas Gonzalez');
INSERT INTO "revisiones" ("id", "arco_id", "fecha_mantenimiento", "tipo_mantenimiento", "observaciones", "tecnico_responsable") VALUES ('85', '44', '2026-04-21 14:40:00', 'Preventivo', 'Se cambio baterias y se limpiaron los paneles solared', 'Carlos Serafin Chavelas Gonzalez');
INSERT INTO "revisiones" ("id", "arco_id", "fecha_mantenimiento", "tipo_mantenimiento", "observaciones", "tecnico_responsable") VALUES ('86', '43', '2026-04-21 16:04:00', 'Preventivo', 'Se limpiaron los paneles solares y se cambiaron las baterias', 'Carlos Serafin Chavelas Gonzalez');

-- revision_material: 30 registro(s)
INSERT INTO "revision_material" ("id", "revision_id", "arco_material_id", "material_id", "cantidad", "foto", "serie", "accion") VALUES ('78', '65', '267', '13', '1', NULL, '5661015500079', 'cambio');
INSERT INTO "revision_material" ("id", "revision_id", "arco_material_id", "material_id", "cantidad", "foto", "serie", "accion") VALUES ('79', '65', '268', '13', '1', NULL, '5661015500080', 'cambio');
INSERT INTO "revision_material" ("id", "revision_id", "arco_material_id", "material_id", "cantidad", "foto", "serie", "accion") VALUES ('81', '67', '491', '7', '1', NULL, '8B0159EAAJ81B1A', 'cambio');
INSERT INTO "revision_material" ("id", "revision_id", "arco_material_id", "material_id", "cantidad", "foto", "serie", "accion") VALUES ('86', '70', '595', '13', '1', NULL, '5661015500076', 'cambio');
INSERT INTO "revision_material" ("id", "revision_id", "arco_material_id", "material_id", "cantidad", "foto", "serie", "accion") VALUES ('87', '70', '596', '13', '1', NULL, '5661015500077', 'cambio');
INSERT INTO "revision_material" ("id", "revision_id", "arco_material_id", "material_id", "cantidad", "foto", "serie", "accion") VALUES ('91', '74', '446', '9', '1', NULL, NULL, 'cambio');
INSERT INTO "revision_material" ("id", "revision_id", "arco_material_id", "material_id", "cantidad", "foto", "serie", "accion") VALUES ('93', '76', '487', '8', '1', NULL, NULL, 'cambio');
INSERT INTO "revision_material" ("id", "revision_id", "arco_material_id", "material_id", "cantidad", "foto", "serie", "accion") VALUES ('96', '78', '497', '13', '1', NULL, NULL, 'cambio');
INSERT INTO "revision_material" ("id", "revision_id", "arco_material_id", "material_id", "cantidad", "foto", "serie", "accion") VALUES ('97', '78', '498', '13', '1', NULL, NULL, 'cambio');
INSERT INTO "revision_material" ("id", "revision_id", "arco_material_id", "material_id", "cantidad", "foto", "serie", "accion") VALUES ('98', '79', '515', '13', '1', NULL, NULL, 'cambio');
INSERT INTO "revision_material" ("id", "revision_id", "arco_material_id", "material_id", "cantidad", "foto", "serie", "accion") VALUES ('99', '79', '516', '13', '1', NULL, NULL, 'cambio');
INSERT INTO "revision_material" ("id", "revision_id", "arco_material_id", "material_id", "cantidad", "foto", "serie", "accion") VALUES ('100', '80', '580', '30', '10', NULL, NULL, 'cambio');
INSERT INTO "revision_material" ("id", "revision_id", "arco_material_id", "material_id", "cantidad", "foto", "serie", "accion") VALUES ('101', '81', '657', '13', '1', NULL, NULL, 'cambio');
INSERT INTO "revision_material" ("id", "revision_id", "arco_material_id", "material_id", "cantidad", "foto", "serie", "accion") VALUES ('102', '81', '658', '13', '1', NULL, NULL, 'cambio');
INSERT INTO "revision_material" ("id", "revision_id", "arco_material_id", "material_id", "cantidad", "foto", "serie", "accion") VALUES ('103', '82', '665', '13', '1', NULL, NULL, 'cambio');
INSERT INTO "revision_material" ("id", "revision_id", "arco_material_id", "material_id", "cantidad", "foto", "serie", "accion") VALUES ('104', '82', '666', '13', '1', NULL, NULL, 'cambio');
INSERT INTO "revision_material" ("id", "revision_id", "arco_material_id", "material_id", "cantidad", "foto", "serie", "accion") VALUES ('105', '83', '631', '13', '1', NULL, NULL, 'cambio');
INSERT INTO "revision_material" ("id", "revision_id", "arco_material_id", "material_id", "cantidad", "foto", "serie", "accion") VALUES ('106', '83', '632', '13', '1', NULL, NULL, 'cambio');
INSERT INTO "revision_material" ("id", "revision_id", "arco_material_id", "material_id", "cantidad", "foto", "serie", "accion") VALUES ('107', '83', '712', '17', '1', NULL, NULL, 'cambio');
INSERT INTO "revision_material" ("id", "revision_id", "arco_material_id", "material_id", "cantidad", "foto", "serie", "accion") VALUES ('108', '83', '711', '10', '1', NULL, NULL, 'cambio');
INSERT INTO "revision_material" ("id", "revision_id", "arco_material_id", "material_id", "cantidad", "foto", "serie", "accion") VALUES ('109', '83', '640', '12', '1', NULL, NULL, 'cambio');
INSERT INTO "revision_material" ("id", "revision_id", "arco_material_id", "material_id", "cantidad", "foto", "serie", "accion") VALUES ('110', '83', '639', '12', '1', NULL, NULL, 'cambio');
INSERT INTO "revision_material" ("id", "revision_id", "arco_material_id", "material_id", "cantidad", "foto", "serie", "accion") VALUES ('111', '83', '635', '15', '2.5', NULL, NULL, 'cambio');
INSERT INTO "revision_material" ("id", "revision_id", "arco_material_id", "material_id", "cantidad", "foto", "serie", "accion") VALUES ('112', '83', '636', '14', '2.5', NULL, NULL, 'cambio');
INSERT INTO "revision_material" ("id", "revision_id", "arco_material_id", "material_id", "cantidad", "foto", "serie", "accion") VALUES ('113', '84', '713', '13', '1', NULL, NULL, 'cambio');
INSERT INTO "revision_material" ("id", "revision_id", "arco_material_id", "material_id", "cantidad", "foto", "serie", "accion") VALUES ('114', '84', '714', '13', '1', NULL, NULL, 'cambio');
INSERT INTO "revision_material" ("id", "revision_id", "arco_material_id", "material_id", "cantidad", "foto", "serie", "accion") VALUES ('115', '85', '740', '13', '1', NULL, NULL, 'cambio');
INSERT INTO "revision_material" ("id", "revision_id", "arco_material_id", "material_id", "cantidad", "foto", "serie", "accion") VALUES ('116', '85', '741', '13', '1', NULL, NULL, 'cambio');
INSERT INTO "revision_material" ("id", "revision_id", "arco_material_id", "material_id", "cantidad", "foto", "serie", "accion") VALUES ('117', '86', '729', '13', '1', NULL, NULL, 'cambio');
INSERT INTO "revision_material" ("id", "revision_id", "arco_material_id", "material_id", "cantidad", "foto", "serie", "accion") VALUES ('118', '86', '730', '13', '1', NULL, NULL, 'cambio');

-- revision_evidencias: 36 registro(s)
INSERT INTO "revision_evidencias" ("id", "revision_id", "filename", "mimetype", "created_at", "uploaded_at") VALUES ('78', '65', '1779077275_6a0a909b51b75.jpg', 'image/jpeg', '2026-05-17 22:07:55', '2026-05-17 22:07:55');
INSERT INTO "revision_evidencias" ("id", "revision_id", "filename", "mimetype", "created_at", "uploaded_at") VALUES ('79', '65', '1779077275_6a0a909b55be9.jpg', 'image/jpeg', '2026-05-17 22:07:55', '2026-05-17 22:07:55');
INSERT INTO "revision_evidencias" ("id", "revision_id", "filename", "mimetype", "created_at", "uploaded_at") VALUES ('81', '67', '1779087638_6a0ab9169530a.jpg', 'image/jpeg', '2026-05-18 01:00:38', '2026-05-18 01:00:38');
INSERT INTO "revision_evidencias" ("id", "revision_id", "filename", "mimetype", "created_at", "uploaded_at") VALUES ('86', '70', '1779865267_6a1696b3ab653.jpg', 'image/jpeg', '2026-05-27 01:01:07', '2026-05-27 01:01:07');
INSERT INTO "revision_evidencias" ("id", "revision_id", "filename", "mimetype", "created_at", "uploaded_at") VALUES ('87', '70', '1779865267_6a1696b3ae675.jpg', 'image/jpeg', '2026-05-27 01:01:07', '2026-05-27 01:01:07');
INSERT INTO "revision_evidencias" ("id", "revision_id", "filename", "mimetype", "created_at", "uploaded_at") VALUES ('88', '70', '1779865267_6a1696b3afed1.jpg', 'image/jpeg', '2026-05-27 01:01:07', '2026-05-27 01:01:07');
INSERT INTO "revision_evidencias" ("id", "revision_id", "filename", "mimetype", "created_at", "uploaded_at") VALUES ('89', '70', '1779865267_6a1696b3b165a.jpg', 'image/jpeg', '2026-05-27 01:01:07', '2026-05-27 01:01:07');
INSERT INTO "revision_evidencias" ("id", "revision_id", "filename", "mimetype", "created_at", "uploaded_at") VALUES ('90', '70', '1779865267_6a1696b3b2ab2.jpg', 'image/jpeg', '2026-05-27 01:01:07', '2026-05-27 01:01:07');
INSERT INTO "revision_evidencias" ("id", "revision_id", "filename", "mimetype", "created_at", "uploaded_at") VALUES ('96', '76', '1780211404_6a1bdecc1bf55.jpg', 'image/jpeg', '2026-05-31 01:10:04', '2026-05-31 01:10:04');
INSERT INTO "revision_evidencias" ("id", "revision_id", "filename", "mimetype", "created_at", "uploaded_at") VALUES ('97', '76', '1780211404_6a1bdecc1d9d9.jpg', 'image/jpeg', '2026-05-31 01:10:04', '2026-05-31 01:10:04');
INSERT INTO "revision_evidencias" ("id", "revision_id", "filename", "mimetype", "created_at", "uploaded_at") VALUES ('98', '76', '1780211404_6a1bdecc1e866.jpg', 'image/jpeg', '2026-05-31 01:10:04', '2026-05-31 01:10:04');
INSERT INTO "revision_evidencias" ("id", "revision_id", "filename", "mimetype", "created_at", "uploaded_at") VALUES ('99', '76', '1780211404_6a1bdecc20319.jpg', 'image/jpeg', '2026-05-31 01:10:04', '2026-05-31 01:10:04');
INSERT INTO "revision_evidencias" ("id", "revision_id", "filename", "mimetype", "created_at", "uploaded_at") VALUES ('100', '76', '1780211404_6a1bdecc21172.jpg', 'image/jpeg', '2026-05-31 01:10:04', '2026-05-31 01:10:04');
INSERT INTO "revision_evidencias" ("id", "revision_id", "filename", "mimetype", "created_at", "uploaded_at") VALUES ('101', '79', '1780216323_6a1bf20389942.jpg', 'image/jpeg', '2026-05-31 02:32:03', '2026-05-31 02:32:03');
INSERT INTO "revision_evidencias" ("id", "revision_id", "filename", "mimetype", "created_at", "uploaded_at") VALUES ('102', '81', '1780258497_6a1c96c14647d6.05367476.jpg', 'image/jpeg', '2026-05-31 14:14:57', '2026-05-31 14:14:57');
INSERT INTO "revision_evidencias" ("id", "revision_id", "filename", "mimetype", "created_at", "uploaded_at") VALUES ('103', '81', '1780258497_6a1c96c14a3063.86558227.jpg', 'image/jpeg', '2026-05-31 14:14:57', '2026-05-31 14:14:57');
INSERT INTO "revision_evidencias" ("id", "revision_id", "filename", "mimetype", "created_at", "uploaded_at") VALUES ('104', '82', '1780265572_6a1cb264770d82.14592795.jpg', 'image/jpeg', '2026-05-31 16:12:52', '2026-05-31 16:12:52');
INSERT INTO "revision_evidencias" ("id", "revision_id", "filename", "mimetype", "created_at", "uploaded_at") VALUES ('105', '83', '1780269150_6a1cc05e75e060.98323092.jpg', 'image/jpeg', '2026-05-31 17:12:30', '2026-05-31 17:12:30');
INSERT INTO "revision_evidencias" ("id", "revision_id", "filename", "mimetype", "created_at", "uploaded_at") VALUES ('106', '83', '1780269150_6a1cc05e780878.75085299.jpg', 'image/jpeg', '2026-05-31 17:12:30', '2026-05-31 17:12:30');
INSERT INTO "revision_evidencias" ("id", "revision_id", "filename", "mimetype", "created_at", "uploaded_at") VALUES ('107', '84', '1780272041_6a1ccba9d48162.76494754.jpg', 'image/jpeg', '2026-05-31 18:00:41', '2026-05-31 18:00:41');
INSERT INTO "revision_evidencias" ("id", "revision_id", "filename", "mimetype", "created_at", "uploaded_at") VALUES ('108', '84', '1780272041_6a1ccba9d75215.26657019.jpg', 'image/jpeg', '2026-05-31 18:00:41', '2026-05-31 18:00:41');
INSERT INTO "revision_evidencias" ("id", "revision_id", "filename", "mimetype", "created_at", "uploaded_at") VALUES ('109', '84', '1780272041_6a1ccba9d882e3.88109745.jpg', 'image/jpeg', '2026-05-31 18:00:41', '2026-05-31 18:00:41');
INSERT INTO "revision_evidencias" ("id", "revision_id", "filename", "mimetype", "created_at", "uploaded_at") VALUES ('110', '84', '1780272041_6a1ccba9d9b516.97328373.jpg', 'image/jpeg', '2026-05-31 18:00:41', '2026-05-31 18:00:41');
INSERT INTO "revision_evidencias" ("id", "revision_id", "filename", "mimetype", "created_at", "uploaded_at") VALUES ('111', '84', '1780272041_6a1ccba9dad495.19569479.jpg', 'image/jpeg', '2026-05-31 18:00:41', '2026-05-31 18:00:41');
INSERT INTO "revision_evidencias" ("id", "revision_id", "filename", "mimetype", "created_at", "uploaded_at") VALUES ('112', '84', '1780272041_6a1ccba9dbfc54.38078989.jpg', 'image/jpeg', '2026-05-31 18:00:41', '2026-05-31 18:00:41');
INSERT INTO "revision_evidencias" ("id", "revision_id", "filename", "mimetype", "created_at", "uploaded_at") VALUES ('113', '85', '1780286343_6a1d03879a8a28.46617032.jpg', 'image/jpeg', '2026-05-31 21:59:03', '2026-05-31 21:59:03');
INSERT INTO "revision_evidencias" ("id", "revision_id", "filename", "mimetype", "created_at", "uploaded_at") VALUES ('114', '85', '1780286343_6a1d03879e96e8.81994781.jpg', 'image/jpeg', '2026-05-31 21:59:03', '2026-05-31 21:59:03');
INSERT INTO "revision_evidencias" ("id", "revision_id", "filename", "mimetype", "created_at", "uploaded_at") VALUES ('115', '85', '1780286343_6a1d0387a04f50.69801048.jpg', 'image/jpeg', '2026-05-31 21:59:03', '2026-05-31 21:59:03');
INSERT INTO "revision_evidencias" ("id", "revision_id", "filename", "mimetype", "created_at", "uploaded_at") VALUES ('116', '85', '1780286343_6a1d0387a1c5c7.18320891.jpg', 'image/jpeg', '2026-05-31 21:59:03', '2026-05-31 21:59:03');
INSERT INTO "revision_evidencias" ("id", "revision_id", "filename", "mimetype", "created_at", "uploaded_at") VALUES ('117', '85', '1780286343_6a1d0387a35df1.89074428.jpg', 'image/jpeg', '2026-05-31 21:59:03', '2026-05-31 21:59:03');
INSERT INTO "revision_evidencias" ("id", "revision_id", "filename", "mimetype", "created_at", "uploaded_at") VALUES ('118', '85', '1780286343_6a1d0387a5e719.43446008.jpg', 'image/jpeg', '2026-05-31 21:59:03', '2026-05-31 21:59:03');
INSERT INTO "revision_evidencias" ("id", "revision_id", "filename", "mimetype", "created_at", "uploaded_at") VALUES ('119', '86', '1780293172_6a1d1e34112af1.58038565.jpg', 'image/jpeg', '2026-05-31 23:52:52', '2026-05-31 23:52:52');
INSERT INTO "revision_evidencias" ("id", "revision_id", "filename", "mimetype", "created_at", "uploaded_at") VALUES ('120', '86', '1780293172_6a1d1e3413cf88.39504541.jpg', 'image/jpeg', '2026-05-31 23:52:52', '2026-05-31 23:52:52');
INSERT INTO "revision_evidencias" ("id", "revision_id", "filename", "mimetype", "created_at", "uploaded_at") VALUES ('121', '86', '1780293172_6a1d1e34156c13.71653275.jpg', 'image/jpeg', '2026-05-31 23:52:52', '2026-05-31 23:52:52');
INSERT INTO "revision_evidencias" ("id", "revision_id", "filename", "mimetype", "created_at", "uploaded_at") VALUES ('122', '86', '1780293172_6a1d1e34174461.73483966.jpg', 'image/jpeg', '2026-05-31 23:52:52', '2026-05-31 23:52:52');
INSERT INTO "revision_evidencias" ("id", "revision_id", "filename", "mimetype", "created_at", "uploaded_at") VALUES ('123', '86', '1780293172_6a1d1e3418f0f5.09390810.jpg', 'image/jpeg', '2026-05-31 23:52:52', '2026-05-31 23:52:52');

-- infraestructura_nodos: 3 registro(s)
INSERT INTO "infraestructura_nodos" ("id", "tipo", "nombre", "ubicacion_id", "lat", "lng", "descripcion", "created_at") VALUES ('1', 'Puente/Poste', 'Salto Hospital Poste 12', '3', '17.605125', '-99.520715', NULL, '2026-05-24 17:53:14');
INSERT INTO "infraestructura_nodos" ("id", "tipo", "nombre", "ubicacion_id", "lat", "lng", "descripcion", "created_at") VALUES ('2', 'Sitio/Torre', 'Cumbres', '4', '16.810472', '-99.811859', NULL, '2026-05-27 01:17:10');
INSERT INTO "infraestructura_nodos" ("id", "tipo", "nombre", "ubicacion_id", "lat", "lng", "descripcion", "created_at") VALUES ('3', 'Sitio/Torre', 'Cuartel de Policias', '4', '16.755646', '-99.572439', NULL, '2026-05-31 03:29:47');

-- arco_infraestructura: 4 registro(s)
INSERT INTO "arco_infraestructura" ("id", "arco_id", "infraestructura_id", "created_at") VALUES ('2', '33', '1', '2026-05-25 00:09:38');
INSERT INTO "arco_infraestructura" ("id", "arco_id", "infraestructura_id", "created_at") VALUES ('3', '5', '2', '2026-05-27 01:17:10');
INSERT INTO "arco_infraestructura" ("id", "arco_id", "infraestructura_id", "created_at") VALUES ('4', '31', '2', '2026-05-27 01:17:10');
INSERT INTO "arco_infraestructura" ("id", "arco_id", "infraestructura_id", "created_at") VALUES ('6', '22', '3', '2026-05-31 03:33:53');

-- infraestructura_material: 21 registro(s)
INSERT INTO "infraestructura_material" ("id", "infraestructura_id", "material_id", "cantidad", "serie", "fecha_instalacion") VALUES ('4', '1', '19', '1', NULL, '2026-05-25 00:09:38');
INSERT INTO "infraestructura_material" ("id", "infraestructura_id", "material_id", "cantidad", "serie", "fecha_instalacion") VALUES ('5', '1', '8', '1', NULL, '2026-05-25 00:09:38');
INSERT INTO "infraestructura_material" ("id", "infraestructura_id", "material_id", "cantidad", "serie", "fecha_instalacion") VALUES ('6', '1', '18', '10', NULL, '2026-05-25 00:09:38');
INSERT INTO "infraestructura_material" ("id", "infraestructura_id", "material_id", "cantidad", "serie", "fecha_instalacion") VALUES ('7', '1', '8', '1', NULL, '2026-05-25 00:09:38');
INSERT INTO "infraestructura_material" ("id", "infraestructura_id", "material_id", "cantidad", "serie", "fecha_instalacion") VALUES ('8', '2', '20', '1', NULL, '2025-06-27 01:16:00');
INSERT INTO "infraestructura_material" ("id", "infraestructura_id", "material_id", "cantidad", "serie", "fecha_instalacion") VALUES ('9', '2', '23', '1', NULL, '2025-06-27 01:16:00');
INSERT INTO "infraestructura_material" ("id", "infraestructura_id", "material_id", "cantidad", "serie", "fecha_instalacion") VALUES ('10', '2', '8', '1', NULL, '2025-06-27 01:16:00');
INSERT INTO "infraestructura_material" ("id", "infraestructura_id", "material_id", "cantidad", "serie", "fecha_instalacion") VALUES ('11', '2', '8', '1', NULL, '2025-06-27 01:16:00');
INSERT INTO "infraestructura_material" ("id", "infraestructura_id", "material_id", "cantidad", "serie", "fecha_instalacion") VALUES ('12', '2', '8', '1', NULL, '2025-06-27 01:16:00');
INSERT INTO "infraestructura_material" ("id", "infraestructura_id", "material_id", "cantidad", "serie", "fecha_instalacion") VALUES ('13', '2', '8', '1', NULL, '2025-06-27 01:16:00');
INSERT INTO "infraestructura_material" ("id", "infraestructura_id", "material_id", "cantidad", "serie", "fecha_instalacion") VALUES ('14', '2', '8', '1', NULL, '2025-06-27 01:16:00');
INSERT INTO "infraestructura_material" ("id", "infraestructura_id", "material_id", "cantidad", "serie", "fecha_instalacion") VALUES ('25', '3', '20', '1', NULL, '2026-05-31 03:33:53');
INSERT INTO "infraestructura_material" ("id", "infraestructura_id", "material_id", "cantidad", "serie", "fecha_instalacion") VALUES ('26', '3', '9', '1', 'PS306GF-UPS-15A2408MX023', '2026-05-31 03:33:53');
INSERT INTO "infraestructura_material" ("id", "infraestructura_id", "material_id", "cantidad", "serie", "fecha_instalacion") VALUES ('27', '3', '13', '1', NULL, '2026-05-31 03:33:53');
INSERT INTO "infraestructura_material" ("id", "infraestructura_id", "material_id", "cantidad", "serie", "fecha_instalacion") VALUES ('28', '3', '13', '1', NULL, '2026-05-31 03:33:53');
INSERT INTO "infraestructura_material" ("id", "infraestructura_id", "material_id", "cantidad", "serie", "fecha_instalacion") VALUES ('29', '3', '15', '2.5', NULL, '2026-05-31 03:33:53');
INSERT INTO "infraestructura_material" ("id", "infraestructura_id", "material_id", "cantidad", "serie", "fecha_instalacion") VALUES ('30', '3', '14', '2.5', NULL, '2026-05-31 03:33:53');
INSERT INTO "infraestructura_material" ("id", "infraestructura_id", "material_id", "cantidad", "serie", "fecha_instalacion") VALUES ('31', '3', '29', '1', NULL, '2026-05-31 03:33:53');
INSERT INTO "infraestructura_material" ("id", "infraestructura_id", "material_id", "cantidad", "serie", "fecha_instalacion") VALUES ('32', '3', '12', '1', NULL, '2026-05-31 03:33:53');
INSERT INTO "infraestructura_material" ("id", "infraestructura_id", "material_id", "cantidad", "serie", "fecha_instalacion") VALUES ('33', '3', '12', '1', NULL, '2026-05-31 03:33:53');
INSERT INTO "infraestructura_material" ("id", "infraestructura_id", "material_id", "cantidad", "serie", "fecha_instalacion") VALUES ('34', '3', '30', '5', NULL, '2026-05-31 03:33:53');

-- infraestructura_revisiones: 1 registro(s)
INSERT INTO "infraestructura_revisiones" ("id", "infraestructura_id", "fecha_mantenimiento", "tipo_mantenimiento", "observaciones", "tecnico_responsable", "created_at") VALUES ('4', '3', '2026-04-25 03:54:00', 'Correctivo', 'Se cambio baterias por medio uso', 'Carlos Serafin Chavelas Gonzalez', '2026-05-31 11:55:09');

-- infraestructura_revision_material: 2 registro(s)
INSERT INTO "infraestructura_revision_material" ("id", "revision_id", "material_id", "cantidad", "serie") VALUES ('5', '4', '13', '1', '');
INSERT INTO "infraestructura_revision_material" ("id", "revision_id", "material_id", "cantidad", "serie") VALUES ('6', '4', '13', '1', '');

-- infraestructura_revision_evidencias: 3 registro(s)
INSERT INTO "infraestructura_revision_evidencias" ("id", "revision_id", "filename", "mimetype", "uploaded_at") VALUES ('1', '4', '1780250109_6a1c75fdd98917.13988036.jpg', 'image/jpeg', '2026-05-31 11:55:09');
INSERT INTO "infraestructura_revision_evidencias" ("id", "revision_id", "filename", "mimetype", "uploaded_at") VALUES ('2', '4', '1780250109_6a1c75fddf87c4.27906511.jpg', 'image/jpeg', '2026-05-31 11:55:09');
INSERT INTO "infraestructura_revision_evidencias" ("id", "revision_id", "filename", "mimetype", "uploaded_at") VALUES ('3', '4', '1780250109_6a1c75fde1f7a6.61719002.jpg', 'image/jpeg', '2026-05-31 11:55:09');

-- bitacoras_arco: 3 registro(s)
INSERT INTO "bitacoras_arco" ("id", "arco_id", "encargado", "observaciones", "fecha_registro") VALUES ('1', '23', 'Jose Luis Romero Palacios', 'Se Realizo La instalación sin poblemas', '2026-04-05 15:58:43');
INSERT INTO "bitacoras_arco" ("id", "arco_id", "encargado", "observaciones", "fecha_registro") VALUES ('3', '18', 'Carlos Chavelaz Gonzalez', '', '2026-04-05 20:11:39');
INSERT INTO "bitacoras_arco" ("id", "arco_id", "encargado", "observaciones", "fecha_registro") VALUES ('4', '22', 'luis', 'lfdjdl', '2026-04-26 13:01:17');

-- checklist_conceptos: 12 registro(s)
INSERT INTO "checklist_conceptos" ("id", "nombre", "activo") VALUES ('1', 'Instalación de Estructura del arco', '1');
INSERT INTO "checklist_conceptos" ("id", "nombre", "activo") VALUES ('2', 'Instalación de gabinete', '1');
INSERT INTO "checklist_conceptos" ("id", "nombre", "activo") VALUES ('3', 'Instalación de panel solar y batería', '1');
INSERT INTO "checklist_conceptos" ("id", "nombre", "activo") VALUES ('4', 'Antena RFID instalada y fijada', '1');
INSERT INTO "checklist_conceptos" ("id", "nombre", "activo") VALUES ('5', 'Cámara LPR instalada y enfocada', '1');
INSERT INTO "checklist_conceptos" ("id", "nombre", "activo") VALUES ('6', 'Conexión eléctrica con cable 1+1', '1');
INSERT INTO "checklist_conceptos" ("id", "nombre", "activo") VALUES ('7', 'Cableado UTP', '1');
INSERT INTO "checklist_conceptos" ("id", "nombre", "activo") VALUES ('8', 'Prueba de lectura RFID correcta', '1');
INSERT INTO "checklist_conceptos" ("id", "nombre", "activo") VALUES ('9', 'Prueba de captura de placas correcta', '1');
INSERT INTO "checklist_conceptos" ("id", "nombre", "activo") VALUES ('10', 'Servidor / envío a plataforma validado', '1');
INSERT INTO "checklist_conceptos" ("id", "nombre", "activo") VALUES ('11', 'Prueba de energía', '1');
INSERT INTO "checklist_conceptos" ("id", "nombre", "activo") VALUES ('12', 'Colocación de respaldo UPS', '1');

-- bitacora_checklist: 23 registro(s)
INSERT INTO "bitacora_checklist" ("id", "bitacora_id", "concepto_id", "realizado") VALUES ('1', '1', '1', '1');
INSERT INTO "bitacora_checklist" ("id", "bitacora_id", "concepto_id", "realizado") VALUES ('2', '1', '2', '1');
INSERT INTO "bitacora_checklist" ("id", "bitacora_id", "concepto_id", "realizado") VALUES ('3', '1', '3', '1');
INSERT INTO "bitacora_checklist" ("id", "bitacora_id", "concepto_id", "realizado") VALUES ('4', '1', '4', '1');
INSERT INTO "bitacora_checklist" ("id", "bitacora_id", "concepto_id", "realizado") VALUES ('5', '1', '5', '1');
INSERT INTO "bitacora_checklist" ("id", "bitacora_id", "concepto_id", "realizado") VALUES ('6', '1', '7', '1');
INSERT INTO "bitacora_checklist" ("id", "bitacora_id", "concepto_id", "realizado") VALUES ('7', '1', '8', '1');
INSERT INTO "bitacora_checklist" ("id", "bitacora_id", "concepto_id", "realizado") VALUES ('8', '1', '9', '1');
INSERT INTO "bitacora_checklist" ("id", "bitacora_id", "concepto_id", "realizado") VALUES ('9', '1', '10', '1');
INSERT INTO "bitacora_checklist" ("id", "bitacora_id", "concepto_id", "realizado") VALUES ('10', '1', '11', '1');
INSERT INTO "bitacora_checklist" ("id", "bitacora_id", "concepto_id", "realizado") VALUES ('21', '3', '1', '1');
INSERT INTO "bitacora_checklist" ("id", "bitacora_id", "concepto_id", "realizado") VALUES ('22', '3', '2', '1');
INSERT INTO "bitacora_checklist" ("id", "bitacora_id", "concepto_id", "realizado") VALUES ('23', '3', '3', '1');
INSERT INTO "bitacora_checklist" ("id", "bitacora_id", "concepto_id", "realizado") VALUES ('24', '3', '4', '1');
INSERT INTO "bitacora_checklist" ("id", "bitacora_id", "concepto_id", "realizado") VALUES ('25', '3', '7', '1');
INSERT INTO "bitacora_checklist" ("id", "bitacora_id", "concepto_id", "realizado") VALUES ('26', '3', '8', '1');
INSERT INTO "bitacora_checklist" ("id", "bitacora_id", "concepto_id", "realizado") VALUES ('27', '3', '9', '1');
INSERT INTO "bitacora_checklist" ("id", "bitacora_id", "concepto_id", "realizado") VALUES ('28', '3', '10', '1');
INSERT INTO "bitacora_checklist" ("id", "bitacora_id", "concepto_id", "realizado") VALUES ('29', '3', '11', '1');
INSERT INTO "bitacora_checklist" ("id", "bitacora_id", "concepto_id", "realizado") VALUES ('30', '4', '1', '1');
INSERT INTO "bitacora_checklist" ("id", "bitacora_id", "concepto_id", "realizado") VALUES ('31', '4', '2', '1');
INSERT INTO "bitacora_checklist" ("id", "bitacora_id", "concepto_id", "realizado") VALUES ('32', '4', '6', '1');
INSERT INTO "bitacora_checklist" ("id", "bitacora_id", "concepto_id", "realizado") VALUES ('33', '4', '9', '1');

-- Ajuste de secuencias identity/serial
SELECT setval(seq, max_id, is_called)
FROM (
  SELECT pg_get_serial_sequence('public.users', 'id') AS seq,
         GREATEST((SELECT COALESCE(MAX(id), 0) FROM "users"), 1) AS max_id,
         (SELECT COALESCE(MAX(id), 0) > 0 FROM "users") AS is_called
) s
WHERE seq IS NOT NULL;
SELECT setval(seq, max_id, is_called)
FROM (
  SELECT pg_get_serial_sequence('public.ubicaciones', 'id') AS seq,
         GREATEST((SELECT COALESCE(MAX(id), 0) FROM "ubicaciones"), 1) AS max_id,
         (SELECT COALESCE(MAX(id), 0) > 0 FROM "ubicaciones") AS is_called
) s
WHERE seq IS NOT NULL;
SELECT setval(seq, max_id, is_called)
FROM (
  SELECT pg_get_serial_sequence('public.materiales', 'id') AS seq,
         GREATEST((SELECT COALESCE(MAX(id), 0) FROM "materiales"), 1) AS max_id,
         (SELECT COALESCE(MAX(id), 0) > 0 FROM "materiales") AS is_called
) s
WHERE seq IS NOT NULL;
SELECT setval(seq, max_id, is_called)
FROM (
  SELECT pg_get_serial_sequence('public.arcos', 'id') AS seq,
         GREATEST((SELECT COALESCE(MAX(id), 0) FROM "arcos"), 1) AS max_id,
         (SELECT COALESCE(MAX(id), 0) > 0 FROM "arcos") AS is_called
) s
WHERE seq IS NOT NULL;
SELECT setval(seq, max_id, is_called)
FROM (
  SELECT pg_get_serial_sequence('public.arco_material', 'id') AS seq,
         GREATEST((SELECT COALESCE(MAX(id), 0) FROM "arco_material"), 1) AS max_id,
         (SELECT COALESCE(MAX(id), 0) > 0 FROM "arco_material") AS is_called
) s
WHERE seq IS NOT NULL;
SELECT setval(seq, max_id, is_called)
FROM (
  SELECT pg_get_serial_sequence('public.revisiones', 'id') AS seq,
         GREATEST((SELECT COALESCE(MAX(id), 0) FROM "revisiones"), 1) AS max_id,
         (SELECT COALESCE(MAX(id), 0) > 0 FROM "revisiones") AS is_called
) s
WHERE seq IS NOT NULL;
SELECT setval(seq, max_id, is_called)
FROM (
  SELECT pg_get_serial_sequence('public.revision_material', 'id') AS seq,
         GREATEST((SELECT COALESCE(MAX(id), 0) FROM "revision_material"), 1) AS max_id,
         (SELECT COALESCE(MAX(id), 0) > 0 FROM "revision_material") AS is_called
) s
WHERE seq IS NOT NULL;
SELECT setval(seq, max_id, is_called)
FROM (
  SELECT pg_get_serial_sequence('public.revision_evidencias', 'id') AS seq,
         GREATEST((SELECT COALESCE(MAX(id), 0) FROM "revision_evidencias"), 1) AS max_id,
         (SELECT COALESCE(MAX(id), 0) > 0 FROM "revision_evidencias") AS is_called
) s
WHERE seq IS NOT NULL;
SELECT setval(seq, max_id, is_called)
FROM (
  SELECT pg_get_serial_sequence('public.infraestructura_nodos', 'id') AS seq,
         GREATEST((SELECT COALESCE(MAX(id), 0) FROM "infraestructura_nodos"), 1) AS max_id,
         (SELECT COALESCE(MAX(id), 0) > 0 FROM "infraestructura_nodos") AS is_called
) s
WHERE seq IS NOT NULL;
SELECT setval(seq, max_id, is_called)
FROM (
  SELECT pg_get_serial_sequence('public.infraestructura_material', 'id') AS seq,
         GREATEST((SELECT COALESCE(MAX(id), 0) FROM "infraestructura_material"), 1) AS max_id,
         (SELECT COALESCE(MAX(id), 0) > 0 FROM "infraestructura_material") AS is_called
) s
WHERE seq IS NOT NULL;
SELECT setval(seq, max_id, is_called)
FROM (
  SELECT pg_get_serial_sequence('public.infraestructura_revisiones', 'id') AS seq,
         GREATEST((SELECT COALESCE(MAX(id), 0) FROM "infraestructura_revisiones"), 1) AS max_id,
         (SELECT COALESCE(MAX(id), 0) > 0 FROM "infraestructura_revisiones") AS is_called
) s
WHERE seq IS NOT NULL;
SELECT setval(seq, max_id, is_called)
FROM (
  SELECT pg_get_serial_sequence('public.infraestructura_revision_material', 'id') AS seq,
         GREATEST((SELECT COALESCE(MAX(id), 0) FROM "infraestructura_revision_material"), 1) AS max_id,
         (SELECT COALESCE(MAX(id), 0) > 0 FROM "infraestructura_revision_material") AS is_called
) s
WHERE seq IS NOT NULL;
SELECT setval(seq, max_id, is_called)
FROM (
  SELECT pg_get_serial_sequence('public.infraestructura_revision_evidencias', 'id') AS seq,
         GREATEST((SELECT COALESCE(MAX(id), 0) FROM "infraestructura_revision_evidencias"), 1) AS max_id,
         (SELECT COALESCE(MAX(id), 0) > 0 FROM "infraestructura_revision_evidencias") AS is_called
) s
WHERE seq IS NOT NULL;
SELECT setval(seq, max_id, is_called)
FROM (
  SELECT pg_get_serial_sequence('public.bitacoras_arco', 'id') AS seq,
         GREATEST((SELECT COALESCE(MAX(id), 0) FROM "bitacoras_arco"), 1) AS max_id,
         (SELECT COALESCE(MAX(id), 0) > 0 FROM "bitacoras_arco") AS is_called
) s
WHERE seq IS NOT NULL;
SELECT setval(seq, max_id, is_called)
FROM (
  SELECT pg_get_serial_sequence('public.checklist_conceptos', 'id') AS seq,
         GREATEST((SELECT COALESCE(MAX(id), 0) FROM "checklist_conceptos"), 1) AS max_id,
         (SELECT COALESCE(MAX(id), 0) > 0 FROM "checklist_conceptos") AS is_called
) s
WHERE seq IS NOT NULL;
SELECT setval(seq, max_id, is_called)
FROM (
  SELECT pg_get_serial_sequence('public.bitacora_checklist', 'id') AS seq,
         GREATEST((SELECT COALESCE(MAX(id), 0) FROM "bitacora_checklist"), 1) AS max_id,
         (SELECT COALESCE(MAX(id), 0) > 0 FROM "bitacora_checklist") AS is_called
) s
WHERE seq IS NOT NULL;

COMMIT;
